### ISSUE TITLE
change the classes

### ISSUE THREAD

**Issue by hushuai1** [mikel-brostrom/Yolov5_DeepSort_Pytorch#1]
hello where can i change the class for car not only person

**Comment by mikel-brostrom** [comment]
Hi,

Thank you for showing interest in my repository!
You can change the class by changing the default value of the 'classes' argument from 0 (person in COCO) to 2 (car in COCO). However, that would make little sense as the deep learning metric that is mentioned in this repo is trained on a person re-identification ONLY dataset (Mars) and further refined on anther person re-identification dataset (REID) for better performance. You would need to find a model for deep sort trained on a car re-identification dataset if you want to track cars.
