### ISSUE TITLE
DeepSort not tracking when Detector lost object

### ISSUE THREAD

**Issue by OleksiiYeromenko** [mikel-brostrom/Yolov5_DeepSort_Pytorch#101]
I've compared results on the same video with pure Yolov5 and Yolov5 + DeepSort - result is the same.
Whenever Yolov5 lost an object behind an obstacle, combined model also does not output object bounding boxes.
Maybe I'm doing something wrong? Why DeepSort (Kalman filter) does not predict the next position of an object?

**Comment by mikel-brostrom** [comment]
It does. The prediction is done one step ahead, which let us make the association process from one frame to the next, but only if it found a matching track. Check:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/189e8410da7b6e2478a11a69f77bbcdcd3eeb93f/deep_sort_pytorch/deep_sort/deep_sort.py#L26

More specifically these lines:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/189e8410da7b6e2478a11a69f77bbcdcd3eeb93f/deep_sort_pytorch/deep_sort/deep_sort.py#L39

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/189e8410da7b6e2478a11a69f77bbcdcd3eeb93f/deep_sort_pytorch/deep_sort/deep_sort.py#L40

**Comment by OleksiiYeromenko** [comment]
Yes, thanks. I'm trying for cases where Detector fails to properly identify an item, to use prediction from DeepSort for 5-10 steps as a source for object bbox.

**Comment by sainivedh** [comment]
Can this be used for re-identification task as well ?.. Suppose if person reappears after 100-200 frames will the model able to recognize him ?. Assume that RE-ID model is trained on Market-1501 dataset.

**Comment by mikel-brostrom** [comment]
> Can this be used for re-identification task as well ?.. Suppose if person reappears after 100-200 frames will the model able to recognize him ?. Assume that RE-ID model is trained on Market-1501 dataset.

Yes, Deep Sort is a re-identification algorithm
