### ISSUE TITLE
weigths of deepsort ckpt.t7

### ISSUE THREAD

**Issue by yuninn** [mikel-brostrom/Yolov5_DeepSort_Pytorch#104]
I trained my data through yolov5,and I want to track my data. Is the initial weight (CKPT. T7) of deep sort still available?

**Comment by mikel-brostrom** [comment]
Yes, you can find them here: https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6
