### ISSUE TITLE
have trouble in loading the weights

### ISSUE THREAD

**Issue by Gintka** [mikel-brostrom/Yolov5_DeepSort_Pytorch#106]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/20283535/122416218-22866880-cfbb-11eb-9917-01de48379abc.png"
after typing the _python track.py --source_ command in terminal, I got this error. I downloaded yolo5s.pt and yolo5l.pt in yolov5/weightgs/. what should I do

**Comment by mikel-brostrom** [comment]
In the new release the weights are downloaded automatically. Select your weights [yolov5s, yolov5m, yolov5l, ...] in:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/02590ed0b62f5a2a2c65f51695d27ac6b9e23fd5/track.py#L254

And then run 

`python track.py --source ...`

**Comment by mikel-brostrom** [comment]
I recommend you to clone again and try the method above

**Comment by Gintka** [comment]
solved, thank you
