### ISSUE TITLE
Question about deepsort update frequency

### ISSUE THREAD

**Issue by HowieMa** [mikel-brostrom/Yolov5_DeepSort_Pytorch#11]
In [track.py](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/master/track.py#L176), you update the deepsort module per object, as the variable 'det' has size (num of obj, 6). However, in the code of  [YOLOv3+ DeepSORT](https://github.com/ZQPei/deep_sort_pytorch/blob/master/yolov3_deepsort.py#L99), they just update once per image. 
Is there anything I miss here?

**Comment by mikel-brostrom** [comment]
Your are totally right @HowieMa! I will try to fix this in the coming weeks. That you for reminding me of this

**Comment by mikel-brostrom** [comment]
I just updated track.py. Now the deepsort module is updated once per image, instead of once per detected object. You should see some inference speedup when the number of detected objects is large
