### ISSUE TITLE
Object Tracking Counting

### ISSUE THREAD

**Issue by alkalinehawk** [mikel-brostrom/Yolov5_DeepSort_Pytorch#111]
I would love to be able to add a feature that counts the number of people that cross an arbitrarily drawn line using bounding box intersection and then by tracking centroid you would know what direction they came from. I have programmed this in dlib with open cv but don't know how to apply this to DeepSort. Would you have any ideas?

**Comment by electrolabopen** [comment]
to do people counting, how can I implement it?
