### ISSUE TITLE
this is python,where is c++?

### ISSUE THREAD

**Issue by henbucuoshanghai** [mikel-brostrom/Yolov5_DeepSort_Pytorch#114]

**Comment by mikel-brostrom** [comment]
You can export both the Yolo and Deep Sort model to onnx. This will let you rewrite all the surrounding code and load the models in C++

**Comment by henbucuoshanghai** [comment]
only onnx？ is there any successful code in github?

**Comment by mikel-brostrom** [comment]
I searched for: 

`deepsort c++ github`

This is what i got:

https://github.com/apennisi/deep_sort

**Comment by henbucuoshanghai** [comment]
。。。yolo5+deepsort&nbsp; c++? tks

**Comment by mikel-brostrom** [comment]
Yolov5 only exists for the Pytorch framwork

**Comment by henbucuoshanghai** [comment]
where is c++ version of deepsort?&nbsp; thank you
