### ISSUE TITLE
Yolo video source

### ISSUE THREAD

**Issue by kimgw-pl** [mikel-brostrom/Yolov5_DeepSort_Pytorch#116]
Hello, I'm using yolov4 deepsort on my project.
Like yolov5 deepsort, I want to use http stream as the source, but I'm wondering which method to use.

**Comment by mikel-brostrom** [comment]
Check https://github.com/ultralytics/yolov5/blob/33202b7f0bbfcc55860e8c0cafbf13f227e77a84/utils/datasets.py#L276

cv2.VideoCapture takes care of that
