### ISSUE TITLE
Error in MOT16 evaluation script

### ISSUE THREAD

**Issue by VirajBagal** [mikel-brostrom/Yolov5_DeepSort_Pytorch#118]
Hi. I followed the steps mentioned in the 'Evaluation Wiki' to evaluate the pretrained model on MOT16 train split. The `track.py` runs fine but I get the following error when the bash script runs the `run_mot_challenge.py` file. Please help.

```
Evaluating ch_yolov5m_deep_sort

    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.2811 sec
Tracker ch_yolov5m_deep_sort was unable to be evaluated.
Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
Traceback (most recent call last):
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
Traceback (most recent call last):
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 91, in <module>
    evaluator.evaluate(dataset_list, metrics_list)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 180, in evaluate
    raise err
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
```

**Comment by mikel-brostrom** [comment]
I updated the eval.sh script. I recommend you to start from a clean slate. Let me know if it works for you!

**Comment by mikel-brostrom** [comment]
Notice that I also updated the Evaluation Wiki page

**Comment by VirajBagal** [comment]
It is working now. Thanks!

But I am getting different results than those reported in the Wiki. Is there any randomization during test time? 

                                            MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT16-02                           34.705    76.197    35.485    42.242    86.21     16.667    48.148    35.185    24.651    7533      10300     1205      139       9         26        19        268       
MOT16-04                           60.046    76.018    60.254    74.09     84.264    42.169    42.169    15.663    42.278    35235     12322     6580      99        35        35        13        366       
MOT16-05                           54.473    76.241    55.588    73.57     80.359    42.4      51.2      6.4       36.994    5016      1802      1226      76        53        64        8         159       
MOT16-09                           59.92     82.114    60.776    77.953    81.944    56        44        0         45.978    4098      1159      903       45        14        11        0         76        
MOT16-10                           52.801    74.603    53.742    64.483    85.722    31.481    53.704    14.815    36.424    7943      4375      1323      116       17        29        8         341       
MOT16-11                           57.456    83.957    57.903    80.532    78.064    53.623    36.232    10.145    44.536    7388      1786      2076      41        37        25        7         84        
MOT16-13                           31.301    68.152    32.341    47.24     76.022    11.215    57.944    30.841    16.256    5409      6041      1706      119       12        62        33        331       
COMBINED                           51.598    76.463    52.173    65.777    82.863    34.236    48.743    17.021    36.116    72622     37785     15019     635       177       252       88        1625      

                                              IDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT16-02                           34.451    25.666    52.38     4577      13256     4161      
MOT16-04                           65.555    61.598    70.056    29294     18263     12521     
MOT16-05                           39.663    37.988    41.493    2590      4228      3652      
MOT16-09                           54.26     52.939    55.649    2783      2474      2218      
MOT16-10                           55.523    48.644    64.667    5992      6326      3274      
MOT16-11                           53.836    54.687    53.011    5017      4157      4447      
MOT16-13                           38.75     31.415    50.555    3597      7853      3518      
COMBINED                           54.381    48.774    61.444    53850     56557     33791     

                                          Dets      GT_Dets   IDs       GT_IDs    
MOT16-02                           8738      17833     54        54        
MOT16-04                           41815     47557     118       83        
MOT16-05                           6242      6818      40        125       
MOT16-09                           5001      5257      27        25        
MOT16-10                           9266      12318     51        54        
MOT16-11                           9464      9174      67        69        
MOT16-13                           7115      11450     64        107       
COMBINED                           87641     110407    421       517       
`

**Comment by mikel-brostrom** [comment]
Yes, you get slightly different results:

Tracker | MOTA | IDF1 | MT | ML | IDs | FPS
-- | -- | -- | -- | -- | -- | --
yolov5m_crowdhuman+deep_sort (conf_thres=0.4) | 51.6 | 53.8 | 25.1% | 13.0% | 422 | <21 (Nvidia quadro P2000)
yours | 51.6 | 54.4 | 17.7% | 8.8% | 421 | ?

Run a `git diff track.py`. Do you get any different hparams compared to the original ones?

**Comment by VirajBagal** [comment]
I ran `git diff track.py`. I got no output. There is no difference in hparams. I am using the default ones. I have one more question, sorry for my ignorance, but is the denominator always 1000 in both MT and ML? Coz the values of MT and ML are 177 and 88 respectively, and u represented them as 17.7% and 8.8% in the table.

**Comment by ssbilakeri** [comment]
> It is working now. Thanks!
> 
> But I am getting different results than those reported in the Wiki. Is there any randomization during test time?
> 
> ```
>                                         MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
> ```
> 
> MOT16-02 34.705 76.197 35.485 42.242 86.21 16.667 48.148 35.185 24.651 7533 10300 1205 139 9 26 19 268
> MOT16-04 60.046 76.018 60.254 74.09 84.264 42.169 42.169 15.663 42.278 35235 12322 6580 99 35 35 13 366
> MOT16-05 54.473 76.241 55.588 73.57 80.359 42.4 51.2 6.4 36.994 5016 1802 1226 76 53 64 8 159
> MOT16-09 59.92 82.114 60.776 77.953 81.944 56 44 0 45.978 4098 1159 903 45 14 11 0 76
> MOT16-10 52.801 74.603 53.742 64.483 85.722 31.481 53.704 14.815 36.424 7943 4375 1323 116 17 29 8 341
> MOT16-11 57.456 83.957 57.903 80.532 78.064 53.623 36.232 10.145 44.536 7388 1786 2076 41 37 25 7 84
> MOT16-13 31.301 68.152 32.341 47.24 76.022 11.215 57.944 30.841 16.256 5409 6041 1706 119 12 62 33 331
> COMBINED 51.598 76.463 52.173 65.777 82.863 34.236 48.743 17.021 36.116 72622 37785 15019 635 177 252 88 1625
> 
> ```
>                                           IDF1      IDR       IDP       IDTP      IDFN      IDFP      
> ```
> 
> MOT16-02 34.451 25.666 52.38 4577 13256 4161
> MOT16-04 65.555 61.598 70.056 29294 18263 12521
> MOT16-05 39.663 37.988 41.493 2590 4228 3652
> MOT16-09 54.26 52.939 55.649 2783 2474 2218
> MOT16-10 55.523 48.644 64.667 5992 6326 3274
> MOT16-11 53.836 54.687 53.011 5017 4157 4447
> MOT16-13 38.75 31.415 50.555 3597 7853 3518
> COMBINED 54.381 48.774 61.444 53850 56557 33791
> 
> ```
>                                       Dets      GT_Dets   IDs       GT_IDs    
> ```
> 
> MOT16-02 8738 17833 54 54
> MOT16-04 41815 47557 118 83
> MOT16-05 6242 6818 40 125
> MOT16-09 5001 5257 27 25
> MOT16-10 9266 12318 51 54
> MOT16-11 9464 9174 67 69
> MOT16-13 7115 11450 64 107
> COMBINED 87641 110407 421 517
> `

Hi 
could you please share steps followed for evaluation

**Comment by VirajBagal** [comment]
I followed the evaluation wiki page of this repo as it is. No changes from my side. 

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/wiki/Evaluation

**Comment by ssbilakeri** [comment]
Could you please share the code ..I'm getting some errors

**Comment by ssbilakeri** [comment]
Also, which weight files you have used. I want to see the generated .text
file of yours .can you please share

**Comment by mikel-brostrom** [comment]
As @VirajBagal previously wrote you should follow what is written under:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/wiki/Evaluation

If you get any errors I recommend you to start from a clean slate and then run the evaluation script

**Comment by mikel-brostrom** [comment]
> I have one more question, sorry for my ignorance, but is the denominator always 1000 in both MT and ML? Coz the values of MT and ML are 177 and 88 respectively, and u represented them as 17.7% and 8.8% in the table.

Yes. I haven't checked the metrics' code but in the official documentation the state the following:

Measure | Better | Perfect | Description
-- | -- | -- | --
| MT | higher | 100% | Mostly tracked targets. The ratio of ground-truth  trajectories that are covered by a track hypothesis for at least 80% of  their respective life span. |
ML | lower | 0% | Mostly lost targets. The ratio of ground-truth  trajectories that are covered by a track hypothesis for at most 20% of  their respective life span.

I hence expect the official MOT16 evaluation script to generate MT and ML metric in % and that no other post-process is needed.

**Comment by mikel-brostrom** [comment]
But correct me if I am wrong @VirajBagal :smile:

**Comment by xuaixi** [comment]
> Hi. I followed the steps mentioned in the 'Evaluation Wiki' to evaluate the pretrained model on MOT16 train split. The `track.py` runs fine but I get the following error when the bash script runs the `run_mot_challenge.py` file. Please help.
> 
> ```
> Evaluating ch_yolov5m_deep_sort
> 
>     MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.2811 sec
> Tracker ch_yolov5m_deep_sort was unable to be evaluated.
> Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
> Traceback (most recent call last):
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
>     res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
>     data = dataset.get_preprocessed_seq_data(raw_data, cls)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
>     self._check_unique_ids(raw_data)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
>     raise TrackEvalException(exc_str)
> trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
> Traceback (most recent call last):
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 91, in <module>
>     evaluator.evaluate(dataset_list, metrics_list)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 180, in evaluate
>     raise err
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
>     res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
>     data = dataset.get_preprocessed_seq_data(raw_data, cls)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
>     self._check_unique_ids(raw_data)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
>     raise TrackEvalException(exc_str)
> trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
> ```

**Comment by xuaixi** [comment]
I met the same problems , so i want to know how you deal with them ,

**Comment by xuaixi** [comment]
> Hi. I followed the steps mentioned in the 'Evaluation Wiki' to evaluate the pretrained model on MOT16 train split. The `track.py` runs fine but I get the following error when the bash script runs the `run_mot_challenge.py` file. Please help.
> 
> ```
> Evaluating ch_yolov5m_deep_sort
> 
>     MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.2811 sec
> Tracker ch_yolov5m_deep_sort was unable to be evaluated.
> Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
> Traceback (most recent call last):
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
>     res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
>     data = dataset.get_preprocessed_seq_data(raw_data, cls)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
>     self._check_unique_ids(raw_data)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
>     raise TrackEvalException(exc_str)
> trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
> Traceback (most recent call last):
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 91, in <module>
>     evaluator.evaluate(dataset_list, metrics_list)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 180, in evaluate
>     raise err
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
>     res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
>     data = dataset.get_preprocessed_seq_data(raw_data, cls)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
>     self._check_unique_ids(raw_data)
>   File "/SSD1TB/viraj/MOT/yolov5_deepsort/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
>     raise TrackEvalException(exc_str)
> trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 2, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 28 29 30 31 32)
> ```

I met the same problems , so i want to know how you deal with them , #

**Comment by mikel-brostrom** [comment]
Reclone and run the evaluation script
