### ISSUE TITLE
How can I use this for single class?

### ISSUE THREAD

**Issue by hammadyounas2008** [mikel-brostrom/Yolov5_DeepSort_Pytorch#119]
I have trained yolov5 for one fruit class oranges I want to count and track the fruit on tree how can I use this repo?

**Comment by mikel-brostrom** [comment]
You will need to implement a counter, this repo does not contain such functionality

**Comment by ccl-private** [comment]
I trained a yolov5 for a custom class, can I track my custom class use this repo?

**Comment by ccl-private** [comment]
or should I training the re-id model my self？
https://github.com/ZQPei/deep_sort_pytorch#training-the-re-id-model

**Comment by hammadyounas2008** [comment]
author has no reply :(

**Comment by mikel-brostrom** [comment]
> or should I training the re-id model my self？
> https://github.com/ZQPei/deep_sort_pytorch#training-the-re-id-model

Ideally yes. You can start with the default tracking functionality to wether it fulfills your requirements or not.

> I trained a yolov5 for a custom class, can I track my custom class use this repo?

Yes, check: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch#filter-tracked-classes

**Comment by hammadyounas2008** [comment]
I used the trained model of yolov5, i want to track and count the number of objects in the video but it is not working, How can it gives the random values to the objects

**Comment by mikel-brostrom** [comment]
Again, there is not counting functionality in this repo. You need to implement it yourself

**Comment by ccl-private** [comment]
@hammadyounas2008 maybe you can draw the trajectory of the object

**Comment by hammadyounas2008** [comment]
@ccl-private How to avoid that?

**Comment by hammadyounas2008** [comment]
@mikel-brostrom How can I implement in this track.py file?

**Comment by ccl-private** [comment]
@hammadyounas2008 maybe you need to implement a algorithm yourself.
I also plan to count objects amount in the near future.
