### ISSUE TITLE
track.py only detec for 1 sec in video

### ISSUE THREAD

**Issue by ramostapiai** [mikel-brostrom/Yolov5_DeepSort_Pytorch#120]
When entering a video to analyze and detect using tract.py detects only the first second of video, leaving only 1 second of video saved. Is there a problem with the video or with the script?

**Comment by mikel-brostrom** [comment]
Are using the colab script? In that case you will see that:

```bash
# extract 3 seconds worth of video frames of it
!y | ffmpeg -ss 00:00:00 -i test.avi -t 00:00:02 -c copy out.avi`
```

extract a few seconds of you video
