### ISSUE TITLE
Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!

### ISSUE THREAD

**Issue by rcgopi100** [mikel-brostrom/Yolov5_DeepSort_Pytorch#121]
Thanks for this library.

I am getting error when I try to run on my video file.
==================================
# get yolov5m model trained on the crowd-human dataset
!wget -nc https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/releases/download/v.2.0/crowdhuman_yolov5m.pt -O /content/Yolov5_DeepSort_Pytorch/yolov5/weights/crowdhuman_yolov5m.pt

# get the test video from the repo
!wget -nc https://github.com/rcgopi100/AllDownloads/blob/main/persons_walking.mp4
# extract 5 seconds worth of video frames of it
!y | ffmpeg -ss 00:00:00 -i persons_walking.mp4 -t 00:00:05 -c copy out_persons_walking.mp4
===================================================
Error:
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘persons_walking.mp4’

persons_walking.mp4     [ <=>                ] 113.27K  --.-KB/s    in 0.02s   

2021-07-12 21:26:24 (4.72 MB/s) - ‘persons_walking.mp4’ saved [115992]

/bin/bash: y: command not found
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56045618a000] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56045618a000] moov atom not found
persons_walking.mp4: Invalid data found when processing input

**Comment by mikel-brostrom** [comment]
!wget -nc https://github.com/rcgopi100/AllDownloads/raw/main/persons_walking.avi

```bash
Saving to: ‘persons_walking.avi’

persons_walking.avi 100%[===================>]  11.91M  33.6MB/s    in 0.4s    

2021-07-14 09:29:33 (33.6 MB/s) - ‘persons_walking.avi’ saved [12488926/12488926]
```

!wget -nc https://github.com/rcgopi100/AllDownloads/blob/main/persons_walking.mp4

```bash
Saving to: ‘persons_walking.mp4’

persons_walking.mp4     [ <=>                ] 113.38K  --.-KB/s    in 0.1s    

2021-07-14 09:29:33 (948 KB/s) - ‘persons_walking.mp4’ saved [116096]

```

It looks like the mp4 video causes the problems. It works with the avi version of it :smiley:

**Comment by rcgopi100** [comment]
Thank you it is working only for avi format. Let me know if you fix it for mp4 format

**Comment by yrj109** [comment]
zhe same question with me!
