### ISSUE TITLE
last location tracked object

### ISSUE THREAD

**Issue by Hilal-Urun** [mikel-brostrom/Yolov5_DeepSort_Pytorch#123]
Hi, I'm trying to find last location of tracked object on IP Camera with adding object id and tracked loc taked from to_tlbr() function than grouped locations according to id's and access last location of the object according to the id. Because its leave and last loc always updated I do not handle with this problem. Could you guide me please, I'm lost :)
Thanks for your time..

**Comment by mikel-brostrom** [comment]
I do not fully understand what you mean. You want to get the last location in tlbr format before the objects exit the field of view of the camera and they are removed from deep sort tracks?

**Comment by Hilal-Urun** [comment]
yes exactly I want to do that

**Comment by mikel-brostrom** [comment]
You would need to add a queue to each track so that they can keep a record of their last X locations. On deleting the track the last inserted location can be extracted for further processing
