### ISSUE TITLE
How to use custom dataset in YOLO and  set up the data format?

### ISSUE THREAD

**Issue by Kyangzhou** [mikel-brostrom/Yolov5_DeepSort_Pytorch#124]
I see your videos in BILIBILI and I use Detectron2 to detect my objects and how to use DeepSort to track them? It would be better if you can start a new project. Thank you very much!

**Comment by mikel-brostrom** [comment]
Yolov5 is Pareto optimal on all indicators. This is:

- When  comparing any YOLOv5 with the same accuracy of any of the object detectors under Detectron2, the inference speed of Yolov5 is higher. 
- When YOLOv5 is compared to any of the object detectors under Detectron2 with the same speed, the accuracy is higher.

Hence, there is no reason for creating a repo based on Detectron2. I recommend you to train a Yolov5 model on your dataset

**Comment by mikel-brostrom** [comment]
If you for some reason still want to use your Detectron2 model you have to comply with the deepsort input. This is:  

1. A list of bboxes in xywh format 
2. A list of confidence values.

**Comment by Kyangzhou** [comment]
Sorry for the late reply, follow your advice and I get the right results by using YOLOv5. Thank you very much!
