### ISSUE TITLE
Stuck in tentative

### ISSUE THREAD

**Issue by sudhanv09** [mikel-brostrom/Yolov5_DeepSort_Pytorch#128]
Hi I am attempting to port this repo to ROS. I am having trouble with deepsort, it is stuck in tentative. Can you help me sort this out

**Comment by mikel-brostrom** [comment]
Sorry, I am not so familiar with ROS. By maybe somebody else can help you out here. Good luck!

**Comment by sudhanv09** [comment]
I'm sorry for not making it clear. My problem is with deepsort and not ROS. 

In deep_sort/sort/tracker.py I observe that I'm stuck in _initiate_track function and self.tracks is not updating.
The is_tentative function of Track gives True and never updates

**Comment by mikel-brostrom** [comment]
A track is in `Tentative` state until the object has been associated `n_init` consecutive times. How are you feeding the images to `track.py`?

**Comment by sudhanv09** [comment]
`def detect(device, image, yolo_weights, deep_sort_weights, config_deepsort):
    
    out = 'inference/output'
    img_size = 640
    conf_thres = 0.4
    iou_thres = 0.5
    augment = True
    agnostic_nms =True
    final_out = dict()
    tlwh_bboxs = []

    cfg = get_config()
    cfg.merge_from_file(config_deepsort)
    attempt_download(deep_sort_weights, repo='mikel-brostrom/Yolov5_DeepSort_Pytorch')
    deepsort = DeepSort(deep_sort_weights,
                        max_dist=cfg.DEEPSORT.MAX_DIST, min_confidence=cfg.DEEPSORT.MIN_CONFIDENCE,
                        nms_max_overlap=cfg.DEEPSORT.NMS_MAX_OVERLAP, max_iou_distance=cfg.DEEPSORT.MAX_IOU_DISTANCE,
                        max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET,
                        use_cuda=False)                   

    device = select_device(device)
    if os.path.exists(out):
        shutil.rmtree(out)  
    os.makedirs(out)  
    half = device.type != 'cpu'  
    
    model = attempt_load(yolo_weights, map_location=device)  
    stride = int(model.stride.max())  
    imgsz = check_img_size(img_size, s=stride)  
    names = model.module.names if hasattr(model, 'module') else model.names  
    if half:
        model.half()  

    if device.type != 'cpu':
        model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  

    # image going to YOLO as tensor (BCHW)
    img = torch.from_numpy(image).to(device)
    img = img.half() if half else img.float()  
    img /= 255.0 
    if img.ndimension() == 3:
        img = img.unsqueeze(0)

    assert img.shape == (1,3,480,640)        

    # image going to deepsort (HWC) (480, 640, 3)
    image = image.transpose(1, 2, 0)

    # Inference
    pred = model(img, augment=augment)[0]

    # Apply NMS
    pred = non_max_suppression(pred, conf_thres, iou_thres, agnostic=agnostic_nms)

    for _, det in enumerate(pred): 

        if det is not None and len(det):

            det[:, :4] = scale_coords(
                img.shape[2:], det[:, :4], image.shape).round()
      
            for c in det[:, -1].unique():
                n = (det[:, -1] == c).sum()  # detections per class
                final_out[names[int(c)]] = n

            xywh_bboxs = []
            confs = []

            for *xyxy, conf, _ in det:
                x_c, y_c, bbox_w, bbox_h = xyxy_to_xywh(*xyxy)
                xywh_obj = [x_c, y_c, bbox_w, bbox_h]
                xywh_bboxs.append(xywh_obj)
                confs.append([conf.item()])
            
            xywhs = torch.Tensor(xywh_bboxs)
            confss = torch.Tensor(confs)

            outputs = deepsort.update(xywhs, confss, image)

            # print(f'out: {outputs}')

            if len(outputs) > 0:
                bbox_xyxy = outputs[:, :4]
                identities = outputs[:, -1]
                draw_boxes(image, bbox_xyxy, identities)
                # to MOT format
                tlwh_bboxs = xyxy_to_tlwh(bbox_xyxy)

            else:
                deepsort.increment_ages()

    return final_out, tlwh_bboxs`

image comes from ROS. image input from ROS is not a problem. I could be wrong somewhere in the detect method

**Comment by sudhanv09** [comment]
```
# image going to YOLO as tensor (BCHW)
    img = torch.from_numpy(image).to(device)
    img = img.half() if half else img.float()  
    img /= 255.0 
    if img.ndimension() == 3:
        img = img.unsqueeze(0)

    assert img.shape == (1,3,480,640)        

    # image going to deepsort (HWC) (480, 640, 3)
    image = image.transpose(1, 2, 0)

    # Inference
    pred = model(img, augment=augment)[0]

    # Apply NMS
    pred = non_max_suppression(pred, conf_thres, iou_thres, agnostic=agnostic_nms)

    for _, det in enumerate(pred): 

        if det is not None and len(det):

            det[:, :4] = scale_coords(
                img.shape[2:], det[:, :4], image.shape).round()
      
            for c in det[:, -1].unique():
                n = (det[:, -1] == c).sum()  # detections per class
                final_out[names[int(c)]] = n

            xywh_bboxs = []
            confs = []

            for *xyxy, conf, _ in det:
                x_c, y_c, bbox_w, bbox_h = xyxy_to_xywh(*xyxy)
                xywh_obj = [x_c, y_c, bbox_w, bbox_h]
                xywh_bboxs.append(xywh_obj)
                confs.append([conf.item()])
            
            xywhs = torch.Tensor(xywh_bboxs)
            confss = torch.Tensor(confs)

            outputs = deepsort.update(xywhs, confss, image)

            # print(f'out: {outputs}')

            if len(outputs) > 0:
                bbox_xyxy = outputs[:, :4]
                identities = outputs[:, -1]
                draw_boxes(image, bbox_xyxy, identities)
                # to MOT format
                tlwh_bboxs = xyxy_to_tlwh(bbox_xyxy)

        else:
            deepsort.increment_ages()

    return final_out, tlwh_bboxs
```
like this

**Comment by mikel-brostrom** [comment]
I have the feeling that maybe only a single image is feed to yolo. It makes no sense otherwise that the tracks get stuck in tentative. Either they should be deleted or accepted as valid tracks if there is a continuous stream of images. What do you feed to:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/track.py#L78

?

**Comment by sudhanv09** [comment]
Actually I'm not using this line. I feed my images directly to the loop. So the webcam uploads to ROS and then I get the images from ROS. 

"I have the feeling that maybe only a single image is feed to yolo."
This could be the case. I'll check it out
