### ISSUE TITLE
new id assigned after an object gets lost for a few frames

### ISSUE THREAD

**Issue by matakahas** [mikel-brostrom/Yolov5_DeepSort_Pytorch#129]
Thank you so much for creating and maintaining this wonderful project!

I am trying to track cars using this project, and I am having some issues with ID assignments.
As the screenshots show, when the tracker loses an object even for a couple of frames, it assigns a new id upon finding the object again.
![Screen Shot 2021-07-16 at 9 49 03 AM](https://user-images.githubusercontent.com/61954130/125982526-daa9a934-6aa6-4d0f-aecd-5841d14ab916.png)
![Screen Shot 2021-07-16 at 9 49 09 AM](https://user-images.githubusercontent.com/61954130/125982536-ccc9adc2-4bf0-415f-9be1-c708c9fd686b.png)
  
The `max_age` parameter is set to the default. I tried tuning the other parameters like `max_dist` and `max_iou_distance`, but they do not seem to have made any difference. Do you have any advice on this? Thank you for your help in advance!

**Comment by mikel-brostrom** [comment]
> Thank you so much for creating and maintaining this wonderful project!

I am glad you like it :smile: 

> Do you have any advice on this?

I would recommend you to train Yolov5 on a more extensive car dataset. The reason behind it simply that the object detector is not good enough on cars. This is easily experienced when running the MOT16 tracking evaluation (only pedestrians) on the original Yolov5 models trained only on COCO filtered on the person class, vs a model that has been fine-tuned on the crowd human dataset. The MOTA goes from ~32 to ~53, which means that it does a much better job tracking pedestrians when fine-tuning the model.

**Comment by matakahas** [comment]
I'm sorry it took me a long time to respond to your suggestion! I found another pretrained model based on a dataset featuring more cars, and my tracker is working better now. In case anyone is tackling a similar task, I used the following model:

[https://github.com/VilledeMontreal/urban-detection/releases](https://github.com/VilledeMontreal/urban-detection/releases)

Thanks for your suggestion!

**Comment by ruiming46zrm** [comment]
i think there is another problem, is the Reid precision.  It's hard to avoid shelter appearance any where, when a now box come out , we may put the box into right traceId.

**Comment by mikel-brostrom** [comment]
There are many reasons for the ID switching. One is the performance of the object detector an another of course is the DeepSort implementation, as @ruiming46zrm points out. 

Previously in DeepSort, the ID assignment was solely done based on the appearance descriptor. Now you can choose in what proportion to use the appearance descriptor vs the position in the assignment by using the lambda parameter here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/bc6e00a61d70e7a42af576aed8c38db7da986638/deep_sort_pytorch/deep_sort/sort/tracker.py#L38

In the paper they state that  "during our experiments we found that setting λ = 0 is a reasonable choice when there is substantial camera motion". Assuming that you have very little to no camera, setting lambda to 0.6-0.7 should yield even better results.

Let me know if this gives you even better results @matakahas !

**Comment by ruiming46zrm** [comment]
I haven't got better results when I use lambda=0.75,  many happens like following scene:
person_a goes to a place where sheltered by wall, so trackId_a disappears, 
but in few frames person_b goes out off the wall in the same place and deepsort regards person_b as trackId_a.
even they look difference. 
so during my work , i found that lambda=0.2 is a optimal value.

the above bad case still happens when lambda=any because the reId comparision is not accurate enough.
how can I reduce it by more strict position measurement **between disappeared trackid and new appeared person bounding box**?
