### ISSUE TITLE
Human tracking using stereo cameras

### ISSUE THREAD

**Issue by huynhtnhut97** [mikel-brostrom/Yolov5_DeepSort_Pytorch#130]
Hello author,

Thank you for ur awesome project. I am using it on stereo cameras, I successfully use threading to simultaneously detect and track objects from 2 cameras. However, I want the ID of one person from 2 cameras to be the same. Do u have any function to fuse the ID? or any idea on how I can do that?

Thank you very much for your time.

**Comment by huynhtnhut97** [comment]
I shouldn't forget to mention that objects are visible in both camera. Not moving from one camera to another camera.

**Comment by mikel-brostrom** [comment]
You maybe find this issue interesting. 

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/103#issuecomment-876415083
