### ISSUE TITLE
Bug in saving results as video 

### ISSUE THREAD

**Issue by VirajBagal** [mikel-brostrom/Yolov5_DeepSort_Pytorch#132]
I added `--save-vid` argument to the `track.py` command of `eval.sh`. The results are saved at `inference/output` but the files are named as `00xxxx.jpg.mp4` where xxxx goes from 0001 to 01050. Is this result expected? Can you please elaborate why there are so many files? I expected to have only 7 video files because evaluation is done only on 7 videos. Moreover, these result mp4 files aren't running on Ubuntu. I mean, the videov is opening but it is not getting played. No error pops up. Is this due to Ubuntu or a bug while saving the videos? Can you please check if you are able to play the output mp4 files after running the script **with saving videos** ?

**Comment by VirajBagal** [comment]
I now confirm that the `.mp4` videos do run on my Ubuntu system. So, there is certainly some bug in the code while saving the video.

**Comment by mikel-brostrom** [comment]
> Is this result expected?

Yes. Your are not supposed to perform tracking on an image folder. It it just intended for evaluation. If you want MOT16 inference results in the form of a video you should run `tracker.py` on the MOT16 videos, not the image folder.

**Comment by VirajBagal** [comment]
I also ran FairMOT on MOT16 using this repo: https://github.com/ifzhang/FairMOT

Here as well, the model runs on images but the results can be saved as video, and the output videos run completely fine with tracking bboxes on each detected human in the video. Can you please try to incorporate that functionality in `track.py`?

**Comment by mikel-brostrom** [comment]
It makes more sense to me to keep the implementation as it is. If the source is an image folder the output should be an image folder. If the input is a video the output should be a video. You can just generate a video out of the input images if you want the result as a video.

**Comment by VirajBagal** [comment]
@mikel-brostrom Makes sense. Yet, I have created a pull request. It enables output video saving (in addition to image saving). I think it might be beneficial/desirable to/for others. Please take a look at it. Thanks!

**Comment by mikel-brostrom** [comment]
Any interesting findings by the way in the comparison between FairMOT and this repo?

**Comment by VirajBagal** [comment]
I didn't dive deep into the codes. But here are some points when I tried running both these models on MOT16 evalution:
- I found the sample-wise dictionary of results of different metrics (CLEAR, Count, Identity) from this repo very helpful in logging. I either didn't look close enough or couldn't find similar code in FairMOT repo. 
- In terms of MOTA, FairMOT outperforms Yolov5 + DeepSORT on all video sequences of MOT16-train split except for one. This is the case because FairMOT has very low FPs and ID switches compared to Yolov5 + DeepSORT. I believe FairMOT is better in terms of ID switches because of usage of centerpoints (via CenterNet) of objectsd for tracking them. This removes the ambiguity of one box containing many objects and one object in many boxes. 
- In terms of localization of objects (measured by MOTP), both the models are similar.
- I really liked the bounding box and identity notation in the output videos of this repo. In FairMOT, identity of the box is barely visible w/o squeezing your eyes :). You can see the videos in the following mentioned report. 

I am writing a weights and biases report on the comparison of both of these models. I have logged the tabular samplewise metric results as well as tracking output videos of both these models on MOT16-train split. You can find the in-development report here: 
https://wandb.ai/vbagal/Multi-Object%20Tracking/reports/Yolov5_DeepSort-vs-FairMOT--Vmlldzo4Nzk0MjQ
