### ISSUE TITLE
Structure of the .txt file created with --save-txt

### ISSUE THREAD

**Issue by ElDorado34** [mikel-brostrom/Yolov5_DeepSort_Pytorch#137]
Hello can someone explain to me how the .txt file created with the --save-txt command in the output folder is structured?
In other words what do the columns of the file stand for?
Best regards

**Comment by mikel-brostrom** [comment]
Hi! You can read about the MOT16 format here:
https://motchallenge.net/instructions/

**Comment by lonnylundsten** [comment]
Hello,

Regarding the MOT16 format, how do I map the id in the save-txt file back to the class label? The class labels show up correctly on the video but they aren't in the txt file which gets saved and there isn't an additional way to map the id number in the MOT file to the original class labels, unless I missed an additional flag?

**Comment by legeiger** [comment]
> there isn't an additional way to map the id number in the MOT file to the original class labels

Is there any way to save the class id or class name?
maybe with an other flag than `--save-txt`

**Comment by lonnylundsten** [comment]
At about line 158 in the track.py file you can alter the info written to the text files.
I've added the class name and file path using this:

                          with open(txt_path, 'a') as f:
                               f.write(('%g ' * 10 + '\n') % (frame_idx, id, bbox_left,
                                                           bbox_top, bbox_w, bbox_h, -1, -1, -1, -1))  # label format

**Comment by legeiger** [comment]
thanks you saved my day - found your solution in #55 already :)
Thank you once again!

**Comment by BenzKukkik** [comment]
> At about line 200 in the track.py file you can alter the info written to the text files. I've added the file path, class name, and confidence using this:
> 
> ```
>                         if save_txt:
>                             # to MOT format
>                             bbox_left = output[0]
>                             bbox_top = output[1]
>                             bbox_w = output[2] - output[0]
>                             bbox_h = output[3] - output[1]
>                             c = int(cls)  # integer class
>                             label = f'{id:0.0f} {names[c]} {conf:.2f}'
>                             # Write MOT compliant results to file
>                             with open(txt_path + '.txt', 'a') as f:
>                                 f.write((str(path) + ' ' +'%g ' * 10 + ' ' + label +'\n') % (frame_idx + 1, id, bbox_left,  # MOT format
>                                                                bbox_top, bbox_w, bbox_h, -1, -1, -1, i))
> ```

I try to use your code but error is (UnboundLocalError: local variable 'label' referenced before assignment)
