### ISSUE TITLE
Add a parameter to consider also Mahalanobis-distance when assigning detections to tracked objects

### ISSUE THREAD

**Issue by mrtj** [mikel-brostrom/Yolov5_DeepSort_Pytorch#138]
The authors of the [original DeepSort paper](https://arxiv.org/pdf/1703.07402.pdf) combine both the Mahalanobis-distance (motion info from Kalman filters) and cosine-distance (similarity info from deep embeddings) in a weighted sum formula (eq. 5 in the paper):

<i>c</i><sub><i>i,j</i></sub> = &lambda;<i>d</i><sup>(1)</sup>(<i>i, j</i>) + (1 &#8211; &lambda;)d</i><sup>(2)</sup>(<i>i, j</i>)

where <i>d</i><sup>(1)</sup>(<i>i, j</i>) and d</i><sup>(2)</sup>(<i>i, j</i>) are the Mahalanobis and cosine-distance respectively. Then they say that "during our experiments we found that setting &lambda; = 0 is a reasonable choice when there is substantial camera motion". Indeed, in the source code of the tracker, this lambda parameter is not even implemented and the distance of the Kalman-filter prediction is simply used to gate the cosine distances (I guess [here](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/deep_sort_pytorch/deep_sort/sort/tracker.py#L103)). 

My use case is to track vehicles with a fixed position camera. In this scenario, considering also the prediction of the Kalman filter when calculating the distance matrix could be beneficial, as the cars might look similar, but they have also a quite predictable movement. At least it would be interesting to experiment with values of lambda different from zero and see if the tracking can be improved. Currently, I have experienced quite a lot of identity switches when a car occludes a similar-looking another car, as the supposed velocity is not considered during the match, and both cars are still inside the gated distance threshold.

I am unsure though, how could I implement this lambda parameter. Any hints? Thank you.

**Comment by mikel-brostrom** [comment]
I guess you could add the Mahalonobis distance, calculated under:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/a60dcf9300ee7673b7d484e8ebb363b9a6408b81/deep_sort_pytorch/deep_sort/sort/kalman_filter.py#L188

to the cost matrix here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/9935d81231192f6a977954c4ff5d8361071ee6cf/deep_sort_pytorch/deep_sort/sort/nn_matching.py#L175

In that way you can call an association admissible if it is within the gating region of both metrics. The best match would then be the observation with minimum cosine distance as well as Mahalonobis distance. Which should go under:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/9935d81231192f6a977954c4ff5d8361071ee6cf/deep_sort_pytorch/deep_sort/sort/linear_assignment.py#L80

Let me know if you get it working. PR are accepted of course!

**Comment by mikel-brostrom** [comment]
I found an implementation here: https://github.com/michael-camilleri/deep_sort.
I will have it merged before the end of the year

**Comment by mikel-brostrom** [comment]
This is now implemented! You can set lambda here: 

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/bc6e00a61d70e7a42af576aed8c38db7da986638/deep_sort_pytorch/deep_sort/sort/tracker.py#L38

Let me know if this makes any difference!
