### ISSUE TITLE
cannot save the txt?

### ISSUE THREAD

**Issue by yuzehui1996** [mikel-brostrom/Yolov5_DeepSort_Pytorch#14]
Hi, 
Great job for your repo.
However, the detections cannot save to txt, such as frame_index, car_identities or bbox_xyxy.

**Comment by mikel-brostrom** [comment]
Hi @yuzehui1996,
Thank you!

I will try to find some time to generate an output that complies with the MOT challenge in the coming weeks

**Comment by mikel-brostrom** [comment]
I now added the possibility to generate MOT compliant results @yuzehui1996

**Comment by yuzehui1996** [comment]
> I now added the possibility to generate MOT compliant results @yuzehui1996

Thanks a lot !
