### ISSUE TITLE
nothing occures when I run track.py

### ISSUE THREAD

**Issue by besbesmany** [mikel-brostrom/Yolov5_DeepSort_Pytorch#141]
I pip install requirment.txt
I add my video.mp4 and pt file under yolov5 folder

`python3 track.py --source video.mp4 --yolo_weights yolov5/best.pt --img 640 --save-txt

what is missing, where the output should be
should I use video with detected cars or the deepsort will detect my cars

`
![1](https://user-images.githubusercontent.com/35992924/127662461-3021a33c-22d9-42bf-a68c-771a12dfe872.png)
![2](https://user-images.githubusercontent.com/35992924/127662573-1bb70849-f116-4336-a5c3-00e52c0c0672.png)

**Comment by iresusharma** [comment]
hi,
try to run like this,    python3 file.py --source video.mp4 --show-vid
--save-txt = is for saving the predictions.

**Comment by jlldavi98** [comment]
Me too,
when I run "python3 track.py --source test.avi --show-vid --yolo_weights yolov5/weights/crowdhuman_yolo5m.pt --classes 0"
there are nothing changes about the video, the window shows the original video. So is what " save-vid " saved video.

![IMG_20210808_160258](https://user-images.githubusercontent.com/57584271/128625375-af492459-b055-46c8-b790-6c57af39f5f9.jpg)
![IMG_20210808_160318](https://user-images.githubusercontent.com/57584271/128625392-d169be6f-9db6-42ef-ad56-155989d3cd8c.jpg)

**Comment by hrishikeshps94** [comment]
Try a larger image size  like 1920 'python3 track.py --source video.mp4 --yolo_weights yolov5/best.pt --img 640 --save-txt' change --img to 1920
