### ISSUE TITLE
how to draw trajectory line?

### ISSUE THREAD

**Issue by besbesmany** [mikel-brostrom/Yolov5_DeepSort_Pytorch#143]
I want to draw trajectory line for moving object through the video
how to do that?

**Comment by mikel-brostrom** [comment]
I am planning to implement this in a near future.

However, if you want to implement it yourself, you can simply store the historical bbox locations in a deque with a maximum nr of element (so that doesn't grow infinitely big). And then use CV2 to display those on the image

**Comment by besbesmany** [comment]
In fact I don't know how , can you tell me when exactly you will apply 
I want to combine your method with trackpy method like this
[https://github.com/soft-matter/trackpy-examples/blob/master/notebooks/walkthrough.ipynb](url)
to get this image

![1](https://user-images.githubusercontent.com/35992924/128065477-61e335a7-f1e4-4ccf-94bc-5c190a41bc96.png)

**Comment by besbesmany** [comment]
can you tell me in details what code should I add in Yolov5_DeepSort_Pytorch to get this figure please?
