### ISSUE TITLE
Nothing occures when I run track.py, too

### ISSUE THREAD

**Issue by jlldavi98** [mikel-brostrom/Yolov5_DeepSort_Pytorch#145]
when I run "python3 track.py --source test.avi --show-vid --yolo_weights yolov5/weights/crowdhuman_yolo5m.pt --classes 0"
There are nothing changes about the video, the window shows the original video. So is what " --save-vid " saved video.

python3.9 & torch-1.81+cu111-cp39 & torchvision-0.9.1+cu111-cp39
![IMG_20210808_160318](https://user-images.githubusercontent.com/57584271/128625817-9b70b2e5-bf53-4bbd-949d-963421d193a5.jpg)

But the terminal display program is finished
![IMG_20210808_160258](https://user-images.githubusercontent.com/57584271/128625694-5102f959-be1c-4fb8-ba81-7660f7ece2c8.jpg)

Could you tell me what the problem is or what is missing?

**Comment by mikel-brostrom** [comment]
I tried this on a freshly cloned version and I have no problems what so ever with the visualization of the results, so I suggest you to start from a clean slate. Reclone, get the video and run inference on it.

If you want  to save the original video along with the infered bboxes just add the `--save-vid` flag to your command

**Comment by kentaroy47** [comment]
I'm not sure why, but my windows machine had a similar problem (webcam tracked fine, but video source outputted no outputs)
Moving on to my linux machine made deepsort work fine. Might be related to your environment, not the code itself.
