### ISSUE TITLE
Why the video is bigger than fact？？？

### ISSUE THREAD

**Issue by SaoDiSengA** [mikel-brostrom/Yolov5_DeepSort_Pytorch#146]
when i run track.py with a video,the displaying video get bigger than original video.Why?how to update the code.

**Comment by mikel-brostrom** [comment]
If you wan the resulting video to be the exact same size of the original one. Try;

```
vid_cap.set(cv2.CAP_PROP_FRAME_WIDTH, img.shape[0])
vid_cap.set(cv2.CAP_PROP_FRAME_HEIGHT, img.shape[1])
```

under:

https://github.com/ultralytics/yolov5/blob/e96c74b5a1c4a27934c5d8ad52cde778af248ed8/detect.py#L181

Let me know if this works for you!

**Comment by SaoDiSengA** [comment]
> If you wan the resulting video to be the exact same size of the original one. Try;
> 
> ```
> vid_cap.set(cv2.CAP_PROP_FRAME_WIDTH, img.shape[0])
> vid_cap.set(cv2.CAP_PROP_FRAME_HEIGHT, img.shape[1])
> ```
> 
> under:
> 
> https://github.com/ultralytics/yolov5/blob/e96c74b5a1c4a27934c5d8ad52cde778af248ed8/detect.py#L181
> 
> Let me know if this works for you!

Thank you for reply! I already find a way to workout.
Track.py line 173,174:
                im0 = cv2.resize(im0, (960, 540))   # use cv2.resize to resize video
                cv2.imshow(p, im0)
