### ISSUE TITLE
CUDA problem

### ISSUE THREAD

**Issue by xiaofeng-c** [mikel-brostrom/Yolov5_DeepSort_Pytorch#150]
**i run the track.py with the command python track.py --save-vid,but a new problem oocur as follow:**
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
**do you know how to solve it?Thank you.**

**Comment by xiaofeng-c** [comment]
i seem to know the reason,i appoint the number of GPU like --device 5,but it seem to can't  recognize while use the command of CUDA_VISIBLE_DEVICES=5,it recognize.

**Comment by mikel-brostrom** [comment]
The device flag does not specify the nr of gpus to use, but the specific CUDA device to use. If you want  to use multiple GPUs specify that as following: `--gpu 1,2,3,4,5`

**Comment by xiaofeng-c** [comment]
Ok,i get it,thank you!
