### ISSUE TITLE
crowdhuman_yolov5m.pt

### ISSUE THREAD

**Issue by Edurccl** [mikel-brostrom/Yolov5_DeepSort_Pytorch#152]
Hello, I want to know what tricks you have when training your `crowdhuman_yolov5m.pt `weights. The yolo weights I trained on the `crowdhuman dataset` tested on the `MOT16` dataset were significantly lower than your results. The following are my parameter settings and results.

**parameters**

    parser.add_argument('--weights', type=str, default='weights/yolov5m.pt', help='initial weights path')

    # Add a small target detection layer on the basis of yolov5m.yaml
    parser.add_argument('--cfg', type=str, default='models/yolov5m_add_detect.yaml', help='model.yaml path')      

    parser.add_argument('--data', type=str, default='data/CrowdHuman_self.yaml', help='data.yaml path')
    parser.add_argument('--hyp', type=str, default='data/hyp.scratch.yaml', help='hyperparameters path')
    parser.add_argument('--epochs', type=int, default=30)
    parser.add_argument('--batch-size', type=int, default=4, help='total batch size for all GPUs')
    parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='[train, test] image sizes')
    parser.add_argument('--rect', action='store_true', help='rectangular training')
    parser.add_argument('--resume', nargs='?', const=True, default=True, help='resume most recent training')
    parser.add_argument('--nosave', action='store_true', help='only save final checkpoint')
    parser.add_argument('--notest', action='store_true', help='only test final epoch')
    parser.add_argument('--noautoanchor', action='store_true', help='disable autoanchor check')
    parser.add_argument('--evolve', action='store_true', help='evolve hyperparameters')
    parser.add_argument('--bucket', type=str, default='', help='gsutil bucket')
    parser.add_argument('--cache-images', action='store_true', help='cache images for faster training')
    parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')
    parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--multi-scale', action='store_true', help='vary img-size +/- 50%%')
    parser.add_argument('--single-cls', action='store_true', help='train multi-class data as single-class')
    parser.add_argument('--adam', action='store_true', help='use torch.optim.Adam() optimizer')
    parser.add_argument('--sync-bn', action='store_true', help='use SyncBatchNorm, only available in DDP mode')
    parser.add_argument('--local_rank', type=int, default=-1, help='DDP parameter, do not modify')
    parser.add_argument('--workers', type=int, default=0, help='maximum number of dataloader workers')
    parser.add_argument('--project', default='runs/train', help='save to project/name')
    parser.add_argument('--entity', default=None, help='W&B entity')
    parser.add_argument('--name', default='exp', help='save to project/name')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--quad', action='store_true', help='quad dataloader')
    parser.add_argument('--linear-lr', action='store_true', help='linear LR')
    parser.add_argument('--label-smoothing', type=float, default=0.1, help='Label smoothing epsilon')
    parser.add_argument('--upload_dataset', action='store_true', help='Upload dataset as W&B artifact table')
    parser.add_argument('--bbox_interval', type=int, default=-1, help='Set bounding-box image logging interval for W&B')
    parser.add_argument('--save_period', type=int, default=-1, help='Log model after every "save_period" epoch')
    parser.add_argument('--artifact_alias', type=str, default="latest", help='version of dataset artifact to be used')
    opt = parser.parse_args()

```
                 from  n    params  module                                  arguments                     
  0                -1  1      5280  models.common.Focus                     [3, 48, 3]                    
  1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]                
  2                -1  1     65280  models.common.C3                        [96, 96, 2]                   
  3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]               
  4                -1  1    629760  models.common.C3                        [192, 192, 6]                 
  5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]              
  6                -1  1   2512896  models.common.C3                        [384, 384, 6]                 
  7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]              
  8                -1  1   1476864  models.common.SPP                       [768, 768, [5, 9, 13]]        
  9                -1  1   4134912  models.common.C3                        [768, 768, 2, False]          
 10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1   1182720  models.common.C3                        [768, 384, 2, False]          
 14                -1  1    148224  models.common.Conv                      [384, 384, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1   1108992  models.common.C3                        [576, 384, 2, False]          
 18                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
 19                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 20           [-1, 2]  1         0  models.common.Concat                    [1]                           
 21                -1  1    278016  models.common.C3                        [288, 192, 2, False]          
 22                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
 23          [-1, 18]  1         0  models.common.Concat                    [1]                           
 24                -1  1    296448  models.common.C3                        [384, 192, 2, False]          
 25                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
 26          [-1, 14]  1         0  models.common.Concat                    [1]                           
 27                -1  1   1108992  models.common.C3                        [576, 384, 2, False]          
 28                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]              
 29          [-1, 10]  1         0  models.common.Concat                    [1]                           
 30                -1  1   4134912  models.common.C3                        [768, 768, 2, False]          
 31  [21, 24, 27, 30]  1     27720  models.yolo.Detect                      [1, [[5, 6, 8, 14, 15, 11], [10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 192, 384, 768]]
C:\Users\master\anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model Summary: 467 layers, 23001000 parameters, 23001000 gradients, 84.7 GFLOPS

Transferred 604/604 items from .\runs\train\exp2\weights\last.pt
Scaled weight_decay = 0.0005
Optimizer groups: 103 .bias, 103 conv.weight, 99 other
train: Scanning '..\CrowdHuman\labels\annotation_train.cache' images and labels... 14096 found, 904 missing, 0 empty, 0 corrupted: 100%|██████████| 15000/15000 [00:00<?, ?it/s]
val: Scanning '..\CrowdHuman\labels\annotation_val.cache' images and labels... 4127 found, 243 missing, 0 empty, 0 corrupted: 100%|██████████| 4370/4370 [00:00<?, ?it/s]
Image sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs\train\exp2
Starting training for 30 epochs...


**results**
```
      0/29     6.02G   0.06714   0.03384         0     0.101       240       640    0.5463    0.5026    0.5012    0.1812    0.0609   0.02677         0
      1/29     5.78G   0.06516   0.03437         0   0.09953       374       640    0.5822    0.5159    0.5388    0.2053   0.05913   0.02615         0
      2/29     5.78G   0.06418   0.03392         0    0.0981       304       640    0.5952    0.5153    0.5389    0.2149   0.05973   0.02677         0
      3/29     5.79G   0.06268   0.03357         0   0.09625       388       640    0.6127     0.548    0.5788    0.2392   0.05721   0.02574         0
      4/29     5.79G   0.06183   0.03326         0    0.0951       303       640    0.6206    0.5676     0.595    0.2511   0.05665    0.0251         0
      5/29     5.79G   0.06152   0.03286         0   0.09438       359       640    0.5434    0.4939    0.4733    0.1952   0.05912   0.03715         0
      6/29     5.79G   0.06104   0.03248         0   0.09352       235       640    0.6707    0.5632    0.6132    0.2643   0.05605   0.02471         0
      7/29     5.79G    0.0606   0.03211         0   0.09271       243       640    0.6476    0.5905     0.622    0.2738   0.05506   0.02455         0
      8/29     5.79G   0.06035    0.0329         0   0.09325       255       640    0.6715    0.5963    0.6376    0.2861    0.0544   0.02583         0
      9/29     5.79G   0.06003   0.03248         0   0.09251       372       640    0.6753    0.6066    0.6441    0.2918    0.0541   0.02434         0
     10/29     5.09G   0.05962   0.03197         0   0.09159       240       640     0.667    0.5976    0.6382    0.2876   0.05409   0.02419         0
     11/29     5.62G   0.05973   0.03235         0   0.09208       374       640    0.6816    0.5933    0.6418    0.2923   0.05356   0.02404         0
     12/29     5.62G   0.05908    0.0321         0   0.09119       304       640       0.7    0.6138    0.6627    0.3092   0.05292   0.02403         0
     13/29     5.62G   0.05898   0.03209         0   0.09107       388       640     0.689    0.6188    0.6642    0.3116   0.05257   0.02369         0
     14/29     5.62G   0.05863   0.03199         0   0.09062       303       640    0.6973    0.6157    0.6645    0.3134   0.05223   0.02362         0
     15/29     5.09G    0.0582   0.03138         0   0.08958       240       640    0.6966    0.6259    0.6683    0.3164   0.05284   0.02428         0
     16/29      5.4G    0.0579   0.03119         0   0.08909       240       640    0.7112    0.6243    0.6773    0.3234   0.05192   0.02364         0
     17/29     5.78G   0.05783   0.03162         0   0.08945       374       640    0.7014      0.63    0.6772    0.3256    0.0516   0.02331         0
     18/29     5.78G   0.05752   0.03138         0   0.08889       304       640    0.7144    0.6286    0.6809    0.3295   0.05124   0.02348         0
     19/29     5.78G   0.05702   0.03135         0   0.08837       388       640    0.7134    0.6382    0.6866    0.3339   0.05099   0.02319         0
     20/29     5.78G   0.05685   0.03113         0   0.08798       303       640     0.722    0.6353    0.6882    0.3372   0.05073   0.02314         0
     21/29     5.78G   0.05647   0.03084         0    0.0873       359       640    0.7237    0.6416    0.6927    0.3421   0.05057   0.02307         0
     22/29     5.78G   0.05632    0.0306         0   0.08692       235       640    0.7295    0.6461     0.697    0.3466   0.05031   0.02304         0
     23/29     5.78G   0.05594   0.03025         0   0.08619       243       640    0.7268    0.6471    0.6959     0.349   0.05011   0.02322         0
     24/29     5.78G    0.0557   0.03083         0   0.08653       255       640    0.7295    0.6505    0.7002    0.3517   0.04985   0.02292         0
     25/29     5.78G   0.05547   0.03053         0   0.08599       372       640    0.7396    0.6521    0.7046    0.3562    0.0497   0.02288         0
     26/29     5.78G   0.05511   0.03015         0   0.08526       256       640     0.743    0.6534    0.7062    0.3584   0.04948   0.02276         0
     27/29     5.78G    0.0549   0.03055         0   0.08545       154       640    0.7345    0.6595    0.7071     0.361   0.04931    0.0226         0
     28/29     5.78G   0.05467   0.03017         0   0.08485       222       640    0.7365    0.6609    0.7087    0.3622   0.04916   0.02261         0
     29/29     5.78G   0.05445   0.03013         0   0.08458       384       640    0.7402    0.6652    0.7117    0.3661     0.049   0.02262         0

**MOT EVAL**
```
...Preprocessing (cleaning) MOT16-05...
.....
Removing 1 boxes from MOT16-13 solution...
..
Removing 873 boxes from MOT16-02 solution...
...........
Removing 0 boxes from MOT16-05 solution...
...
Removing 397 boxes from MOT16-09 solution...
Preprocessing (cleaning) MOT16-10...
.........
Removing 411 boxes from MOT16-10 solution...
......
Removing 1987 boxes from MOT16-04 solution...
evaluation successful
Evaluation Finished
Your Results
         MOTA  MOTP  IDF1  IDP   IDR   Rcll  Prcn  TP    FP   FN    MTR   PTR   MLR   MT PT  ML  FAR  FM   FMR   IDSW IDSWR
MOT16-02 29.80 76.67 37.14 60.10 26.88 37.64 84.16  6712 1263 11121 14.81 38.89 40.74  8  21  22 2.10  278  7.39 135   3.6 
MOT16-04 56.76 75.71 60.61 77.88 49.61 60.35 94.75 28703 1592 18854 20.48 38.55 25.30 17  32  21 1.52  655 10.85 120   2.0 
MOT16-05 32.06 77.97 41.14 76.45 28.15 35.22 95.66  2401  109  4417  8.80 53.60 37.60 11  67  47 0.13  153  4.34 106   3.0 
MOT16-09 54.67 81.87 54.91 62.13 49.19 67.40 85.13  3543  619  1714 28.00 60.00 12.00  7  15   3 1.18  124  1.84  50   0.7 
MOT16-10 49.31 74.54 52.13 62.97 44.47 60.54 85.71  7457 1243  4861 24.07 64.81 11.11 13  35   6 1.90  515  8.51 140   2.3 
MOT16-11 62.52 83.05 63.58 73.84 55.82 69.29 91.67  6357  578  2817 33.33 42.03 24.64 23  29  17 0.64  126  1.82  43   0.6 
MOT16-13 26.04 68.62 40.57 56.56 31.63 41.76 74.66  4781 1623  6669 11.21 55.14 33.64 12  59  36 2.16  400  9.58 176   4.2 
OVERALL  47.24 76.34 53.12 70.34 42.67 54.30 89.51 59954 7027 50453 17.60 49.90 29.40 91 258 152 1.32 2251 41.45 770  14.2 

```
Among them, the MOTA value of MOT16-05 is much lower than your result.Looking forward to your reply, thank you.

**Comment by mikel-brostrom** [comment]
I didn't train Yolov5 on the `crowd-human dataset` myself. I used [these weights](https://github.com/deepakcrk/yolov5-crowdhuman), so I suggest you to contact https://github.com/deepakcrk

**Comment by Edurccl** [comment]
Ok,thank you!

**Comment by fengshuaibo** [comment]
> Hello, I want to know what tricks you have when training your `crowdhuman_yolov5m.pt `weights. The yolo weights I trained on the `crowdhuman dataset` tested on the `MOT16` dataset were significantly lower than your results. The following are my parameter settings and results.
> 
> **parameters**
> 
> ```
> parser.add_argument('--weights', type=str, default='weights/yolov5m.pt', help='initial weights path')
> 
> # Add a small target detection layer on the basis of yolov5m.yaml
> parser.add_argument('--cfg', type=str, default='models/yolov5m_add_detect.yaml', help='model.yaml path')      
> 
> parser.add_argument('--data', type=str, default='data/CrowdHuman_self.yaml', help='data.yaml path')
> parser.add_argument('--hyp', type=str, default='data/hyp.scratch.yaml', help='hyperparameters path')
> parser.add_argument('--epochs', type=int, default=30)
> parser.add_argument('--batch-size', type=int, default=4, help='total batch size for all GPUs')
> parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='[train, test] image sizes')
> parser.add_argument('--rect', action='store_true', help='rectangular training')
> parser.add_argument('--resume', nargs='?', const=True, default=True, help='resume most recent training')
> parser.add_argument('--nosave', action='store_true', help='only save final checkpoint')
> parser.add_argument('--notest', action='store_true', help='only test final epoch')
> parser.add_argument('--noautoanchor', action='store_true', help='disable autoanchor check')
> parser.add_argument('--evolve', action='store_true', help='evolve hyperparameters')
> parser.add_argument('--bucket', type=str, default='', help='gsutil bucket')
> parser.add_argument('--cache-images', action='store_true', help='cache images for faster training')
> parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')
> parser.add_argument('--device', default='', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
> parser.add_argument('--multi-scale', action='store_true', help='vary img-size +/- 50%%')
> parser.add_argument('--single-cls', action='store_true', help='train multi-class data as single-class')
> parser.add_argument('--adam', action='store_true', help='use torch.optim.Adam() optimizer')
> parser.add_argument('--sync-bn', action='store_true', help='use SyncBatchNorm, only available in DDP mode')
> parser.add_argument('--local_rank', type=int, default=-1, help='DDP parameter, do not modify')
> parser.add_argument('--workers', type=int, default=0, help='maximum number of dataloader workers')
> parser.add_argument('--project', default='runs/train', help='save to project/name')
> parser.add_argument('--entity', default=None, help='W&B entity')
> parser.add_argument('--name', default='exp', help='save to project/name')
> parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
> parser.add_argument('--quad', action='store_true', help='quad dataloader')
> parser.add_argument('--linear-lr', action='store_true', help='linear LR')
> parser.add_argument('--label-smoothing', type=float, default=0.1, help='Label smoothing epsilon')
> parser.add_argument('--upload_dataset', action='store_true', help='Upload dataset as W&B artifact table')
> parser.add_argument('--bbox_interval', type=int, default=-1, help='Set bounding-box image logging interval for W&B')
> parser.add_argument('--save_period', type=int, default=-1, help='Log model after every "save_period" epoch')
> parser.add_argument('--artifact_alias', type=str, default="latest", help='version of dataset artifact to be used')
> opt = parser.parse_args()
> ```
> 
> ```
>                  from  n    params  module                                  arguments                     
>   0                -1  1      5280  models.common.Focus                     [3, 48, 3]                    
>   1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]                
>   2                -1  1     65280  models.common.C3                        [96, 96, 2]                   
>   3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]               
>   4                -1  1    629760  models.common.C3                        [192, 192, 6]                 
>   5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]              
>   6                -1  1   2512896  models.common.C3                        [384, 384, 6]                 
>   7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]              
>   8                -1  1   1476864  models.common.SPP                       [768, 768, [5, 9, 13]]        
>   9                -1  1   4134912  models.common.C3                        [768, 768, 2, False]          
>  10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]              
>  11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  12           [-1, 6]  1         0  models.common.Concat                    [1]                           
>  13                -1  1   1182720  models.common.C3                        [768, 384, 2, False]          
>  14                -1  1    148224  models.common.Conv                      [384, 384, 1, 1]              
>  15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  16           [-1, 4]  1         0  models.common.Concat                    [1]                           
>  17                -1  1   1108992  models.common.C3                        [576, 384, 2, False]          
>  18                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
>  19                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
>  20           [-1, 2]  1         0  models.common.Concat                    [1]                           
>  21                -1  1    278016  models.common.C3                        [288, 192, 2, False]          
>  22                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
>  23          [-1, 18]  1         0  models.common.Concat                    [1]                           
>  24                -1  1    296448  models.common.C3                        [384, 192, 2, False]          
>  25                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
>  26          [-1, 14]  1         0  models.common.Concat                    [1]                           
>  27                -1  1   1108992  models.common.C3                        [576, 384, 2, False]          
>  28                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]              
>  29          [-1, 10]  1         0  models.common.Concat                    [1]                           
>  30                -1  1   4134912  models.common.C3                        [768, 768, 2, False]          
>  31  [21, 24, 27, 30]  1     27720  models.yolo.Detect                      [1, [[5, 6, 8, 14, 15, 11], [10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 192, 384, 768]]
> C:\Users\master\anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
>   return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
> Model Summary: 467 layers, 23001000 parameters, 23001000 gradients, 84.7 GFLOPS
> 
> Transferred 604/604 items from .\runs\train\exp2\weights\last.pt
> Scaled weight_decay = 0.0005
> Optimizer groups: 103 .bias, 103 conv.weight, 99 other
> train: Scanning '..\CrowdHuman\labels\annotation_train.cache' images and labels... 14096 found, 904 missing, 0 empty, 0 corrupted: 100%|██████████| 15000/15000 [00:00<?, ?it/s]
> val: Scanning '..\CrowdHuman\labels\annotation_val.cache' images and labels... 4127 found, 243 missing, 0 empty, 0 corrupted: 100%|██████████| 4370/4370 [00:00<?, ?it/s]
> Image sizes 640 train, 640 test
> Using 0 dataloader workers
> Logging results to runs\train\exp2
> Starting training for 30 epochs...
> 
> 
> **results**
> ```
> 
> ```
>   0/29     6.02G   0.06714   0.03384         0     0.101       240       640    0.5463    0.5026    0.5012    0.1812    0.0609   0.02677         0
>   1/29     5.78G   0.06516   0.03437         0   0.09953       374       640    0.5822    0.5159    0.5388    0.2053   0.05913   0.02615         0
>   2/29     5.78G   0.06418   0.03392         0    0.0981       304       640    0.5952    0.5153    0.5389    0.2149   0.05973   0.02677         0
>   3/29     5.79G   0.06268   0.03357         0   0.09625       388       640    0.6127     0.548    0.5788    0.2392   0.05721   0.02574         0
>   4/29     5.79G   0.06183   0.03326         0    0.0951       303       640    0.6206    0.5676     0.595    0.2511   0.05665    0.0251         0
>   5/29     5.79G   0.06152   0.03286         0   0.09438       359       640    0.5434    0.4939    0.4733    0.1952   0.05912   0.03715         0
>   6/29     5.79G   0.06104   0.03248         0   0.09352       235       640    0.6707    0.5632    0.6132    0.2643   0.05605   0.02471         0
>   7/29     5.79G    0.0606   0.03211         0   0.09271       243       640    0.6476    0.5905     0.622    0.2738   0.05506   0.02455         0
>   8/29     5.79G   0.06035    0.0329         0   0.09325       255       640    0.6715    0.5963    0.6376    0.2861    0.0544   0.02583         0
>   9/29     5.79G   0.06003   0.03248         0   0.09251       372       640    0.6753    0.6066    0.6441    0.2918    0.0541   0.02434         0
>  10/29     5.09G   0.05962   0.03197         0   0.09159       240       640     0.667    0.5976    0.6382    0.2876   0.05409   0.02419         0
>  11/29     5.62G   0.05973   0.03235         0   0.09208       374       640    0.6816    0.5933    0.6418    0.2923   0.05356   0.02404         0
>  12/29     5.62G   0.05908    0.0321         0   0.09119       304       640       0.7    0.6138    0.6627    0.3092   0.05292   0.02403         0
>  13/29     5.62G   0.05898   0.03209         0   0.09107       388       640     0.689    0.6188    0.6642    0.3116   0.05257   0.02369         0
>  14/29     5.62G   0.05863   0.03199         0   0.09062       303       640    0.6973    0.6157    0.6645    0.3134   0.05223   0.02362         0
>  15/29     5.09G    0.0582   0.03138         0   0.08958       240       640    0.6966    0.6259    0.6683    0.3164   0.05284   0.02428         0
>  16/29      5.4G    0.0579   0.03119         0   0.08909       240       640    0.7112    0.6243    0.6773    0.3234   0.05192   0.02364         0
>  17/29     5.78G   0.05783   0.03162         0   0.08945       374       640    0.7014      0.63    0.6772    0.3256    0.0516   0.02331         0
>  18/29     5.78G   0.05752   0.03138         0   0.08889       304       640    0.7144    0.6286    0.6809    0.3295   0.05124   0.02348         0
>  19/29     5.78G   0.05702   0.03135         0   0.08837       388       640    0.7134    0.6382    0.6866    0.3339   0.05099   0.02319         0
>  20/29     5.78G   0.05685   0.03113         0   0.08798       303       640     0.722    0.6353    0.6882    0.3372   0.05073   0.02314         0
>  21/29     5.78G   0.05647   0.03084         0    0.0873       359       640    0.7237    0.6416    0.6927    0.3421   0.05057   0.02307         0
>  22/29     5.78G   0.05632    0.0306         0   0.08692       235       640    0.7295    0.6461     0.697    0.3466   0.05031   0.02304         0
>  23/29     5.78G   0.05594   0.03025         0   0.08619       243       640    0.7268    0.6471    0.6959     0.349   0.05011   0.02322         0
>  24/29     5.78G    0.0557   0.03083         0   0.08653       255       640    0.7295    0.6505    0.7002    0.3517   0.04985   0.02292         0
>  25/29     5.78G   0.05547   0.03053         0   0.08599       372       640    0.7396    0.6521    0.7046    0.3562    0.0497   0.02288         0
>  26/29     5.78G   0.05511   0.03015         0   0.08526       256       640     0.743    0.6534    0.7062    0.3584   0.04948   0.02276         0
>  27/29     5.78G    0.0549   0.03055         0   0.08545       154       640    0.7345    0.6595    0.7071     0.361   0.04931    0.0226         0
>  28/29     5.78G   0.05467   0.03017         0   0.08485       222       640    0.7365    0.6609    0.7087    0.3622   0.04916   0.02261         0
>  29/29     5.78G   0.05445   0.03013         0   0.08458       384       640    0.7402    0.6652    0.7117    0.3661     0.049   0.02262         0
> ```
> 
> **MOT EVAL**
> 
> ```
> ...Preprocessing (cleaning) MOT16-05...
> .....
> Removing 1 boxes from MOT16-13 solution...
> ..
> Removing 873 boxes from MOT16-02 solution...
> ...........
> Removing 0 boxes from MOT16-05 solution...
> ...
> Removing 397 boxes from MOT16-09 solution...
> Preprocessing (cleaning) MOT16-10...
> .........
> Removing 411 boxes from MOT16-10 solution...
> ......
> Removing 1987 boxes from MOT16-04 solution...
> evaluation successful
> Evaluation Finished
> Your Results
>          MOTA  MOTP  IDF1  IDP   IDR   Rcll  Prcn  TP    FP   FN    MTR   PTR   MLR   MT PT  ML  FAR  FM   FMR   IDSW IDSWR
> MOT16-02 29.80 76.67 37.14 60.10 26.88 37.64 84.16  6712 1263 11121 14.81 38.89 40.74  8  21  22 2.10  278  7.39 135   3.6 
> MOT16-04 56.76 75.71 60.61 77.88 49.61 60.35 94.75 28703 1592 18854 20.48 38.55 25.30 17  32  21 1.52  655 10.85 120   2.0 
> MOT16-05 32.06 77.97 41.14 76.45 28.15 35.22 95.66  2401  109  4417  8.80 53.60 37.60 11  67  47 0.13  153  4.34 106   3.0 
> MOT16-09 54.67 81.87 54.91 62.13 49.19 67.40 85.13  3543  619  1714 28.00 60.00 12.00  7  15   3 1.18  124  1.84  50   0.7 
> MOT16-10 49.31 74.54 52.13 62.97 44.47 60.54 85.71  7457 1243  4861 24.07 64.81 11.11 13  35   6 1.90  515  8.51 140   2.3 
> MOT16-11 62.52 83.05 63.58 73.84 55.82 69.29 91.67  6357  578  2817 33.33 42.03 24.64 23  29  17 0.64  126  1.82  43   0.6 
> MOT16-13 26.04 68.62 40.57 56.56 31.63 41.76 74.66  4781 1623  6669 11.21 55.14 33.64 12  59  36 2.16  400  9.58 176   4.2 
> OVERALL  47.24 76.34 53.12 70.34 42.67 54.30 89.51 59954 7027 50453 17.60 49.90 29.40 91 258 152 1.32 2251 41.45 770  14.2 
> ```
> 
> Among them, the MOTA value of MOT16-05 is much lower than your result.Looking forward to your reply, thank you.

Hello, I would like to ask you a question. When you retrained the CrowndHuman data set, did you choose Vbox or Fbox? When I used fbox, some of the converted data could not be used
