### ISSUE TITLE
Reproducing fps on mot dataset

### ISSUE THREAD

**Issue by fabiozappo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#153]
Hi, thank you for sharing your code and evaluation script. I have done some changes in reid network and i would like to see how the tracking speed changes. 
In your comparinson table I see your tracker run at less than 21 fps, how can i reproduce that result on my gtx 1050 in order to have a fair comparison?
How did you get that  "< 21 fps" ?

**Comment by mikel-brostrom** [comment]
> How did you get that "< 21 fps" ?

I took the average of the last 100 single image inferences. 

> how can i reproduce that result on my gtx 1050 in order to have a fair comparison?

There is no way of making a fair comparison. The hardware is different on so many levels that there is no possible fair comparison. The clock speed is different, the memory size...
