### ISSUE TITLE
HOW to get the table about different trakers on the metrics

### ISSUE THREAD

**Issue by xuaixi** [mikel-brostrom/Yolov5_DeepSort_Pytorch#154]
![image](https://user-images.githubusercontent.com/88577502/129564259-8e4212ff-d232-43b7-b6d8-ef0b22ec33e6.png)

**Comment by xuaixi** [comment]
could you tell me how to get the result? Thank you

**Comment by mikel-brostrom** [comment]
The table is taken from the FairMOT paper I just added the MOT16 results obtained with this repo
