### ISSUE TITLE
Track only for limited classes

### ISSUE THREAD

**Issue by xiaofeng-c** [mikel-brostrom/Yolov5_DeepSort_Pytorch#155]
I have a model for 9 classes,but i only need to track for two classes,how can i realize it?Thank you.

**Comment by xiaofeng-c** [comment]
I know how to address it,i find the **for *xyxy, conf, cls in det:**,so i can try to limit the classes use the parameter of cls.

**Comment by mikel-brostrom** [comment]
The best way to do this is to use the classes argument in `track.py`. Let's say you have 20 classes, you can limit the predicted output to class 16 and 17 by adding the following:

```
--classes 16 17
```

**Comment by xiaofeng-c** [comment]
Thank you,it really works.
