### ISSUE TITLE
Confused about order of output 

### ISSUE THREAD

**Issue by tuanpham96** [mikel-brostrom/Yolov5_DeepSort_Pytorch#156]
Hi, I noticed in `track.py` the following lines:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/track.py#L153-L160

But based on:
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/track.py#L136

which is from 
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/461c80ce7aa5a7901f722d072a955ec4909dcfcc/deep_sort_pytorch/deep_sort/deep_sort.py#L51

which I am assuming lays out like this:

```
(x1,y1) ----------------
  |                     |
  |                     |
  |                     |
   ----------------- (x2,y2)
```

shouldn't it be more like 

```
 bbox_left = output[0] 
 bbox_top = output[1] 
 bbox_w = output[2] - output[0] 
 bbox_h = output[3] - output[1] 
```

so the written format would be more like this:
```
  f.write(('%g ' * 10 + '\n') % (frame_idx, id, bbox_left, bbox_top, bbox_w, bbox_h, -1, -1, -1, -1))  # label format 
```

Thanks

**Comment by mikel-brostrom** [comment]
Yes, that is a typo. You are right. I updated it as you suggested. Thx!
