### ISSUE TITLE
bboxes are large for new comers

### ISSUE THREAD

**Issue by fwzdev1** [mikel-brostrom/Yolov5_DeepSort_Pytorch#158]
First, thank you for your code.

This is actually the same question as #131 
It also happens to me, and I tried it on [Sort.](https://github.com/abewley/sort) But it worked fine with Sort even the core part of Kalman stuff is basically the same.

Could you help me with that?

**Comment by mikel-brostrom** [comment]
The last argument under this line of code:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/2bae6e64dad8430351bbceb5e08ed06aa703dbde/track.py#L128

indicates whether to print the kf predicted bboxes or the yolo predicted bboxes. Try that out and let me know if it makes a differecne

**Comment by mikel-brostrom** [comment]
Fixed based on https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/166.
Update your code. Let me know if the results you now get are better!
