### ISSUE TITLE
what is the difference between --conf-thres and --iou-thres

### ISSUE THREAD

**Issue by besbesmany** [mikel-brostrom/Yolov5_DeepSort_Pytorch#161]
in track.py 
what is the difference between them

**Comment by sonyta29** [comment]
If I'm right ... 
When processing with NMS ( non maximum supression) you two parameters in consideration which are the iou thresh and conf thresh .. I'm talking in the context of yolo and not deep sort. 
When yolo make all the predictions, we find in the list of BB the true positives (TP) and the false positive (FP) 
TP: object we sould detect and we detected it
FP: object we should not detect and we detect it 
So in NMS yolo is trying to delete the FP 
The TP and FP BBox are overlapped, first of all yolo choose the BBox with the confidance score > conf_thresh after that it computes the iou distance between this BBox and the rest of BBoxes 
if this distnace is greater than iou_thresh than it delete the BBox ( wich is in this case FP) 
You can adjust these parameters to see the difference 


I hope this explanaition was useful

**Comment by besbesmany** [comment]
I coouldn't understand clearly
can you give me example
also what is the optimum value for both of them
