### ISSUE TITLE
how to get the frame number

### ISSUE THREAD

**Issue by xuaixi** [mikel-brostrom/Yolov5_DeepSort_Pytorch#163]
hello, can you  tell me about how can i get the frame number when i track a video ,thank you
like this:
![image](https://user-images.githubusercontent.com/88577502/131271230-af108008-60c6-480f-b9d8-920c5752bc22.png)

**Comment by sonyta29** [comment]
The frame number and the frame_id are the same... Try to write the frame_id on the output video and you'll see the result
