### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Net:

### ISSUE THREAD

**Issue by huahuahauhau** [mikel-brostrom/Yolov5_DeepSort_Pytorch#165]
This error occurred after I ran track.py
RuntimeError: Error(s) in loading state_dict for Net:
        size mismatch for classifier.4.weight: copying a param with shape torch.Size([751, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]).
        size mismatch for classifier.4.bias: copying a param with shape torch.Size([751]) from checkpoint, the shape in current model is torch.Size([1]).
Can someone tell me how to solve it. thank you

**Comment by huahuahauhau** [comment]
> 这个错误发生在我运行 track.py
> RuntimeError: Error(s) in loading state_dict for Net:
> size mismatch for classifier.4.weight: copying a param with shape torch.Size([751, 256]) from checkpoint, the shape在当前模型中是torch.Size([1, 256])。
> 分类器.4.bias 的大小不匹配：从检查点复制形状为 torch.Size([751]) 的参数，当前模型中的形状为 torch.Size([1])。
> 有人可以告诉我如何解决它。谢谢你

Thank you.
When I downloaded and replaced the new version of yolov5 model, I solved this problem.

**Comment by MaxWhite14** [comment]
> > 这个错误发生在我运行 track.py
> > RuntimeError: Error(s) in loading state_dict for Net:
> > size mismatch for classifier.4.weight: copying a param with shape torch.Size([751, 256]) from checkpoint, the shape在当前模型中是torch.Size([1, 256])。
> > 分类器.4.bias 的大小不匹配：从检查点复制形状为 torch.Size([751]) 的参数，当前模型中的形状为 torch.Size([1])。
> > 有人可以告诉我如何解决它。谢谢你
> 
> Thank you.
> When I downloaded and replaced the new version of yolov5 model, I solved this problem.

Hello, i'v got the same issue, can you answer in details? What model did you replaced? By which model?

**Comment by huahuahauhau** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月7日(星期二) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_DeepSort_Pytorch] RuntimeError: Error(s) in loading state_dict for Net: (#165)

**Comment by huahuahauhau** [comment]
You need to have a yolov5 folder in the root directory, where you need to put all the files extracted by yolov5 (on GitHub). I hope it will help you. If you have any questions, you can continue to explore------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月7日(星期二) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_DeepSort_Pytorch] RuntimeError: Error(s) in loading state_dict for Net: (#165)

**Comment by mikel-brostrom** [comment]
I suggest you to start from a clean slate

1. `git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`
2. `python3 track.py --source 0` (webcam tracking)

It is as simple as that. The weights get downloaded automatically
