### ISSUE TITLE
When a new object appears in the field of view，the box predicted is much larger.Is the problem in yolo or feature extractor

### ISSUE THREAD

**Issue by tdf1995** [mikel-brostrom/Yolov5_DeepSort_Pytorch#166]
![image](https://user-images.githubusercontent.com/39071957/131487789-5a97711f-25b7-4117-9693-0ab74b3012de.png)
![image](https://user-images.githubusercontent.com/39071957/131488008-e6454839-8999-44e2-95fb-796d77349791.png)
![image](https://user-images.githubusercontent.com/39071957/131488058-57c23c61-6e42-4e67-8a7d-c4f4358dded2.png)
![image](https://user-images.githubusercontent.com/39071957/131488104-13bac1ae-dd79-4f67-bc99-8d0b7482e1c5.png)
the white box is predicted by yolo,color box is predicted by Kalman filter

**Comment by mikel-brostrom** [comment]
This is a known issue in this repo. The ploted bboxes needs to be changed to Yolo bboxes. What gets plotted right now are the predicted KF bboxes

**Comment by 2033329616** [comment]
[solutions.md](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/files/7142677/solutions.md)

**Comment by mikel-brostrom** [comment]
Good catch! I appreciate you took the time to fix this @2033329616 I updated the `KalmanFilter` code accordingly to the previous response
