### ISSUE TITLE
ImportError: cannot import name 'time_synchronized' from 'yolov5.utils.torch_utils

### ISSUE THREAD

**Issue by Baowenqi888** [mikel-brostrom/Yolov5_DeepSort_Pytorch#167]
python ./track.py
Traceback (most recent call last):
  File "./track.py", line 8, in <module>
    from yolov5.utils.torch_utils import select_device, time_synchronized
ImportError: cannot import name 'time_synchronized' from 'yolov5.utils.torch_utils' (/Users/yangfan/Downloads/Yolov5_DeepSort_Pytorch-master/yolov5/utils/torch_utils.py)

Mac，intel，MacBook Pro (Retina, 15-inch, Mid 2015)，python3.9，
How to solve this problem，thanks

**Comment by ysfmani** [comment]
change it tot time_sync   not  time_synchronized

**Comment by ysfmani** [comment]
from yolov5.utils.torch_utils import select_device, time_sync

**Comment by HEROhaoyu** [comment]
Thank you so much!

**Comment by mikel-brostrom** [comment]
The `yolov5` submodule has been updated as well as `track.py` . This shouldn't b e an issue anymore. Let me know if it works for you!
