### ISSUE TITLE
'RuntimeError: Sizes of tensors must match ...' when doing 1280x720 video

### ISSUE THREAD

**Issue by coldfir3** [mikel-brostrom/Yolov5_DeepSort_Pytorch#168]
When I run the code `!python track.py --yolo_weights $path --img 1280 --source vid.mp4 --save-vid` I get the folowing error: RuntimeError: Sizes of tensors must match except in dimension 1. Got 24 and 23 in dimension 2 (The offending index is 1)

However if I run the exact same video using `!python track.py --yolo_weights $path --img 1024 --source vid.mp4 --save-vid` The model works just fine. Any idea what I might be doing wrong?

Tnx in advance

**Comment by mikel-brostrom** [comment]
Fixed according to https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/174#issuecomment-919199240
