### ISSUE TITLE
ImportError: cannot import name 'plot_one_box' from 'yolov5.utils.plots'

### ISSUE THREAD

**Issue by MaxWhite14** [mikel-brostrom/Yolov5_DeepSort_Pytorch#169]
Hello! Just installed your repo for tracking on yolov5 models, but got this error, when trying to run track.py
`ImportError: cannot import name 'plot_one_box' from 'yolov5.utils.plots'`

Is there any updates in names? Because a lot of imports doesnt work as it should be

**Comment by mikel-brostrom** [comment]
Deployment status is passing. That means that if you set up everything correctly the repo should work in its current state. Check that you fulfill all the environment requirements, python version...

**Comment by MaxWhite14** [comment]
> Deployment status is passing. That means that if you set up everything correctly the repo should work in its current state. Check that you fulfill all the environment requirements, python version...

Yea, the problem was in versioning of YOLOv5 repo, thnx for the answer)
