### ISSUE TITLE
how to count number of objects

### ISSUE THREAD

**Issue by besbesmany** [mikel-brostrom/Yolov5_DeepSort_Pytorch#170]
I want to  count number of objects in video

**Comment by mikel-brostrom** [comment]
You need to implement a counter yourself, there is no counting functionality in this repo

**Comment by besbesmany** [comment]
how to do this please

**Comment by mikel-brostrom** [comment]
You can start looking into some there repo that has this functionality and try to move it into this one. PRs are accepted!
