### ISSUE TITLE
Unused nms_max_overlap variable inside DeepSort Class

### ISSUE THREAD

**Issue by sahamrit** [mikel-brostrom/Yolov5_DeepSort_Pytorch#171]
The nms_max_overlap variable passed in the init of Deep Sort class seems to be unused. In the code I only find a non max suppression applied once in track.py on the initial detection predictions. However I don't find any NMS applied inside DeepSort class.

**Comment by mikel-brostrom** [comment]
You are totally right

`self.nms_max_overlap`

is never used and should be deleted

**Comment by mikel-brostrom** [comment]
`self.nms_max_overlap` now deleted
