### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by whut-dg** [mikel-brostrom/Yolov5_DeepSort_Pytorch#172]
想问问FPS指标如何求呀，我评估函数跑出来的结果没有FPS

**Comment by mikel-brostrom** [comment]
You could accumulate https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/ffbf5f7d6440a61260e16429df7ec759c4fb0cc0/track.py#L196

and then divide it by the total amount of frames in the video
