### ISSUE TITLE
Custom Deep Sort trainig 

### ISSUE THREAD

**Issue by lorenzoloretucci** [mikel-brostrom/Yolov5_DeepSort_Pytorch#173]
Hi! I have 2 questions:
 
1. Is there any way to train deep sort on custom data? 
2.  Does Deep sort weights that end wit .pb are accepted on this repo?

Thanks <3

**Comment by mikel-brostrom** [comment]
Hi!

1. https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/79
2. No, deep sort only accepts weights in `.pt` format

**Comment by lorenzoloretucci** [comment]
Thanks a lot :)
