### ISSUE TITLE
 cannot import name 'Annotator' from 'yolov5.utils.plots'

### ISSUE THREAD

**Issue by centurions** [mikel-brostrom/Yolov5_DeepSort_Pytorch#176]

**Comment by Leonard-Bernstein** [comment]
!python3 track.py --source test.mp4 --yolo_weights yolov5/runs/train/exp41/weights/best.pt --classes 0

Traceback (most recent call last):
  File "track.py", line 9, in <module>
    from yolov5.utils.plots import Annotator, colors
ImportError: cannot import name 'Annotator' from 'yolov5.utils.plots' (/fusaka/Yolov5_DeepSort_Pytorch/yolov5/utils/plots.py)

How can I solve this problem?

**Comment by mikel-brostrom** [comment]
Instead of:

`https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

run:

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

as specified here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch#before-you-run-the-tracker

**Comment by Leonard-Bernstein** [comment]
I got it!!
Thank you very much!!
