### ISSUE TITLE
[Feature Request] Ensembling

### ISSUE THREAD

**Issue by opassos** [mikel-brostrom/Yolov5_DeepSort_Pytorch#177]
Is there any way to do ensembling using multiple YoloV5 models?

**Comment by mikel-brostrom** [comment]
I just made it possible to ensemble multiple yolov5 models. Activate it by:

`python3 track.py --source 0 --yolo_weights yolov5/weights/yolov5s.pt yolov5/weights/yolov5m.pt`

you should see the following before the tracker starts:

`Ensemble created with ['yolov5/weights/yolov5s.pt', 'yolov5/weights/yolov5m.pt']`

**Comment by opassos** [comment]
This is huge! thank you so much for the effort! much appreciated!
