### ISSUE TITLE
Strange resolution when doing inference

### ISSUE THREAD

**Issue by opassos** [mikel-brostrom/Yolov5_DeepSort_Pytorch#178]
When I do inference on a video of resolution 1280 x 720 using the call `--img 1280` I get prints saying the frames are of shape (768 x 1280). Apparently, the predictions are correct but I am not 100% sure. Is this working as intended? Thanks

**Comment by mikel-brostrom** [comment]
Do you get the same shape if you run `detect.py` in the original Yolov5 repo? 

In that case, this is more of a Yolov5 issue which I am not responsible for. I suggest you to post this issue under the original Yolov5 repo issues

**Comment by opassos** [comment]
This was indeed a Yolov5 thing and nothing is wrong after all. Thanks again
