### ISSUE TITLE
Can CSI cameras be used directly?

### ISSUE THREAD

**Issue by yyyhainan** [mikel-brostrom/Yolov5_DeepSort_Pytorch#179]
If I want to use the CSI camera, what value should --source assign

**Comment by yyyhainan** [comment]
If I want to use the CSI camera, what value should --source assign

**Comment by mikel-brostrom** [comment]
List the video devices picked up by the kernel. By, for example:

`ls -ltrh /dev/video*`

find out which among them you want to feed to the tracker. Then
what is important is to keep in mind the number associated to the source. So, if this is
`/dev/video3` you should run:

`python3 track.py --source 3`

**Comment by yyyhainan** [comment]
I've run `ls -ltrh /dev/video*` and the result was `/dev/video0`

then I run `python track.py --source 0`
It showed that 
```
[WARN:0]global /tmp/pip-req-build-hwenbn4e/opencv/modules/videoio/src/cap_v4l.cpp(890)open VIDEOIO(V4L2:/dev/video0):can't open camera by index
1/1:0...Traceback(most recent call last):
  File"track.py", line 216, in <module>
    detect(args)
  File"track.py", line 68, in detect
    dataset = LOadStreams(source, img_size = imgsz, stride = stride)
  File "/yolov5/untils/datasets.py", line 304, in __init__
    assert cap.isOpened(), f'Failed to open {s}'
AssertionError: Failed to open 0
```
Could you tell me how to solve it?
I'm using a CSI onboard camera from Jetson NX.
Thank you so much!

**Comment by yyyhainan** [comment]
![source](https://user-images.githubusercontent.com/73106210/135378838-1e9c32e9-566c-4fc0-ba2f-d61fbdd52d0d.png)

**Comment by mikel-brostrom** [comment]
I see that you can run it the first time but the second time you get the error. This is not something that I could replicate.

You can check which camera source is available by:

```
ffplay /dev/video1
ffplay /dev/video2
...
```

If not available, you may want to disable and enable the camera by:

```
sudo modprobe -r uvcvideo
sudo modprobe uvcvideo
```

**Comment by yinqiyu** [comment]
The yolo doesn't seem to support direct calls to the csi camera.

**Comment by bwithai** [comment]
I solve this problem to edit webcam source by adding port 1, 2, 3 if external USB camera attached with these ports. 

![track py at 43](https://user-images.githubusercontent.com/76056239/170105205-65d82523-15a6-48b2-b6ef-c08b3f124986.png)
