### ISSUE TITLE
How to train reid model of other object such as airplane?

### ISSUE THREAD

**Issue by Maeve-D** [mikel-brostrom/Yolov5_DeepSort_Pytorch#18]
I only find reid dataset of person and cars, can you give me some tips on how to make custom reid dataset and method to train this reid model？

**Comment by mikel-brostrom** [comment]
I would recommend you to have a look at the annotation tool mentioned in #6

**Comment by mikel-brostrom** [comment]
I have never created a REID dataset myself but this [link](https://github.com/openvinotoolkit/cvat) may help. It looks like it contains a REID annotation tool. Let me know if you try it out!
