### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by Zamanov84** [mikel-brostrom/Yolov5_DeepSort_Pytorch#180]
I am running in Google Colab and see no difference in the implementation time when I use the default device and when I set it to gpu. 

How should I set the gpu to be used? 

Is it --device gpu or something else? 

Thanks!

**Comment by mikel-brostrom** [comment]
Go to 

Edit --> Notebook Setting
Under hardware accelerator choose GPU

Notice that you will not always be granted a GPU to run on. This depends on availability:
https://research.google.com/colaboratory/faq.html#resource-limits
