### ISSUE TITLE
very low fps

### ISSUE THREAD

**Issue by Snitte** [mikel-brostrom/Yolov5_DeepSort_Pytorch#182]
When running detect.py on a video with a resolution of 1920x1200 i can only achieve 3.07 fps. This is running on gpu with a 2080ti

-Am i doing something wrong? How can i get more fps without running lower resolution? A better gpu is the obvious awnser however i think a 2080 should be able to run faster than 3 fps

**Comment by mikel-brostrom** [comment]
> When running detect.py on a video

You mean `track.py`?

There is not much more you can do than choosing a smaller Yolov5 model if you haven't done that
