### ISSUE TITLE
face detection and tracking

### ISSUE THREAD

**Issue by Lemiron24** [mikel-brostrom/Yolov5_DeepSort_Pytorch#184]
Hi, Boss,
    I want to know whether this project can do face detection and tracking , if not how should I change the project?

appreciate your response, thx!

**Comment by mikel-brostrom** [comment]
For this you need a Yolov5 model trained on faces. I recommend you to get [these weights](https://drive.google.com/file/d/1gglIwqxaH2iTvy6lZlXuAcMpd_U0GCUb/view?usp=sharing) for this purpose. Then you can run:

```bash
python3 track.py --source 0 --yolo_weights crowdhuman_yolov5m.pt --classes 1  # tracks faces
```
