### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by sekisek** [mikel-brostrom/Yolov5_DeepSort_Pytorch#185]
Hi,
Can u point me to how can I decide if an object is moving or standing still?

thanks

**Comment by mikel-brostrom** [comment]
There is no such functionality in this repo. Feel free to leave a PR

**Comment by PiDGMT** [comment]
If the Bbox coordinates of an object haven't changed outside a specific errror margin for an x amount of time/frames, count it as 'not moving', otherwise, count it as 'moving'
