### ISSUE TITLE
Multi camera/videos on same area

### ISSUE THREAD

**Issue by lorenzoloretucci** [mikel-brostrom/Yolov5_DeepSort_Pytorch#186]
Hi! 

I would like to know if deepsort is capable of tracking one or more people across multiple camera (or video) that share same area like EPFL case (https://www.epfl.ch/labs/cvlab/data/data-pom-index-php/). So one person in cam1 has the same id in cam2.  

If It is able, what are the advice you give me in order to modify the source code? 

Thanks

**Comment by mikel-brostrom** [comment]
There is no such functionality in this repo. Check:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/103

Feel free to submit a PR.

**Comment by jyothirrose** [comment]
Any solution for this?

**Comment by mikel-brostrom** [comment]
You have it in master @jyothirrose.
Write the paths to the videos in a txt file and then pass it as source.

`python track.py --source streams.txt`
