### ISSUE TITLE
New features about output

### ISSUE THREAD

**Issue by jayer95** [mikel-brostrom/Yolov5_DeepSort_Pytorch#187]
Hi, I appreciate your project.

Can you release a new version that contains the following functions. 
After inputting the video, it will be tested and output the screenshots of each object. For example, a screenshot of the car number 1 and save it to the output (if each The frame is 1920*1080, the screenshot of the car may only be 600*400).

Only one image is captured for each ID, no repetition.

The sub-folders are named after each different object under the output folder, for example:

inference/output/car/*.jpg
inference/output/person/*.jpg
inference/output/truck/*.jpg

**Comment by mikel-brostrom** [comment]
I have no intention of adding project specific needs to the repo. Feel free to add this functionality and submit a PR!
