### ISSUE TITLE
RuntimeError: Expected object of scalar type c10::Half but got scalar type float for sequence element 2.

### ISSUE THREAD

**Issue by raja1196** [mikel-brostrom/Yolov5_DeepSort_Pytorch#19]
Hello. When i ran track.py i am getting this error:

python3 track.py --source testvideo.mp4 --device 0 --save-txt 
Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.4, config_deepsort='deep_sort/configs/deep_sort.yaml', device='0', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=True, source='testvideo.mp4', view_img=False, weights='yolov5/weights/yolov5x.pt')
/data/home/testVM/data/testing/Yolov5_DeepSort_Pytorch/deep_sort/utils/parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
video 1/1 (1/292) /data/home/testVM/data/testing/Yolov5_DeepSort_Pytorch/testvideo.mp4: Traceback (most recent call last):
  File "track.py", line 236, in <module>
    detect(args)
  File "track.py", line 126, in detect
    pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, classes=opt.classes, agnostic=opt.agnostic_nms)
  File "/data/home/testVM/data/testing/Yolov5_DeepSort_Pytorch/yolov5/utils/general.py", line 630, in non_max_suppression
    x = torch.cat((box[i], x[i, j + 5, None], j[:, None].float()), 1)
RuntimeError: Expected object of scalar type c10::Half but got scalar type float for sequence element 2.

**Comment by qingqizhangqingqi** [comment]
I have the same error! do you slove the problem?

**Comment by raja1196** [comment]
Not yet. I tried running it on different videos as well. Still the same error.

**Comment by mikel-brostrom** [comment]
You don't fulfill the minimum requirements @raja1196. I suggest you to upgrade to torch>=1.6 & python3.8.
Let me know if that solves the problem!

**Comment by raja1196** [comment]
@mikel-brostrom Yes, updating to the latest version of torch and python helped. Now the code is running as expected.
