### ISSUE TITLE
How to add counting feature using this?

### ISSUE THREAD

**Issue by hammadyounas2008** [mikel-brostrom/Yolov5_DeepSort_Pytorch#191]
I want to count number of objects per frame how can I do that using this?

**Comment by hammadyounas2008** [comment]
This is for darknet ,i am using Pytorch Yolov5 Can you please help me in that?

**Comment by darko262** [comment]
> Esto es para darknet, estoy usando Pytorch Yolov5. ¿Pueden ayudarme con eso?

Did you find any solution for it?
