### ISSUE TITLE
put my weights path in track.py script

### ISSUE THREAD

**Issue by Riad123321** [mikel-brostrom/Yolov5_DeepSort_Pytorch#192]
Hi everyone
when i put the path of my weights file and run track.py it downloading pretrained model weights from internet 
but i don't want Yolov5_DeepSort_Pytorch have access to internet  just want it to use my weights and i think the problem in attempt_load function inside track.py  script what should i do?

**Comment by shadfien** [comment]
Hi， did you solve this problem？
