### ISSUE TITLE
Track.py

### ISSUE THREAD

**Issue by feidasheng** [mikel-brostrom/Yolov5_DeepSort_Pytorch#2]
hello,  i want to ask why i run the track.py  ,the code shows that the running result is calling the CPU to run the video. I tried to repair the device and called the GPU. It has not been successful. Can you tell you how to modify it?

**Comment by mikel-brostrom** [comment]
Hi!

It seems to me like CUDA ([https://developer.nvidia.com/cuda-toolkit]) is not available in your environment at all. The select_device method checks whether the device argument is "cpu" or not. If not, it fetch all the CUDA available devices and use the first one as your CUDA device.

**Comment by feidasheng** [comment]
oh,my CUDA version is 10.0,is this reason make CUDA&nbsp; not available for me ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mike"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 下午4:26
收件人:&nbsp;"mikel-brostrom/Yolov5_DeepSort_Pytorch"<Yolov5_DeepSort_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"╭学絵パ紾悕"<1170776918@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_DeepSort_Pytorch] Track.py (#2)





 
Hi!
 
It seems to me like CUDA ([https://developer.nvidia.com/cuda-toolkit]) is not available in your environment at all. The select_device method checks whether the device argument is "cpu" or not. If not, it fetch all the CUDA available devices and use the first one as your CUDA device.

**Comment by mikel-brostrom** [comment]
Most certainly that is that is problem. Torch 1.5.1 (the version that is installed with requirements.txt) is by default CUDA 10.2 compatible. You will need to downgrade both torch and torchvision so that they work with your CUDA version or upgrade CUDA
