### ISSUE TITLE
How to performing object counting for a video?

### ISSUE THREAD

**Issue by lolwakid** [mikel-brostrom/Yolov5_DeepSort_Pytorch#202]
I want to create a function which will count the number of predictions made by the object tracking script. It should write the class count for each label visible in the video.
For eg:-
Object 1: 3
Object 2: 1
Object 3: 5
Also, I have multiple class labels (8). Any help will be appreciated as I am not accustomed with pytorch but my object detection and tracking is working really good (mAP = 0.9).

**Comment by ratva0717** [comment]
Hi @lolwakid 
Did you find any solution for it?

**Comment by darko262** [comment]
> I want to create a function which will count the number of predictions made by the object tracking script. It should write the class count for each label visible in the video. For eg:- Object 1: 3 Object 2: 1 Object 3: 5 Also, I have multiple class labels (8). Any help will be appreciated as I am not accustomed with pytorch but my object detection and tracking is working really good (mAP = 0.9).

Did you find any solution for it?
