### ISSUE TITLE
confidence score

### ISSUE THREAD

**Issue by Riad123321** [mikel-brostrom/Yolov5_DeepSort_Pytorch#205]
Hi
as i see i can extract left, top, width,height and tracking_id for each detection as txt file when running track.py script but there are no conf score for each detection from yolov5 in txt file is there anyway to extract it when running track.py script and if it's possible i want average conf score for each detection when ensembling multiple yolov5 versions.

**Comment by mikel-brostrom** [comment]
You have a solution here (https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/pull/204)
