### ISSUE TITLE
problem when no detections

### ISSUE THREAD

**Issue by bryceburrows** [mikel-brostrom/Yolov5_DeepSort_Pytorch#21]
if there have been some detections then there is a period of time where there are no object detections, the tracker doesn't get updated.
Which means the age of the last tracks stays the same...which would seem to be wrong - as the age should increase even if there has been no detections...

in track.py

age : int
        Total number of frames since first occurance.

But the code 

                outputs = deepsort.update(xywhs, confss, im0)

only gets called if there has been a successful object detection. (from what i can tell) 
This can be ok if you have a constant detections, but not if you have periods where your objects are more sparely occurring.

**Comment by mikel-brostrom** [comment]
Thank you for your feedback @bryceburrows!

You are totally right. I will try to fix this issue in the coming weeks

**Comment by bryceburrows** [comment]
i have a fix that seems to work - don't to push the while thing as ive made a bunch of mod's for another use.
 
can send it to you if you like

**Comment by mikel-brostrom** [comment]
Sure! Feel free to leave it here as a comment :)

**Comment by bryceburrows** [comment]
ok so without thinking too hard:

Yolov5_DeepSort_Pytorch\deep_sort\deep_sort\sort\track.py
def increment_age(self):
        self.age += 1
        self.time_since_update += 1

  def predict(self, kf):
        """Propagate the state distribution to the current time step using a
        Kalman filter prediction step.

        Parameters
        ----------
        kf : kalman_filter.KalmanFilter
            The Kalman filter.

        """
        self.mean, self.covariance = kf.predict(self.mean, self.covariance)
        #self.age += 1
        self.increment_age()
       # self.time_since_update += 1

 Yolov5_DeepSort_Pytorch\deep_sort\deep_sort\sort\tracker.py
 
def increment_ages(self):
        for track in self.tracks:
            track.increment_age()
            track.mark_missed()

deepsort.py add

    def increment_ages(self):
        self.tracker.increment_ages()



and in Yolov5_DeepSort_Pytorch\track.py


     else:
                p, s, im0 = path, '', im0s

            s += '%gx%g ' % img.shape[2:]  # print string

            if det is  None:
                deepsort.increment_ages()

            if det is not None and len(det):
                # Rescale boxes from img_size to im0 size
                det[:, :4] = scale_coords(img.shape[2:], det[:, :4], im0.shape).round()

**Comment by kanasite** [comment]
*bump*, is this fixed?

**Comment by mikel-brostrom** [comment]
This issue is now fixed and pushed to master @kanasite, @bryceburrows
