### ISSUE TITLE
use my own yolov5s.pt module error

### ISSUE THREAD

**Issue by hushuai1** [mikel-brostrom/Yolov5_DeepSort_Pytorch#212]
I want to replace your yolov5 weights .I trianed a yolov5s6.pt but error appear，Which part of the code should I modify to use my own model？
![image](https://user-images.githubusercontent.com/43898397/140000562-4462ae6f-6647-44ec-8d2e-882e85564b15.png)

**Comment by hushuai1** [comment]
SORRY I have solved this problem,it caused by the yolo version

**Comment by ddg238** [comment]
@hushuai1 Hello, how did you solve this problem? I use my yolov5x model also produces the same error, I don’t know how to solve it

**Comment by hushuai1** [comment]
> @hushuai1 Hello, how did you solve this problem? I use my yolov5x model also produces the same error, I don’t know how to solve it
use yolov5 version to train your model:https://github.com/ultralytics/yolov5/tree/47fac9ff73aceedd267db1e734a98de122fc9430
