### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'eval'

### ISSUE THREAD

**Issue by wallfacer2** [mikel-brostrom/Yolov5_DeepSort_Pytorch#213]
Hi！
I get an error when I run the track.py, I have downloaded the deepsort and yolov5's weights file myself and added them.
`Traceback (most recent call last):
  File "G:/Yolov5_DeepSort_Pytorch/track.py", line 216, in <module>
    detect(args)
  File "G:/Yolov5_DeepSort_Pytorch/track.py", line 53, in detect
    model = attempt_load(yolo_weights, map_location=device)  # load FP32 model
  File "G:\Yolov5_DeepSort_Pytorch\yolov5\models\experimental.py", line 110, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
AttributeError: 'NoneType' object has no attribute 'eval'`

**Comment by mikel-brostrom** [comment]
There may be a mismatch between the downloaded weights and the yolov5 submodule version if you download them yourself. Just download them automatically. That is why the functionality is there. So that you don't need to think about this type of issues.
