### ISSUE TITLE
Slow performance with NVIDIA Jetson TX2

### ISSUE THREAD

**Issue by fatbringer** [mikel-brostrom/Yolov5_DeepSort_Pytorch#215]
Hi there. Has anyone else tried running it on an embedded computer platform ? Im currently running it on a DJI Manifold 2G which is internally an NVIDIA Jetson TX2. For 480x640 frame size, each frame takes about 8 seconds to process. For frames with 2 detections, it takes about 12s to process. 

```
0: 480x640 1 tv, Done. (8.416s)
0: 480x640 1 person, 1 bottle, Done. (12.425s)
0: 480x640 1 person, 1 bottle, Done. (13.246s)
````

Platform Specs:
DJI Manifold 2G (NVIDIA Jetson TX2) 
The specs are, if they are helpful: Processor: ARMv8 Processor rev 3 (v8l) × 4
Graphics: NVIDIA Tegra X2 (nvgpu)/integrated Os type: 64-bit Memory: 8gb

**Comment by mikel-brostrom** [comment]
Are you sure that you are running it on GPU?

**Comment by fatbringer** [comment]
How might I check/verify this ? For this embedded computer it's actually running only on a GPU.

**Comment by mikel-brostrom** [comment]
You can check what is running on GPU by this command:

`nvidia-smi`

**Comment by fatbringer** [comment]
Hi i realise i am unable to run the ```nvidia-smi``` command. Let me get back to you when I have resolved it. Could be a driver error.

**Comment by mikel-brostrom** [comment]
most certainly you are running stuff on CPU then :smile:
