### ISSUE TITLE
a bug in output text file

### ISSUE THREAD

**Issue by goldentimecoolk** [mikel-brostrom/Yolov5_DeepSort_Pytorch#217]
According to https://motchallenge.net/instructions/ the index of the first frame is 1, but from [here](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/master/track.py#L158), the beginning index is 0. Is this  a bug?

**Comment by amindehnavi** [comment]
Hi @goldentimecoolk  
did you find the answer? I have the same issue! 
I test the tracker on MOT17-11 and MOT17-11 sequences and in both cases, the frame numbers start from '2' and end up with 'seq_length - 1'. consequently, I cant check the result using MOT devkit [https://github.com/JonathonLuiten/TrackEval/issues](URL)

Thanks

**Comment by mikel-brostrom** [comment]
You are totally right @goldentimecoolk! 
Thank you for pointing this out!
Now, I need to re-run the whole evaluation
