### ISSUE TITLE
result cannot save

### ISSUE THREAD

**Issue by zxbgoat** [mikel-brostrom/Yolov5_DeepSort_Pytorch#22]
I used your code on a video, but it showed this error:

```bash
2020-10-09 19:01:42.440 python[34438:785101] mMovieWriter.status: 3. Error: Cannot Save
```

**Comment by bryceburrows** [comment]
heya - what kind of video? also..mac or pc?

**Comment by zxbgoat** [comment]
mp4 video, an I used mac. I've locate the problem, in the 203 line of your code is:

```python
vid_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*opt.fourcc), fps, (w, h))
```

but in the 111 line, the value of `save_path` is:

```python
save_path = str(Path(out))
```

It's actually a directory, so error occurred.

**Comment by mikel-brostrom** [comment]
Hi @zxbgoat & @bryceburrows !

I fixed the video saving bug now. Let me know if it works for you!

**Comment by bryceburrows** [comment]
cool - fix it in my copy a while ago - should have uploaded my changes.
