### ISSUE TITLE
Try draw motion path but have error path

### ISSUE THREAD

**Issue by zaiplanet** [mikel-brostrom/Yolov5_DeepSort_Pytorch#221]
**Hi,
I try draw motion path by get id from outputs[4] as below image but i get error with some motion path very long :(**
Please tell me where am i wrong. Thanks you

**Code image:**

**pts = [deque(maxlen=30) for _ in range(9999)]**

![image](https://user-images.githubusercontent.com/58675403/141721326-97ee88ac-6e7f-45db-8d96-45018ac5f72b.png)

**Error motion path image:**
![image](https://user-images.githubusercontent.com/58675403/141721046-709de7b6-677a-49c0-bd97-e7776dc9b991.png)
![image](https://user-images.githubusercontent.com/58675403/141721107-bf592bc1-671d-41ee-939a-b3a6dec0bfc9.png)

**Comment by mikel-brostrom** [comment]
It is hard to tell what is going on here just by looking at the pictures. It looks to me that the ids get re-identified when they shouldn't

**Comment by zaiplanet** [comment]
@mikel-brostrom 
Every thing is default. I just added above code only :(

**Comment by prashant-py-debug** [comment]
Hi can u share, how are you accessing the bounding boxes from deepsort.

**Comment by mikel-brostrom** [comment]
Try lowering the MAX_AGE under deep_sort.yaml @zaiplanet !

Let me know if this helps!

**Comment by Camilochiang** [comment]
1. @zaiplanet did that help? Please close the issue if it was the case
2. For me that works :) . Reducing the value from 0.1 to 0.05

**Comment by mikel-brostrom** [comment]
Thx for the feedback @Camilochiang!

**Comment by zaiplanet** [comment]
Hi @mikel-brostrom @Camilochiang 
I'm so sorry late reply, i current working on c# for some my team project.
About draw motion path is more good now , i have reduced MAX_DIST from 2 to 1
Current will detect object is car and draw motion path
![image](https://user-images.githubusercontent.com/58675403/148147045-eba80956-436b-496c-953f-f2f1874cd28e.png)

https://user-images.githubusercontent.com/58675403/148148836-4e250297-311c-422a-a15b-7269e30f27b1.mp4


In this project I don't know how to calculate the speed based on the time bottomcenter_point move from line1 to line 2.
Do you have solution for this?
Thx for feedback @mikel-brostrom @Camilochiang !

**Comment by Camilochiang** [comment]
To calculate the absolute speed there is two things that you would need:
- The intrinsic and extrinsic parameters of the camera
- The angle of your camera, hoping that your camera is not moving.
As I assume than that is impossible to have, I would use the distance between the broken white line , that is more or less standard for every country. Then you could calculate speed ....

**Comment by zaiplanet** [comment]
If use the distance between the broken white line how to calculate the speed? 
 Thx for feedback @Camilochiang

**Comment by Camilochiang** [comment]
1. You need two arrays/lists: one for the position of the center of your object in each frame when going into your zone and another with the time. Btw, what is the fps of the camera?
2. Transform pixel to distance. Be aware that the transformation do not follow a y=ax+b model as you have deep involve
3. Calculate speed ;)

**Comment by XiangqingZhang** [comment]
hi，where I can put this code in track.py?

**Comment by XiangqingZhang** [comment]
Hi, @zaiplanet where I can put this code in track.py ?

**Comment by liang-jingyi** [comment]
@zaiplanet Can you share how you got the motion path？I don't know where to add the code you shared.Please help me

**Comment by zaiplanet** [comment]
> @zaiplanet Can you share how you got the motion path？I don't know where to add the code you shared.Please help me

you declare : `pts = [deque(maxlen=10) for _ in range(9999)]` at main code, outside of main loop.

While get output from deepsort at 
```
if len(outputs) > 0:
   for j, (output, conf) in enumerate(zip(outputs, confs)):
```

below `bboxes = output[0:4]`
you can get value x1,y1,x2,y2 from bboxes output
as `x1, y1, x2, y2 = int(bboxes[0]), int(bboxes[1]), int(bboxes[2]), int(bboxes[3])`

and you calculate a center point or bottom point from x1,y1,x2,y2
as `
centerpointX = (x1+x2)/2 ` and `centerpointY = (y1+y2)/2`
create `centerpoint = [int(centerpointX), int(centerpointY)]`
then draw point with `cv2.circle(im0, bottom_center, 1, (0,255,0), 2)`

and below you add some line code for store centerpoint into pts list and draw it
`pts[id].append(bottom_center) `                                  
```
for jj in range(1, len(pts[id])):
   if pts[id][jj - 1] is None or pts[id][jj] is None:
       continue
   thickness = int(np.sqrt(64 / float(jj + 1)))
   cv2.line(im0,(pts[id][jj-1]), (pts[id][jj]),colors(c, True),thickness)
```

**Comment by liang-jingyi** [comment]
@zaiplanet It worked. Thank you for your help！

**Comment by WestbrookZero** [comment]
> 

How can I solve it?

**Comment by WestbrookZero** [comment]
> > @zaiplanet Can you share how you got the motion path？I don't know where to add the code you shared.Please help me
> 
> you declare : `pts = [deque(maxlen=10) for _ in range(9999)]` at main code, outside of main loop.
> 
> While get output from deepsort at
> 
> ```
> if len(outputs) > 0:
>    for j, (output, conf) in enumerate(zip(outputs, confs)):
> ```
> 
> below `bboxes = output[0:4]` you can get value x1,y1,x2,y2 from bboxes output as `x1, y1, x2, y2 = int(bboxes[0]), int(bboxes[1]), int(bboxes[2]), int(bboxes[3])`
> 
> and you calculate a center point or bottom point from x1,y1,x2,y2 as `centerpointX = (x1+x2)/2` and `centerpointY = (y1+y2)/2` create `centerpoint = [int(centerpointX), int(centerpointY)]` then draw point with `cv2.circle(im0, centerpoint, 1, (0,255,0), 2)`
> 
> and below you add some line code for store centerpoint into pts list and draw it `pts[id].append(centerpoint) `
> 
> ```
> for jj in range(1, len(pts[id])):
>    if pts[id][jj - 1] is None or pts[id][jj] is None:
>        continue
>    thickness = int(np.sqrt(64 / float(jj + 1)))
>    cv2.line(im0,(pts[id][jj-1]), (pts[id][jj]),colors(c, True),thickness)
> ```

pts[id].append(center)
TypeError: list indices must be integers or slices, not numpy.float64

How can I solve it?
