### ISSUE TITLE
changing the FPS of input video

### ISSUE THREAD

**Issue by Jeehoon-K** [mikel-brostrom/Yolov5_DeepSort_Pytorch#223]
Hi,
First of all thank you for the wonderful research.

I was trying to change the FPS of input data to get the results like a 2fps divided video(for a 5min video, total of 600 frames).

I thought changing the numbers on ./track.py : line 186 (fps, w, h = 30 (=> 2), im0.shape[1], im0.shape[0]) and ./yolov5/detect.py : line239 (fps, w, h = 30 (=> 2), im0.shape[1], im0.shape[0]) would do the thing, but the results are still as default 30FPS.

Is there a way to change this?

Thanks in advance.

**Comment by Jeehoon-K** [comment]
I actually found that this is related with the opencv2 library itself.
not 100% sure but I think there isn't a way to solve it in this code.

still is there anyone that solved or trying to solve this problem?

**Comment by mikel-brostrom** [comment]
This may help you: https://stackoverflow.com/questions/22704936/reading-every-nth-frame-from-videocapture-in-opencv

**Comment by Jeehoon-K** [comment]
> This may help you: https://stackoverflow.com/questions/22704936/reading-every-nth-frame-from-videocapture-in-opencv

Thank you mikel,
For now, I'm going on with the 30fps for the model, and picking the nth frames of the output by another code.
I will try your suggestions afterwards.
Thanks again!
