### ISSUE TITLE
run rack.py，NameError: name 'save_dir' is not defined

### ISSUE THREAD

**Issue by yangwang3074897** [mikel-brostrom/Yolov5_DeepSort_Pytorch#224]
run  track.py

Traceback (most recent call last):
  File "track.py", line 242, in <module>
    detect(opt)
  File "track.py", line 207, in detect
    s = f"\n{len(list(save_dir.glob('labels/*.txt')))} labels saved to {save_dir / 'labels'}" if save_txt else ''
NameError: name 'save_dir' is not defined

**Comment by mikel-brostrom** [comment]
Fixed!

Pull & try again
