### ISSUE TITLE
why it show "No module named 'yolov5.models'"

### ISSUE THREAD

**Issue by hackerroy** [mikel-brostrom/Yolov5_DeepSort_Pytorch#225]
i use you code,but it false

**Comment by mikel-brostrom** [comment]
You downloaded the project with:

`git clone https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

instead of:

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`
