### ISSUE TITLE
My own training data does not work well with video.

### ISSUE THREAD

**Issue by Tomoya6436** [mikel-brostrom/Yolov5_DeepSort_Pytorch#226]
I'm not good at English, so it may be hard to understand. I'm sorr
![名称未設定のノート (14)-2](https://user-images.githubusercontent.com/94614689/142412127-9eafbf27-4422-4616-a66c-85c32d493a03.jpg)
y.

**Comment by ouyang11111** [comment]
you should rewrite the file in to yourself   in data/VOC.yaml    if  in  train .py  line 444   you set is parser.add_argument('--data', type=str, default=ROOT / 'data/VOC.yaml', help='dataset.yaml path')    #cahnged

**Comment by Tomoya6436** [comment]
> 列車の.pyライン444で設定したparser.add_argument('--data', type=str, default=ROOT / 'data/VOC.yaml', help='dataset.yaml path')の場合は、data/VOC.yamlでファイルを自分自身に書き換える必要があります #cahnged
<img width="1436" alt="スクリーンショット 2021-11-20 13 58 09" src="https://user-images.githubusercontent.com/94614689/142715948-9cab7ef3-ce8a-406b-bfce-d123eca12e19.png">
