### ISSUE TITLE
DetectMultiBackend not found

### ISSUE THREAD

**Issue by coallar** [mikel-brostrom/Yolov5_DeepSort_Pytorch#227]
Hi, bro, where could i find detecMultiBackend in yolov5?

![image](https://user-images.githubusercontent.com/66529823/142648211-d47cd28b-2a74-4c00-9d4d-995ed6f24564.png)

**Comment by meeftah** [comment]
same here

**Comment by mikel-brostrom** [comment]
The CPU CI testing is passing. This means that `track.py` runs as it should on Linux if you install everything correctly. How did you cloned the repo?

This is wrong:

`git clone https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

This is right:

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`
