### ISSUE TITLE
How to add the link of  ultralytics-yoloV5?

### ISSUE THREAD

**Issue by whuyyc** [mikel-brostrom/Yolov5_DeepSort_Pytorch#229]
I noticed that the folder of yoloV5 in this resposity has a link function. It jumpt to the source address of ultralytics-yoloV5 when I clicked the folder. That is very convenient but I don't know how to achieve it. Could you please tell me the way to set a link like that?

**Comment by mikel-brostrom** [comment]
It is called submodule. You can read about it here: https://git-scm.com/book/en/v2/Git-Tools-Submodules
