### ISSUE TITLE
About tracking speed？

### ISSUE THREAD

**Issue by GJTNB** [mikel-brostrom/Yolov5_DeepSort_Pytorch#23]
Hello, my configuration is GTX660ti, 6G, but the speed I detected is about 0.3 seconds per frame, may I ask if there is a problem with my settings that causes the speed to slow down.

**Comment by GJTNB** [comment]
my pytorch is 1.6.0, and cudn is 11.0

**Comment by mikel-brostrom** [comment]
Most certainly you have an incompatibility problem. Pytorch 1.6.0 is official available ONLY for CUDA:  9.2, 10.1, 10.2. You could solve it by downgrading your CUDA version

**Comment by GJTNB** [comment]
I lowered my cuda version, but the speed still did not improve, about 3fps.  I tested YOLOv5 separately, the speed can reach 30fps, and I tested yolov3_deepsort under this link (https://github.com/ZQPei/deep_sort_pytorch),  the speed can also reach 30fps, may I ask what else may cause me to test YOLOv5_deepsort is so slow?

**Comment by GJTNB** [comment]
> Most certainly you have an incompatibility problem. Pytorch 1.6.0 is official available ONLY for CUDA: 9.2, 10.1, 10.2. You could solve it by downgrading your CUDA version
I lowered my cuda version, but the speed still did not improve, about 3fps. I tested YOLOv5 separately, the speed can reach 30fps, and I tested yolov3_deepsort under this link (https://github.com/ZQPei/deep_sort_pytorch), the speed can also reach 30fps, may I ask what else may cause me to test YOLOv5_deepsort is so slow?

**Comment by GJTNB** [comment]
Maybe my configuration is not good. When I use Yolov5s, the speed can reach 30FPS, but when I use Yolov5x, the speed is only 3Fps，thanks.

**Comment by mikel-brostrom** [comment]
The issue then could be that both models don't fit simultaneously in memory. The NVIDIA GeForce GTX 660 Ti "only" has 2GB of memory.

**Comment by GJTNB** [comment]
Sorry, I said my configuration was wrong. I am 1660TI with 6G of memory. It seems that it is caused by the slow speed of target detection，when I test with Yolov5S, the detection speed can reach 30FPS, but the test speed with Yolov5X is only 3FPS. Do you have any solutions？

**Comment by javiergarcferrer** [comment]
What fps would be normal if everything would be working as supposed to? I have 2080 Super with CUDA 10.2 and am getting between 20-30 fps with yolov5s

**Comment by mikel-brostrom** [comment]
@GJTNB Yolov5X has more than 10 times the amount of parameters of Yolov5S so that is the reason for the inference slowdown.

**Comment by mikel-brostrom** [comment]
@javiergarcferrer  It depends on what GPU you have and the computational load of the GPU at the moment of running. I get ~6FPS with Yolov5x and ~50FPS with Yolov5s on a modest Nvidia Quadro P2000, 4GB
