### ISSUE TITLE
Multiprocessing performance issue

### ISSUE THREAD

**Issue by sriktrako** [mikel-brostrom/Yolov5_DeepSort_Pytorch#232]
Hi @mikel-brostrom,

I wanted to try and reduce the time taken to extract features of the detected bounding boxes to gain a little boost in FPS. I implemented multi-processing to batch m detections and split across n processes to extract features, but I couldn't see much difference in time taken to extract features.
For instance time taken to extract features of 15 detections is taking almost same time as extracting features of 5 detections parallelly across 3 processes. In theory the time taken should have been cut to 1/3rd, but it's not the case. 
With assumption that the multi-processing implementation is correct, is there something I am missing in terms of the model behavior? Any idea on why this might be happening? Thank you in advance.

**Comment by mikel-brostrom** [comment]
My guess is that the time it takes to start the threads and the time it eventually takes for each thread to load their corresponding model to GPU (not sure if this is what you are doing?) is higher than just handling it sequentially on a single thread and single model on GPU
