### ISSUE TITLE
How to calculate MOTA Accuracy on Custom dataset?

### ISSUE THREAD

**Issue by ImSuMyatNoe** [mikel-brostrom/Yolov5_DeepSort_Pytorch#233]
As I am a newbie in CVision field, Could you please tell me how to calculate MOTA Accuracy on Custom dataset?

**Comment by mikel-brostrom** [comment]
The results for each sequence must be stored in a separate .txt file in the archive's root folder. The file name must be exactly like the sequence name (case sensitive).  Moreover, each line must contain 10 values: 

```<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z> ```

You can find detailed information here:

https://motchallenge.net/instructions/
