### ISSUE TITLE
id swap

### ISSUE THREAD

**Issue by MICHIokaGAN** [mikel-brostrom/Yolov5_DeepSort_Pytorch#234]
I'm currently working on a project, in which I'm trying to track players in a soccer match video.
When I input the video, it tracks the players very well. However, I'm having some difficulties. There are some players that randomly swap their id numbers, even if they're not even close in real life. I think this is occurring because even though the players are not close(they're a few meters apart) in real life, in the video they seem close (image coordinate-wise) because they appear small.

Is there any way that I could solve this problem?
Maybe changing the hyperparameters?
![unnamed](https://user-images.githubusercontent.com/87413878/144245674-a342a241-6c49-42e8-94b9-0e51b695e999.jpg)

**Comment by mikel-brostrom** [comment]
Yes this is a know issue... Check:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/138

**Comment by mikel-brostrom** [comment]
But you can start lowering MAX_DIST under deep_sort.yaml

Let me know if this solves your issue!

**Comment by MICHIokaGAN** [comment]
thank you!
I’ll try it!

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/221

**Comment by gigasurgeon** [comment]
take a look at my comment here - https://github.com/mikel-brostrom/boxmot/issues/1226#issuecomment-2225815222
