### ISSUE TITLE
custom tracking

### ISSUE THREAD

**Issue by yotamraz** [mikel-brostrom/Yolov5_DeepSort_Pytorch#235]
Hi, i'm trying to get tracking to work on non-COCO classes. My custom detection model works fine as I'm getting preds up until row 149 in track.py
`outputs = deepsort.update(xywhs.cpu(), confs.cpu(), clss.cpu(), im0)`
outputs is just an empty list for every frame.

Any suggestions here? training a custom extractor is something I'd rather not do.

**Comment by mikel-brostrom** [comment]
Hi @yotamraz!

I have a very hard time seeing that

` outputs = deepsort.update(xywhs.cpu(), confs.cpu(), clss.cpu(), im0)`

could output an empty list. Could you provide more information about
your specific issue?

**Comment by memesoo99** [comment]
I have the same issue @yotamraz . 
Did you solve the issue?

**Comment by yotamraz** [comment]
Yeah, so I ended up commenting out some lines in `deep_sort_pytorch/deep_sort/deep_sort.py`

lines 41 to 58 should be something like this:

`
        # output bbox identities
        outputs = []
        for track in self.tracker.tracks:
            # TODO: check with repo owner for correctness
            # if not track.is_confirmed() or track.time_since_update > 1:
            #     continue
            # if use_yolo_preds:
            #     det = track.get_yolo_pred()
            #     x1, y1, x2, y2 = self._tlwh_to_xyxy(det.tlwh)
            # else:
            box = track.to_tlwh()
            x1, y1, x2, y2 = self._tlwh_to_xyxy(box)
            track_id = track.track_id
            class_id = track.class_id
            outputs.append(np.array([x1, y1, x2, y2, track_id, class_id], dtype=np.int))
        if len(outputs) > 0:
            outputs = np.stack(outputs, axis=0)
        return outputs
`
