### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by shituo123456** [mikel-brostrom/Yolov5_DeepSort_Pytorch#236]
where scripts/run_mot_challenge.py ?
eval.sh ---The path inside is wrong

thank you

**Comment by mikel-brostrom** [comment]
The eval script assumes that you have the Yolov5_DeepSort_Pytorch folder under `~/`.

From there you 

`cd Yolov5_DeepSort_Pytorch`

and then

`./MOT16_eval/eval.sh  `
