### ISSUE TITLE
about deep appearance descriptor

### ISSUE THREAD

**Issue by MICHIokaGAN** [mikel-brostrom/Yolov5_DeepSort_Pytorch#237]
Is there any paper or an article, explaining about the deep appearance descriptor besides [this paper](https://arxiv.org/abs/1703.07402)?

It'll be nice letting me know if you know one.

**Comment by mikel-brostrom** [comment]
You can find a lot of information about ReID models [here](https://github.com/KaiyangZhou/deep-person-reid#reid-specific-models)
