### ISSUE TITLE
It can't work on ubuntu

### ISSUE THREAD

**Issue by zhangchunsheng** [mikel-brostrom/Yolov5_DeepSort_Pytorch#238]
The docker container run with image python:3.9.

```
Traceback (most recent call last):
  File "/pytorch/track.py", line 242, in <module>
    detect(opt)
  File "/pytorch/track.py", line 63, in detect
    model = DetectMultiBackend(opt.yolo_weights, device=device, dnn=opt.dnn)
  File "/pytorch/yolov5/models/common.py", line 305, in __init__
    model = torch.jit.load(w) if 'torchscript' in w else attempt_load(weights, map_location=device)
  File "/pytorch/./yolov5/models/experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by mikel-brostrom** [comment]
The CPU CI testing is passing. This means that track.py runs as it should on Linux if you install everything correctly.

**Comment by zhangchunsheng** [comment]
> The CPU CI testing is passing. This means that track.py runs as it should on Linux if you install everything correctly.

python-version: [3.8]

There is no python 3.9 test.

**Comment by mikel-brostrom** [comment]
Python version updated to 3.9 under CI

**Comment by zhangchunsheng** [comment]
> It is most certainly something wrong with your checkpoint. Isolate the problem. Try to:
> 
> 1. Checkout the same YOLOv5 state as in this repo
> 2. Try to load your model there
> 3. Report back

It can work now. Thank you.

I build  a docker image, it can work as a job.

![image](https://user-images.githubusercontent.com/831839/144995387-c637cea2-ebc4-4d78-9744-a0d7d72c8f68.png)
