### ISSUE TITLE
Tensor size error when I try to use customized yolo model(16 classes)

### ISSUE THREAD

**Issue by gjustin40** [mikel-brostrom/Yolov5_DeepSort_Pytorch#239]
Hi, I am trying to use DeepSort with my own model that trained with yolov5

It has 16 classes and trained from [ultralytics](https://github.com/ultralytics/yolov5).

When I tried default model that @mikel-brostrom provided, It works.
But with my model, It comes out with error like this.

![image](https://user-images.githubusercontent.com/25999141/144810867-e2b79458-66d8-4f59-bfe2-e25b4b47c1ed.png)

Where Should I change? Thanks.

Python 3.7
torch 1.7

**Comment by mikel-brostrom** [comment]
Are you specifying your custom `.yaml` file under `yolov5/data/` to  `track.py` with 

```python
--data xxx.yaml
```

?

**Comment by gjustin40** [comment]
I'm sorry that I didn't write it down in detail.

I successfully trained  and inference my own model( 16 classes) with [ultralytics](https://github.com/ultralytics/yolov5).
It works when I use my model for 'Object Detection' with 16 classes. So `.yaml` file that i used for train is correct.(16 classes)

Then, I take the wieght(best.pt) to [Yolov5_DeepSort_Pytorch](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) and just try to use track.py for inference, and i got the `size error`. This is the command that i used.

`python track.py --yolo_weight yolov5/weights/best.pt --source example.mp4`

Should I need to specify the `.yaml` file to use `track.py` for only inference? As far as I know,  `.yaml` file is for training, isn't it?

Just in case, I change all of `nc` value in `.yaml` files and try it again, still get same error.

**Comment by gjustin40** [comment]
I Just trained again with yolov5 code that included in [Yolov5_DeepSort_Pytorch](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch), and it works.

I used exactly same `.yaml` file and datasets.

I don't know the difference between those.... sorry for causing confusion.

**Comment by Camilochiang** [comment]
@gjustin40 Could you re open this issue? the actual track.py file doesn't not accept the --data argument
`track.py: error: unrecognized arguments: --data test.yaml`

**Comment by Camilochiang** [comment]
For the records: If anyone have trained already a model, the actual solution is copying your .yaml file to the yolov5/data folder of this repository. Good luck!
