### ISSUE TITLE
Merging bounding boxes

### ISSUE THREAD

**Issue by FaHaD-Elm** [mikel-brostrom/Yolov5_DeepSort_Pytorch#24]
Hi Mike,

First of all thank you for code implementation!

I have a question regarding the possibility of merging two detected classes together. for example I have a custom class (not included in coco dataset) trained on Yolov5 and I want to use the deepsort tracker for pedestrian to track and yolo to detect!

my use case is head gear detection in construction site. and i want to use the deepsort pedestrian tracking to count and track the number of persons wearing head gear.
I already trained a Yolov5 model to detect head gear but I wish to merge the yolov5 bounding box with the pedestrian bounding box from deepsort!

I hope my issue is clear. 
thank you for your time.

**Comment by mikel-brostrom** [comment]
> I wish to merge the yolov5 bounding box with the pedestrian bounding box from deepsort

DeepSort depends on the detections made by Yolov5 for making predictions, so what you ask for makes little sense. 

However, what you could do is to train Yolov5 on persons and head gear and then use [Bayes' theorem](https://en.wikipedia.org/wiki/Bayes%27_theorem) to get a probability estimation of a person wearing head gear
