### ISSUE TITLE
Extraction of trajectories

### ISSUE THREAD

**Issue by prashant-py-debug** [mikel-brostrom/Yolov5_DeepSort_Pytorch#240]
Hi, is there a way to extract the future trajectory for the object deepsort is tracking. I know kalman filters are used to predict the trajectories of the moving object. Can we do the same with deepsort.
Thank you

**Comment by mikel-brostrom** [comment]
Yes, you can do multiple prediction ahead. However, this is not implemented

**Comment by prashant-py-debug** [comment]
Thanks, and can you give me an idea how to do that with this code?

**Comment by mikel-brostrom** [comment]
This is making the predictions:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/c7cc0a82025279f5b1f257c82bc454041a8e9077/deep_sort_pytorch/deep_sort/sort/kalman_filter.py#L88

**Comment by akbarali2019** [comment]
> Thanks, and can you give me an idea how to do that with this code?

Have you tried to make it? If so could you share your knowledge?
