### ISSUE TITLE
How can I reduce the vibration of bbox?

### ISSUE THREAD

**Issue by semchan** [mikel-brostrom/Yolov5_DeepSort_Pytorch#242]
Although I see that the Kalman filter has been enabled in the code, the position of the box obtained when I disable the Kalman filter is almost the same as that obtained when it is enabled. How can I reduce the jitter of the tracking bbox during movement? thank you

**Comment by mikel-brostrom** [comment]
You can take back the previous Kalman Filter which only used the height for its state update. It should give less bbox noise during tracking. However, this can lead to incorrect height estimations; specially when objects enter the field of view as can be seen here (https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/166)
