### ISSUE TITLE
MOT16_eval

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#244]
Thank you very much for your reply. I would like to know how to run the folder of multi-objective evaluation indicators to get MOT16 evaluation results (such as MOTA).

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/wiki/Evaluation

**Comment by MICHIokaGAN** [comment]
I'm using Google Colab.
Just by running the script `!./MOT16_eval/eval.sh`, nothing seems to be happening.
Also, I get the following error.
`/bin/bash: ./MOT16_eval/eval.sh: /bin/bash: bad interpreter: Permission denied`

**Comment by mikel-brostrom** [comment]
Sorry, cannot help you there. Have never run the evaluation script on Colab

**Comment by SuperbTUM** [comment]
In Google colab, if you want to execute bash script in your current script, you should type `!bash ./MOT16_eval/eval.sh`.

**Comment by MICHIokaGAN** [comment]
@SuperbTUM 
thanks a lot!!

**Comment by SuperbTUM** [comment]
@MICHIokaGAN 
BTW, can I ask where to download the `data.zip` file? When I try to run the bash script, I got an error message: `trackeval.utils.TrackEvalException: Tracker file not found: ch_yolov5m_deep_sort/data/MOT16-02.txt`
I have already downloaded the `mot16.zip` as well as the detection model on the wiki page.
Thanks in advance.

**Comment by qingfengJade** [comment]
> @MICHIokaGAN BTW, can I ask where to download the `data.zip` file? When I try to run the bash script, I got an error message: `trackeval.utils.TrackEvalException: Tracker file not found: ch_yolov5m_deep_sort/data/MOT16-02.txt` I have already downloaded the `mot16.zip` as well as the detection model on the wiki page. Thanks in advance.

I met this question too

**Comment by mikel-brostrom** [comment]
>  When I try to run the bash script, I got an error message: `trackeval.utils.TrackEvalException: Tracker file not found: ch_yolov5m_deep_sort/data/MOT16-02.txt`

Hmm, weird. This: `ch_yolov5m_deep_sort/data/MOT16-02.txt` is something that should be generated by the tracker 

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/5336c022a72ef7456bc94a37f6c29836cad1bebc/MOT16_eval/eval.sh#L80

before the evaluation starts

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/5336c022a72ef7456bc94a37f6c29836cad1bebc/MOT16_eval/eval.sh#L101

So maybe some prior step failed?

**Comment by SuperbTUM** [comment]
It might be due to the unstable mount between Google Drive and Google Colab. But when I execute it with my Ubuntu 18, another strange error occurred...
```
Inference on all MOT16 sequences DONE
  File "/home/xxx/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 52
    config = {**default_eval_config, **default_dataset_config, **default_metrics_config}
               ^
SyntaxError: invalid syntax

```

**Comment by mikel-brostrom** [comment]
`**` can be used to unpack dictionaries into keyword arguments in function calls. Beginning with python 3.5. What python version do you have?

**Comment by SuperbTUM** [comment]
@mikel-brostrom Solved it! Thanks a lot!

**Comment by XiangqingZhang** [comment]
> @mikel-brostrom Solved it! Thanks a lot!

@SuperbTUM How to solve it ？I occured same error

**Comment by maidouxiaozi** [comment]
MOT16_eval: The reproduction evaluation indicators are low
![image](https://user-images.githubusercontent.com/51068503/195815847-0e124812-7178-46b6-8e71-4290d2bc8a70.png)
![image](https://user-images.githubusercontent.com/51068503/195815872-271438f2-f028-46bf-8277-a7d087854d20.png)
![image](https://user-images.githubusercontent.com/51068503/195815887-d836c7a2-150f-4219-b6a8-3a2c215f4c56.png)

**Comment by mikel-brostrom** [comment]
Update the repo. Your source code isn't the latest

**Comment by maidouxiaozi** [comment]
> 更新存储库。您的源代码不是最新的
I use the yolov5s model, why does the old code run out poorly?

**Comment by maidouxiaozi** [comment]
I use the yolov5s model, why does the old code run out poorly? I updated the code and still get poor results

**Comment by mikel-brostrom** [comment]
Yolov5s is trained on COCO. If you are going to evaluate on MOT I recommend you to use a larger model which is trained on a large people dataset such as CrowdHuman.

**Comment by maidouxiaozi** [comment]
> CrowdHuman

That's not actually the reason for the code update? So where is this CrowdHuman being?

**Comment by mikel-brostrom** [comment]
You will only achieve the expected results if you run the script with the weights specified in the script

**Comment by maidouxiaozi** [comment]
> You will only achieve the expected results if you run the script with the weights specified in the script

I got the latest code and the model is CrowdHuman_yolov5m.pt and the output is also very poor? Why??

**Comment by mikel-brostrom** [comment]
Clone the latest and try again please

**Comment by mikel-brostrom** [comment]
This is a warning @maidouxiaozi. Your previous message is unwelcoming and unconstructive. I don't accept that in any of my repositories.

**Comment by maidouxiaozi** [comment]
> 这是一个警告@maidouxiaozi。您之前的信息不受欢迎且没有建设性。我在我的任何存储库中都不接受这一点。

i use crowdhuman_yolov5m.pt is not error, but i use yolov5s.pt model,  code is error:
![image](https://user-images.githubusercontent.com/51068503/197093241-8b33bd22-6a96-4148-afed-16a3beb32daa.png)
