### ISSUE TITLE
test.txt

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#247]
Sorry to bother you, and I look forward to your reply
The format of the data in the test. TXT file appears to be different from the MOT16gt result format. How can this be calculated
test.txt  ![image](https://user-images.githubusercontent.com/83855363/145836402-1d255a24-52a9-4516-bf41-236ef37ca88c.png)

**Comment by mikel-brostrom** [comment]
Hi!

To me

```python
f.write(('%g ' * 10 + '\n') % (frame_idx + 1, id, bbox_left,
                                                           bbox_top, bbox_w, bbox_h, -1, -1, -1, -1))  # label format
```

follows the MOT16 format standard according to:

https://motchallenge.net/instructions/

In what way is it different?
