### ISSUE TITLE
请问，该项目提供多类别多目标跟踪吗？

### ISSUE THREAD

**Issue by starsky68** [mikel-brostrom/Yolov5_DeepSort_Pytorch#25]
请问，该项目提供多类别多目标跟踪吗？

**Comment by mikel-brostrom** [comment]
Yes, it does. However, only persons are tracked as the re-identification algorithm is trained on a person only dataset. You can deactivate this by eliminating:

`default=[0]`

from

`parser.add_argument('--classes',` nargs='+', type=int, default=[0], help='filter by class')`

**Comment by starsky68** [comment]
> Yes, it does. However, only persons are tracked as the re-identification algorithm is trained on a person only dataset. You can deactivate this by eliminating:
> 
> `default=[0]`
> 
> from
> 
> `parser.add_argument('--classes',` nargs='+', type=int, default=[0], help='filter by class')`
> 
> The tracker will then start tracking all sorts of objects

请问，如何训练多类别的reid模型？可以给一些ReID数据集制作的说明吗？比如我做检测的时候有0，1，2，3，4，5，这六个类别，但是我要跟踪是0，2和，4，这三个类，然后reid在需要对这三个类进行训练，请问这三个类别的数据集如何去做，才可以更好的适应该项目。

**Comment by starsky68** [comment]
> Yes, it does. However, only persons are tracked as the re-identification algorithm is trained on a person only dataset. You can deactivate this by eliminating:
> 
> `default=[0]`
> 
> from
> 
> `parser.add_argument('--classes',` nargs='+', type=int, default=[0], help='filter by class')`
> 
> The tracker will then start tracking all sorts of objects

我设置参数--classes', nargs='+', type=int, default=[0,3,5,7,9,11,15,17,18,19,20]，但是追踪结果始终是一个类别的检测结果，我训练的reid模型和这里的类别是对应的，但是追踪的结果，id的分配只有一个序列？比如，有人的trackid=1，车的trackid=1，但是我得到的结果是所有类别都是从1-n的一个序列，而不是一个类别一个序列，请问，这个问题是什么原因？还是这就是正常的？

**Comment by mikel-brostrom** [comment]
This implementation makes no distinction between classes when it comes to giving them unique IDs. All objects end up in a pool of identified objects so that they can be associated to a certain ID or deleted after some time. The behavior your see is hence normal
