### ISSUE TITLE
 CrowdHuman,

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#251]
Crowdhuman_yolov5m.pt was trained using CrowdHuman, Crowdhuman_yolov5m.pt --classes 0 (non-header) is a crowdHuman data Vbox training or fbox training?Thank you for your reply.

**Comment by fengshuaibo** [comment]
![image](https://user-images.githubusercontent.com/83855363/147040744-863249f0-edf5-4624-888f-3c61a1d518c6.png)

**Comment by mikel-brostrom** [comment]
The model was obtained from:

https://github.com/deepakcrk/yolov5-crowdhuman

But based on the output I would say it is the full bbox

**Comment by fengshuaibo** [comment]
I can understand you mean that the detection of pedestrians (non-head detection) is based on full Bbox training

**Comment by mikel-brostrom** [comment]
Yes, that is right

**Comment by fengshuaibo** [comment]
train: Scanning 'VOCdevkit\labels\train.cache' images and labels... 11834 found, 0 missing, 0 empty, 4097 corrupted: 100%|██████████| 11834/11834 [00:00<?, ?it/s]
val: Scanning 'VOCdevkit\labels\val.cache' images and labels... 3166 found, 0 missing, 0 empty, 1066 corrupted: 100%|██████████| 3166/3166 [00:00<?, ?it/s]

Sorry to disturb you again. You can convert full Bbox data in crowdHuman into the format required by YOLO for training, but there is a problem with 4097 corrupted data. What is the reason?
