### ISSUE TITLE
deep_sort_model can't access to download from google drive in china

### ISSUE THREAD

**Issue by XiangqingZhang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#254]
![image](https://user-images.githubusercontent.com/22740766/147306381-6ad3b7b0-373e-4973-8151-7fd4cac17e13.png)

**Comment by mikel-brostrom** [comment]
I can't do anything about it as I am not hosting this models myself. You would need to contact the guy hosting the models: https://github.com/KaiyangZhou/deep-person-reid
