### ISSUE TITLE
UnboundLocalError: local variable 't5' referenced before assignment

### ISSUE THREAD

**Issue by HeChengHui** [mikel-brostrom/Yolov5_DeepSort_Pytorch#255]
was trying out `Python track.py --source "./sequences/uav0000077_02880_v/0000001.jpg" --yolo_model yolov5/weights/crowdhuman_yolov5m.pt --classes 0 --save-txt --device 0` on this image:
![0000001](https://user-images.githubusercontent.com/84503515/147325879-90c98039-be33-4cf7-a53f-f620fd98177e.jpg)
and it returns the following error:
```
 Fusing layers...
Model Summary: 308 layers, 21041679 parameters, 0 gradients
Traceback (most recent call last):
  File "track.py", line 245, in <module>
    detect(opt)
  File "track.py", line 181, in detect
    LOGGER.info(f'{s}Done. YOLO:({t3 - t2:.3f}s), DeepSort:({t5 - t4:.3f}s)')
UnboundLocalError: local variable 't5' referenced before assignment
```
But executes smoothly when image 0000007 was used instead:
![0000007](https://user-images.githubusercontent.com/84503515/147326592-45c82bd7-ac57-497f-8402-6e27924a818d.jpg)

**Comment by nir-avne** [comment]
This error happens when there are no YoloV5 detection found on the first frame of the video, see [this pull request](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/pull/258) for more details

**Comment by HeChengHui** [comment]
I see. Thank you!
