### ISSUE TITLE
how to train by train.py in your deep_sort/deep/

### ISSUE THREAD

**Issue by StawEndl** [mikel-brostrom/Yolov5_DeepSort_Pytorch#256]
"By default the tracker tracks all MS COCO classes." you said.
did you train the deep model by cocodataset?
and how to train?
should i train like yolov5?
put the folder like this:
coco/
.    train/
        .    images
        .    labels
.    val/
        .    images
        .    labels
like this? and run train.py?

**Comment by mikel-brostrom** [comment]
If you want to train a ReID model this is your best resource:

https://kaiyangzhou.github.io/deep-person-reid/user_guide.html

**Comment by StawEndl** [comment]
thanks,bro

**Comment by StawEndl** [comment]
> If you want to train a ReID model this is your best resource:
> 
> https://kaiyangzhou.github.io/deep-person-reid/user_guide.html

thanks,bro
