### ISSUE TITLE
are yolov5 weights the only thing I need in order to track my custom datasets (moving human cells)?

### ISSUE THREAD

**Issue by nicobrb** [mikel-brostrom/Yolov5_DeepSort_Pytorch#257]
I have my yolov56x weights, trained on imgsz 1280, can i use them in order to track my objects in my custom datasets? Or some more training is needed maybe with the deepSORT models?

**Comment by mikel-brostrom** [comment]
> I have my yolov56x weights, trained on imgsz 1280, can i use them in order to track my objects in my custom datasets?

Yes. You only need to load the weights and specify the video to do the tracking on

> Or some more training is needed maybe with the deepSORT models?

This tracker uses a two-stage approach. One stage is the object detection and the next is the association process. Both of them uses deep learning models. The former for detection objects of interest and the second extract visual features from these objects. Ideally, you would train both of them for your specific task.
