### ISSUE TITLE
Support for pytorch 1.7? (CUDA 11)

### ISSUE THREAD

**Issue by kanasite** [mikel-brostrom/Yolov5_DeepSort_Pytorch#26]
I ran into some error on pytorch 1.7 for CUDA 11 on windows, will it be supported?

**Comment by mikel-brostrom** [comment]
Soon! During this week I will give this repo an update

**Comment by mikel-brostrom** [comment]
Hi @kanasite 

You may want to try out the `submodules` branch. It should support pytorch1.7 and CUDA 11. Let me know whether it works for you or not

**Comment by kanasite** [comment]
@mikel-brostrom Thanks, will check it out. 

btw I'm not sure if https://github.com/ZQPei/deep_sort_pytorch still being actively maintained, noticed many of the issues raised weren't getting any attention.
