### ISSUE TITLE
self.min_confidence

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#262]
Thank you very much
YOLOv5 post-processing has confidence filtering and non-maximum suppression, and the specific values of these two parameters in your project are shown below, that is, the confidence is filtered when the confidence is less than 0.4 and the IOU is also filtered when the IOU is more than 0.5. The final output results of YOLOv5 are both greater than 0.4
![image](https://user-images.githubusercontent.com/83855363/147477919-9535e118-4ec2-489a-a420-417dd7841ccb.png)
However, here's what you do when you take the detection result as trace input in your code
![image](https://user-images.githubusercontent.com/83855363/147478533-9cd673b5-0869-46c1-a85d-3e77f4875e28.png)
self.min_confidence=0.4
As far as I know, the detection results are all higher than 0.4, so self.min_confidence above doesn't have any effect

**Comment by fengshuaibo** [comment]
Is this code used for YOLOv5 post-processing (i.e., confidence filtering and IOU processing)
pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, opt.classes, opt.agnostic_nms, max_det=opt.max_det)

**Comment by mikel-brostrom** [comment]
Thank you for pointing this out! The filtering by confidence in DeepSrot is not needed as it is already performed by Yolo. This is now deleted from DeepSort!
