### ISSUE TITLE
colab problem

### ISSUE THREAD

**Issue by chakloong883** [mikel-brostrom/Yolov5_DeepSort_Pytorch#263]
When I open your colab link and run the code,  it turns out this problem:
track.py: error: unrecognized arguments: --yolo_weights /content/Yolov5_DeepSort_Pytorch/yolov5/weights/crowdhuman_yolov5m.pt

**Comment by kadirnar** [comment]
I think you should do it.
```
python track.py --source video_path.mp4  --yolo_model yolov5/weights/crowdhuman_yolov5m.pt 
```

**Comment by mikel-brostrom** [comment]
Thank you for pointing this out.  Some argument names changed with the last refactoring. Now they should be updated on colab as well!
