### ISSUE TITLE
postprocess

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#264]
Is this code used for YOLOv5 post-processing (i.e., confidence filtering and IOU processing)
pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, opt.classes, opt.agnostic_nms, max_det=opt.max_det)

**Comment by mikel-brostrom** [comment]
Is this a question? Yes, `non_max_suppression` is used

**Comment by fengshuaibo** [comment]
YOLOv5 post-processing includes confidence processing and non-maximum suppression. Are both operations performed in the following function? And opt.conf_thres is the confidence threshold and opt.iou_thres is the overlap area threshold?
Pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, opt.classes, opt.agnostic_NMS, max_det=opt.max_det)
