### ISSUE TITLE
CUDA device not found on DJI Manifold 2 NVIDIA Jetson TX2 

### ISSUE THREAD

**Issue by fatbringer** [mikel-brostrom/Yolov5_DeepSort_Pytorch#265]
Hello, i got this error while trying to run your code on my DJI Manifold 2G which contains an NVIDIA Jetson Tx2
I was attempting to make it run faster, since it had originally said running on cpu before i noticed that i could append the "--device "" option 

Here is the error
```
Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Traceback (most recent call last):
  File "track.py", line 243, in <module>
    detect(opt)
  File "track.py", line 51, in detect
    device = select_device(opt.device)
  File "/media/dji/80GBstore/targetTrack/mikelbrostromNov2021/Yolov5_DeepSort_Pytorch/yolov5/utils/torch_utils.py", line 65, in select_device
    assert torch.cuda.is_available(), f'CUDA unavailable, invalid device {device} requested'  # check availability
AssertionError: CUDA unavailable, invalid device 0,1,2,3,4,5 requested
````

**Comment by mikel-brostrom** [comment]
The error is clear. You don't have CUDA installed

**Comment by fatbringer** [comment]
I actually have CUDA 9 installed 

```
/usr/local/cuda/samples/1_Utilities/deviceQuery$ ./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA Tegra X2"
  CUDA Driver Version / Runtime Version          9.0 / 9.0
  CUDA Capability Major/Minor version number:    6.2
  Total amount of global memory:                 7839 MBytes (8219348992 bytes)
  ( 2) Multiprocessors, (128) CUDA Cores/MP:     256 CUDA Cores
  GPU Max Clock rate:                            1301 MHz (1.30 GHz)
  Memory Clock rate:                             1600 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            Yes
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS
````

**Comment by mikel-brostrom** [comment]
That you `Detected 1 CUDA Capable device(s)` does not mean that you have the right driver to make use of it. The output is misleading. Specifically this part: `CUDA Driver Version / Runtime Version...`. If you have ubuntu, the easies way is: 

```bash
sudo ubuntu-drivers autoinstall
```

**Comment by fatbringer** [comment]
Hey there. I tried the command i got this instead
```
dji@manifold2:~$ sudo ubuntu-drivers autoinstall
No drivers found for automatic installation.
````
Is this then the CUDA version is not compatible with the torch version ?

**Comment by SinDongHwan** [comment]
Hi, @fatbringer
To run pytorch with gpu, re-install torch.
refer [this link](https://pytorch.org/)

**Comment by fatbringer** [comment]
@SinDongHwan hey thanks. But i have CUDA 9 only, will it affect the system ?

**Comment by SinDongHwan** [comment]
Hi, @fatbringer 
This repository should use  pytorch lib  over 1.7.0 version.
So, I recommend to upgrade cuda version over 10.1.

I think you should select one of following versions.

ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu112 (from versions: 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.1, 1.9.1+cpu, 1.9.1+cu102, 1.9.1+cu111, 1.10.0, 1.10.0+cpu, 1.10.0+cu102, 1.10.0+cu111, 1.10.0+cu113, 1.10.1, 1.10.1+cpu, 1.10.1+cu102, 1.10.1+cu111, 1.10.1+cu113)

if you use rtx 3000 serise graphic card, i recommend to install cuda 11.1 or 11.3.
if you want to use cuda 11.3, you can download "cuDNN 8.2.0 or 8.2.1 version for 11.x".

**Comment by fatbringer** [comment]
@SinDongHwan   Ah i am using a embedded computer which contains an NVIDIA Jetson TX2 instead of the usual rtx30xx series graphics card. I am trying to find how to upgrade the CUDA too to at least CUDA 10. But for now i am unable to

**Comment by SinDongHwan** [comment]
@fatbringer 
refer [this link](https://docs.nvidia.com/jetson/jetpack/install-jetpack/index.html).
or try to convert pytorch to onnx or tensorrt.

**Comment by fatbringer** [comment]
@SinDongHwan  visited the link you shared. That is for the newer version of Jetpack. I am currently unable to upgrade to a newer version of jetpack because of DJI's hardware problems. I have posted on their forums but no avail yet.
