### ISSUE TITLE
Question training on VisDrone dataset

### ISSUE THREAD

**Issue by HeChengHui** [mikel-brostrom/Yolov5_DeepSort_Pytorch#266]
I am trying to use this tracking algo in a drone setting and hence wanted to train it using VisDrone datasets. Before doing so, I would like to check if what I plan to do is correct.
1. Do I have to train models for both yolov5 and re-id (osnet-25)?
2. Since the crowdhuman model was recommended to track people, is it possible to further train that on vidrone dataset?

**Comment by mikel-brostrom** [comment]
> Do I have to train models for both yolov5 and re-id (osnet-25)?

Ideally, yes. Why? The top perspective of the camera implies that the physical appearance slightly change compared to COCO (which Yolo is trained on) and most of the ReID datasets.

> Since the crowdhuman model was recommended to track people, is it possible to further train that on vidrone dataset?

Yes, it is possible. If you want to train a ReID model on a custom dataset I recommend that you go through: https://kaiyangzhou.github.io/deep-person-reid/user_guide.html

**Comment by HeChengHui** [comment]
Thank you for the detailed explanation!

While looking through the yolov5 folder, I came across a YAML file that seems to help train yolov5 on visdrone dataset (yolov5\data\VisDrone.yaml).
Is it advisable to use that? And would training from scratch vs continue training from the crowdhuman model be better?

**Comment by mikel-brostrom** [comment]
> Is it advisable to use that?

If such a file exists in the original Yolov5 repo I suggest you to use that one

> And would training from scratch be better than continuing training with the crowdhuman model?

Training from scratch is very seldom better than continuing training from something. I would continue training from the models trained on COCO, the default ones provided by the Yolov5 repo. The reason for this is that they contain richer features (trained on 80 classes) compared the one trained only on crowd human (trained on persons)

**Comment by HeChengHui** [comment]
> Training from scratch is very seldom better than continuing training from something

My bad I meant between using the Yolo models (Yolov5s.pt is the default in the training code) and crowdhuman model provided.

**Comment by HeChengHui** [comment]
I managed to get the training code working and when I tried to train from the crowdhuman model, there was an error about the tensor size. I also asked about this in the yolov5 github and the responder seems to say it could be due to the model? Wonder if you know anything about this?

https://github.com/ultralytics/yolov5/issues/4585

**Comment by mikel-brostrom** [comment]
> My bad I meant between using the Yolo models (Yolov5s.pt is the default in the training code) and crowdhuman model provided.

Again. I would continue training from the models trained on COCO, the default ones provided by the Yolov5 repo. The reason for this is that they contain richer features (trained on 80 classes) compared the one trained only on crowd human (trained on persons)

> I managed to get the training code working and when I tried to train from the crowdhuman model, there was an error about the tensor size. I also asked about this in the yolov5 github and the responder seems to say it could be due to the model? Wonder if you know anything about this?

The architecture associated to the crowdhuman model could be an old one which the repo isn't supporting anymore. I suggest you to start from the models provided by the Yolov5 repo.

**Comment by HeChengHui** [comment]
Thank you for your suggestions. 
In the VisDrone dataset, there is also a MOT dataset in addition to a DET dataset which can be used to train the detector (yolov5 in this case). Should the reid  model be trained on the MOT dataset or something else?

**Comment by mikel-brostrom** [comment]
> Should the reid model be trained on the MOT dataset or something else?

Ideally you train a ReiD model on the data you focus on butYou won't be able to train a ReID model with a MOT dataset right away. You will need to process it accordingly.

**Comment by HeChengHui** [comment]
> you won't be able to train a ReID model with a MOT dataset right away. You will need to process it accordingly.

Is there any resources about this or is it better to ask at the torchreid repo? Which component of deepsort would train on a MOT dataset?

**Comment by mikel-brostrom** [comment]
You can read about the most well known ReID datasets here: https://kaiyangzhou.github.io/deep-person-reid/datasets.html. By downloading one of them you could check their structure and contents. If you need more help i suggest you to leave that question in the torch ReID repo where you will find more support.
