### ISSUE TITLE
why λ = 0? any thoughts or opinions?

### ISSUE THREAD

**Issue by MICHIokaGAN** [mikel-brostrom/Yolov5_DeepSort_Pytorch#268]
In the paper, it's reported that

> During our experiments we found that setting λ = 0 is a reasonable choice when there is substantial camera motion.

I understand that it's an empirical thing but any thoughts or opinions about why λ = 0 is the best choice?
It doesn't have to be a true fact.
I want to hear some opinions from you guys.
Please comment freely. 

Thanks in advance!

**Comment by mikel-brostrom** [comment]
I think that the important part of 

> During our experiments we found that setting λ = 0 is a reasonable choice when there is substantial camera motion.

is: 

> when there is substantial camera motion

The Mahalonobis distance is suitable when the motion uncertainty is low, but when there is: camera motion, occlusion, unaccounted frame skipping... the Mahalanobis distance is in the best case rather useless and in the worst case it can be harmful. Therefore they complement the motion metric with a visual metric.

So when the motions uncertainty is high, as when there is substantial camera movement, it hence make sense to set λ = 0 as this makes the tracking to not take into consideration the Mahalanobis distance at all.

**Comment by MICHIokaGAN** [comment]
I don't know why but I completely overlooked the
> when there is substantial camera motion
part.
Thank you so much for your reply!
