### ISSUE TITLE
from torchreid import models ModuleNotFoundError: No module named 'torchreid'

### ISSUE THREAD

**Issue by totoadel** [mikel-brostrom/Yolov5_DeepSort_Pytorch#269]
```
Traceback (most recent call last):
  File "track.py", line 30, in <module>
    from deep_sort.utils.parser import get_config
  File "E:\Python\Yolov5_DS2\deep_sort\__init__.py", line 1, in <module>
    from .deep_sort import DeepSort
  File "E:\Python\Yolov5_DS2\deep_sort\deep_sort.py", line 4, in <module>
    from .deep.feature_extractor import Extractor
  File "E:\Python\Yolov5_DS2\deep_sort\deep\feature_extractor.py", line 10, in <module>
    from torchreid import models
ModuleNotFoundError: No module named 'torchreid'
```

**Comment by totoadel** [comment]
sorry i found the error
i must download this repo
[](https://github.com/KaiyangZhou/deep-person-reid/tree/6987d99074fcc63146660b83b38218c37b4412b3)

**Comment by mikel-brostrom** [comment]
You forgot to run the clone command with the --recurse-submodules flag, like this:

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

as specified here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch#before-you-run-the-tracker

**Comment by shadfien** [comment]
> sorry i found the error i must download this repo [here](https://github.com/KaiyangZhou/deep-person-reid/tree/6987d99074fcc63146660b83b38218c37b4412b3)

Hi, I have the same question, after download this repo,what should i do?

**Comment by totoadel** [comment]
> > sorry i found the error i must download this repo [here](https://github.com/KaiyangZhou/deep-person-reid/tree/6987d99074fcc63146660b83b38218c37b4412b3)
> 
> Hi, I have the same question, after download this repo,what should i do?

Put it the folder inside the deep folder inside the deep sort folder , you will find a folder with the Same name
