### ISSUE TITLE
Performance questions

### ISSUE THREAD

**Issue by berkantay** [mikel-brostrom/Yolov5_DeepSort_Pytorch#27]
Hello Mike, thanks for the repository and implementation. I have trained my model on yolov5 for my custom object. And ran your track.py code  works fine. But there is one thing I want to ask. How big is the affect of trained model to the performance of the tracker? How can I improve the performance and accuracy of the tracker?

**Comment by mikel-brostrom** [comment]
Hi @berkantay,

I am glad you liked my repo! 

This is a two stage algorithm: first yolo extract objects of interest, in this case pedestrians; then, this objects are passed to deep sort which tracks them. You could boost the performance both by increasing the accuracy of yolov5 but also by training a better deep learning metric. 

You can make the experiment of training Yolov5s, Yolov5m and Yolov5l on your custom dataset and see how the different models affect the inference. The short answer is: Yolov5s < Yolov5m < Yolov5l < Yolov5x

The tracker is trickier as you would need a REID dataset for your objects of interest to train the deep learning metric on.

**Comment by berkantay** [comment]
Hello @mikel-brostrom I enhanced my training performance. Everything is perfect for detection, But there is one spot that needs to be clarified. Does the tracker needs training for what to track?

**Comment by mikel-brostrom** [comment]
Yes, Deep Sort extends the original [SORT](https://arxiv.org/pdf/1602.00763.pdf) to integrate appearance information based on a deep appearance descriptor. Hence the name, DEEP SORT. This appearance descriptor is given by a CNN model presented under Table 1 in the paper [DEEP SORT](https://arxiv.org/pdf/1703.07402.pdf). This model was trained on a [large-scale person re-identification dataset](https://arxiv.org/pdf/1809.02874.pdf) that contains over 1,100,000 images of 1,261 pedestrians, making it well suited for deep metric learning in a people tracking context.

Although this metric can be used for other objects that are not people, it may be far from optimal for the specific objects that you want to track. If you want to improve the performance of the tracker you could try to train that deep appearance descriptor on your custom REID dataset containing the objects you want to track
