### ISSUE TITLE
result video not saving?

### ISSUE THREAD

**Issue by DRiXD** [mikel-brostrom/Yolov5_DeepSort_Pytorch#271]
Hi all,

I tried to run the colab notebook. At the command 
!python track.py --yolo_model /content/Yolov5_DeepSort_Pytorch/yolov5/weights/crowdhuman_yolov5m.pt --source out.avi --output out/ --save-vid
It runs succesfully and prints: "Results saved to /content/Yolov5_DeepSort_Pytorch/out/" . But the video isnt there? I tried a few times now and also had alook into debugging the code (the save video step definitly gets executed)

Can anyone help here?

**Comment by mikel-brostrom** [comment]
That print statement has not been updated after the latest changes. Now it should specify the correct location

**Comment by DRiXD** [comment]
It does work now thank you for the fast response.
By the way in your Colab you also have to adjust the first Block under "Show the results" now to match the correct path I guess.

**Comment by unbeliveyu** [comment]
> It does work now thank you for the fast response. By the way in your Colab you also have to adjust the first Block under "Show the results" now to match the correct path I guess.



Excuse me, how did you solve this problem
