### ISSUE TITLE
 I use this order{ python3 track.py --source 0 --yolo_model yolov5/weights/crowdhuman_yolov5m.pt --classes 0  # tracks persons, only},  but   appear this problem

### ISSUE THREAD

**Issue by Bob-jpg** [mikel-brostrom/Yolov5_DeepSort_Pytorch#273]
![图片](https://user-images.githubusercontent.com/56429665/148896416-0d9a829e-edda-4f25-8bf9-de262a8b6168.png)

**Comment by echosalik** [comment]
If you are doing it over SSH you need to allow it to access X11, for example:

`ssh -X user@address`

or check `$DISPLAY` environment variable.
