### ISSUE TITLE
Question about tracking arguments

### ISSUE THREAD

**Issue by pasmai** [mikel-brostrom/Yolov5_DeepSort_Pytorch#274]
Is it correct that the DeepSort takes as argument the most recent detections. And for every detection it adds those to the list internal detections form deep_sort. 
And you can control how many are stored with the `max_age` parameter. Is the `max_age ` in number of detections or a time period?

**Comment by mikel-brostrom** [comment]
You have a short description about the relevant DeepSort hparams here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/master/deep_sort/configs/deep_sort.yaml

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/fe7b4e230b3c4518b064b31d3d0e3246c5f34c25/deep_sort/configs/deep_sort.yaml#L5

**Comment by pasmai** [comment]
Thanks, so is that 30 detections misses then?

**Comment by mikel-brostrom** [comment]
No, 30 association misses.

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/e43588593a93f9fa48d7a994ed9be9fa7f71b9f0/deep_sort/sort/track.py#L165-L171
