### ISSUE TITLE
How to draw Trackline？

### ISSUE THREAD

**Issue by XiangqingZhang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#276]
single class how to draw ？

**Comment by mikel-brostrom** [comment]
You have a solution here:
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/221

**Comment by XiangqingZhang** [comment]
@mikel-brostrom Thank you. I solved it.

**Comment by liang-jingyi** [comment]
@XiangqingZhang Please help me

**Comment by liang-jingyi** [comment]
@mikel-brostrom Can you tell me where to add the code in #221?How do I plot the trajectory
