### ISSUE TITLE
extract each frame?

### ISSUE THREAD

**Issue by yuzehui1996** [mikel-brostrom/Yolov5_DeepSort_Pytorch#28]
Hi,
Thanks for your repo!
When the video is very long, it is very time-consuming to extract and detect each frame.
Is it possible to detect at intervals of several frames？

**Comment by mikel-brostrom** [comment]
Hi,

I am glad you liked my repo!

There is no possibility of batch processing of multiple frames at the moment

**Comment by yuzehui1996** [comment]
I think you don't get my point.

**Comment by yuzehui1996** [comment]
I think you don't get my point.
In your code, every frame is extracted and then detected and tracked.

**Comment by yuzehui1996** [comment]
Thanks for your reply!
I think you don't get my point.
In your code, every frame is extracted and then detected and tracked.
What I want to know is that is it possible to extract every few frames and then detect and track, instead of extracting each frame from the video.
You know that when the video is too long, extracting each frame will be time-consuming.

**Comment by mikel-brostrom** [comment]
What you ask for is not possible at the moment.  That would cause problems when rebuilding the video with detections as the frame rate wouldn't be the same as the original video source. If you still want to do this you could just `continue` the `frame_idx, (path, img, im0s, vid_cap) in enumerate(dataset):` loop for a certain amount of frames

**Comment by gayatriprasad** [comment]
Hello, thank you for the wonderful repository. It is indeed very helpful. What if I want to just save the images for individual person/ID ? Can I increase the processing speed ?
