### ISSUE TITLE
post-processing

### ISSUE THREAD

**Issue by fengshuaibo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#280]
YOLOv5 post-processing includes confidence processing and non-maximum suppression. Are both operations performed in the following function? And opt.conf_thres is the confidence threshold and opt.iou_thres is the overlap area threshold?
Pred = non_max_suppression(pred, opt.conf_thres, opt.iou_thres, opt.classes, opt.agnostic_NMS, max_det=opt.max_det)

**Comment by mikel-brostrom** [comment]
I recommend you to leave all the Yolov5 related questions in the original repo: https://github.com/ultralytics/yolov5.
You will find more help there.
