### ISSUE TITLE
How to count objects crossing vertical line on conveyor belt 

### ISSUE THREAD

**Issue by zyakubova86** [mikel-brostrom/Yolov5_DeepSort_Pytorch#281]
**Hi!
How to implement counting custom objects moving horizontally on conveyor belt? Please, share your ideas.**

**Comment by mikel-brostrom** [comment]
There are plenty of ways of doing this. You have one way in this PR: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/pull/211
