### ISSUE TITLE
how to train "crowdhuman_yolov5m"

### ISSUE THREAD

**Issue by nomurakeiya** [mikel-brostrom/Yolov5_DeepSort_Pytorch#282]
Thanks for the great code and model! !!

I was surprised that the crowdhuman_yolov5m model detected people very accurately.

Can you tell me what kind of composition and how much you learned the image?

Thank you

**Comment by mikel-brostrom** [comment]
I used the model provided in this repo https://github.com/deepakcrk/yolov5-crowdhuman

> I was surprised that the crowdhuman_yolov5m model detected people very accurately.

I was also quite surprised :smile:

**Comment by nomurakeiya** [comment]
@mikel-brostrom 

Thank you for telling me the repository.

You were asking [here](https://github.com/deepakcrk/yolov5-crowdhuman/issues/10) too, but did you know what kind of image composition the trained model was?

Did he trained in something of a data set?
