### ISSUE TITLE
counter error

### ISSUE THREAD

**Issue by darko262** [mikel-brostrom/Yolov5_DeepSort_Pytorch#283]
Hello, I have a slight problem.
I am keeping track of my dataset which works fine, however it is sometimes wrong. for example it detects an object then after it jumps to 5 counted objects. How can i fix this? Any parameter to adjust?

**Comment by mikel-brostrom** [comment]
Hi! How do you count the objects?

**Comment by darko262** [comment]
I tried the track.py with my model to test the performance. The counter generated in the identification box is the one with problems
Counts more objects than found.

**Comment by mikel-brostrom** [comment]
You can try to count only the objects that ends up being tracked by DeepSort. In that way you will most certainly exclude false positives
