### ISSUE TITLE
The Detail implementation of DeepSort and YOLOv5 with track.py 

### ISSUE THREAD

**Issue by XiangqingZhang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#285]
I have changed the YOLOv5 algorithm partly, how do I replace the yolov5 method in your repository? and how can I modify the "track.py " file in detail? Looking forward to your reply!

**Comment by mikel-brostrom** [comment]
Just substitute the Yolov5 submodule by your custom Yolov5

**Comment by XiangqingZhang** [comment]
ok
