### ISSUE TITLE
import gdown error

### ISSUE THREAD

**Issue by zyakubova86** [mikel-brostrom/Yolov5_DeepSort_Pytorch#286]
When i try to run track.py this error is showing up. 

![image](https://user-images.githubusercontent.com/74640447/151121940-cdd8963d-79f4-4e4d-9d00-edb0bf139306.png)

**Comment by mikel-brostrom** [comment]
try `pip install gdown`

**Comment by zyakubova86** [comment]
> try `pip install gdown`

we need to add gdown and tensorboard to requirements.txt

**Comment by mikel-brostrom** [comment]
You can find all the needed packages under `requirements.txt`. Installed via pip as explained here:
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch#before-you-run-the-tracker
