### ISSUE TITLE
运行python3 track.py --source ... --save-txt时出现错误

### ISSUE THREAD

**Issue by sfx-666** [mikel-brostrom/Yolov5_DeepSort_Pytorch#287]
运行python3 track.py --source ... --save-txt时出现File "track.py", line 375, in <module>
    detect(args)
  File "track.py", line 305, in detect
    f.write(('%g ' * 10 + '\n') % (frame_idx + 1, id, bbox_left,bbox_top, bbox_w, bbox_h, -1, -1, -1, -1))  # label format
TypeError: must be real number, not builtin_function_or_method

**Comment by mikel-brostrom** [comment]
Closing this due to duplicated issue
