### ISSUE TITLE
When I run python3 track.py --source ... --save-txt，I get the error.

### ISSUE THREAD

**Issue by sfx-666** [mikel-brostrom/Yolov5_DeepSort_Pytorch#288]
When I run python3 track.py --source ... --save-txt，I get the error.File "track.py", line 375, in <module>
    detect(args)
  File "track.py", line 305, in detect
    f.write(('%g ' * 10 + '\n') % (frame_idx + 1, id, bbox_left,bbox_top, bbox_w, bbox_h, -1, -1, -1, -1))  # label format
TypeError: must be real number, not builtin_function_or_method

**Comment by mikel-brostrom** [comment]
Make sure that you fulfill everything under: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch#before-you-run-the-tracker. The CI pipeline shows that everything is working when fulfilling these requirements
