### ISSUE TITLE
该项目中又又yolov3又出现了yolov5

### ISSUE THREAD

**Issue by starsky68** [mikel-brostrom/Yolov5_DeepSort_Pytorch#29]
该项目中又又yolov3又出现了yolov5，请问，以那个为准，它们有些错乱。

**Comment by mikel-brostrom** [comment]
Sorry, what?

**Comment by starsky68** [comment]
> Sorry, what?

在该项目中，deep_sort/detector中有YOLOv3做检测器，然后，有出现了yolov5做检测器，问题没有，就是觉得，这样会有些错乱。

**Comment by mikel-brostrom** [comment]
Yes, this repo contains two other repositories as specified in the intro. From the deep_sort one i just extract the deep_sort part, so I just ignore the detector. And I use Ultralytics' Yolov5 for detections instead and connect both

**Comment by mikel-brostrom** [comment]
I cleaned-up the code under the deep_sort folder from which I deleted all the YOLOv3 stuff. Should be clearer now
