### ISSUE TITLE
Why is there a difference in the detection results?

### ISSUE THREAD

**Issue by nomurakeiya** [mikel-brostrom/Yolov5_DeepSort_Pytorch#290]
Thank you for answering many questions!

I'm trying the model of "crowdhuman_yolov5m.pt" that you taught me.

1. Use the same model "crowdhuman_yolov5m.pt".

2. Compare the case of detecting one image with [this source](https://github.com/deepakcrk/yolov5-crowdhuman) and the case of detecting a video with [your source](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch).

3.YOLOv5-DeepSort(your source) gives overwhelmingly better results.

Is that because YOLOv5_DeepSort complements something from the previous and next frames?

> result of https://github.com/deepakcrk/yolov5-crowdhuman (I made a video by detecting one image.)

https://user-images.githubusercontent.com/56009331/151685352-414cbea7-260b-4d95-af26-904171f085c5.mp4

> result of https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch

https://user-images.githubusercontent.com/56009331/151685380-8c77466d-2b75-4995-aaa7-a7576a7643ca.mp4

**Comment by mikel-brostrom** [comment]
> Thank you for answering many questions!

Glad I can help :smile: 

> Is that because YOLOv5_DeepSort complements something from the previous and next frames?

YOLOv5_DeepSort predicts the position of the object in the next frame and then matches the actual detections to these predictions by a metric that is comprised of two parts (in different proportion): location and visual appearance. This matchings provide the IDs, the first number you see on top of each of the bounding boxes. The rest is basically the same so I am not quite sure why the differences are so big in this case.

**Comment by nomurakeiya** [comment]
thank you!

"Matchings provide the IDs" is for identifying the same person, isn't it?

In YOLOv5_crowdhuman, the drawing of bbox is unstable and the size and position are different. In deepsort, if the bbox of the next frame is predicted from the bbox of the previous frame, it seems that the difference in accuracy can be explained.

**Comment by mikel-brostrom** [comment]
> "Matchings provide the IDs" is for identifying the same person, isn't it?

Yes

> In deepsort, if the bbox of the next frame is predicted from the bbox of the previous frame, it seems that the difference in accuracy can be explained.

Yes I am mixing up stuff here, sorry. You are right, if the predictor fails in the process of detecting an already existing object tracked by the tracker, its KF will estimate the position of its bbox making the results more stable. DeepSORT also sets  a minimum amount of associations before it creates a track for it. In practice, this means less amount of false positives.

Sweet video comparison by the way :+1:

**Comment by nomurakeiya** [comment]
@mikel-brostrom 

> DeepSORT also sets a minimum amount of associations before it creates a track for it. In practice, this means less amount of false positives.

I see, I was convinced!
thanks.
