### ISSUE TITLE
rtsp stream id or camera id

### ISSUE THREAD

**Issue by zyakubova86** [mikel-brostrom/Yolov5_DeepSort_Pytorch#293]
hi 

How can i get multiple rtsp stream camera IDs or ip camera IPs?

Thanks

**Comment by mikel-brostrom** [comment]
Try

`git checkout multi-video-tracking`

Then create a .txt file containing you stream sources

```
0
abc.mp4
```

finally you can run

python3 track.py --source streams.txt

**Comment by zyakubova86** [comment]
Thanks, Mikel
