### ISSUE TITLE
Save results failed, both in txt and vid

### ISSUE THREAD

**Issue by SuperbTUM** [mikel-brostrom/Yolov5_DeepSort_Pytorch#295]
Hi. I am using Debian 10. I strictly followed the instructions on the readme file. When I tried to execute the code with continuous image frames with the following command:
 `python track.py --source /path --img 1280 --yolo_model yolov5/weights/yolov5m6.pt --class 0 2 --save-txt --save-vid`
I got the error message saying `OpenCV: FFMPEG: tag 0x7634706d/'mp4v' is not supported with codec id 12 and format 'image2 / image2 sequence'`. 
Not knowing why. Besides, there is no text file saved. 
My OpenCV is 4.5.5.62, the latest one.

**Comment by mikel-brostrom** [comment]
I cannot reproduce this error with `opencv-python==4.5.5.62`. However, can you try to replace

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/e5d79a17d4c951fe1265470b1fc51f24a46e096e/track.py#L216

by 

`vid_writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'XVID'), fps, (w, h)) `

Let me know if this helps
