### ISSUE TITLE
Useable with own trained dataset?

### ISSUE THREAD

**Issue by flowzen1337** [mikel-brostrom/Yolov5_DeepSort_Pytorch#3]
Hi @mikel-brostrom 

thanks for your repository, I'll check it out tomorrow! :-)

One question, i've trained succesfully my own custom dataset with AlexeyAB's darknet implemenation of YoloV4.

I've got 90 classes, my weight file (After 200.000k training itterations) and my corresponding yolov4_custom.cfg file where classes=90 and the filters=285 set accordingly on each [convetional] layer before the 3x [yolo] layers.

Can i just pass my custom weights, cfg and the classes to your deep sort python implemenation (which parameters do i have to provide when i run your python script for that task?) or is it strict only for the coco dataset with the weight, cfg etc. you provide in this repo?

Thanks for your time! :-)
Cheers

**Comment by mikel-brostrom** [comment]
Hi,

Thank you for showing interest in my repository!

You cannot pass your custom weights, cfg and classes to Yolov5 as the implementations differs greatly.You would need to train Ultralytics' Yolov5 and use those weights.
