### ISSUE TITLE
Can DeepSort model be converted to tensorrt for reference？

### ISSUE THREAD

**Issue by shliang0603** [mikel-brostrom/Yolov5_DeepSort_Pytorch#30]

**Comment by shliang0603** [comment]
@mikel-brostrom Hi,  Can DeepSort model be converted to tensorrt for reference？If it can be converted, how should it be realized? I tried it but failed

**Comment by mikel-brostrom** [comment]
I haven't tried it myself but deep sort is just comprised of convolutional layers followed by residual blocks and a dense layer so it should be straight forward to serialize

**Comment by Wulingtian** [comment]
我试了yolov5_deepsort的tensorrt版本，大概15ms一帧
