### ISSUE TITLE
deep

### ISSUE THREAD

**Issue by liang-jingyi** [mikel-brostrom/Yolov5_DeepSort_Pytorch#300]
My improved YoloV5 network can only use the V6 version of YoloV5. However, DeepSort uses an older version. What should I do to use V6?Please help me，Thank you

**Comment by mikel-brostrom** [comment]
The gitmodule is pointing to V6. Hence this:

> My improved YoloV5 network can only use the V6 version of YoloV5. However, DeepSort uses an older version

is incorrect

**Comment by liang-jingyi** [comment]
Thank you very much for your reply! Sorry for the wrong description, I used V3 version instead of V4 version you released. Do you mean the latest deepSort V4 version uses yolov5 V6?

**Comment by mikel-brostrom** [comment]
> Do you mean the latest deepSort V4 version uses yolov5 V6?

Yes
