### ISSUE TITLE
There was an error when I ran track.py

### ISSUE THREAD

**Issue by liang-jingyi** [mikel-brostrom/Yolov5_DeepSort_Pytorch#301]
![NDC~O FW$OCIWG5GUCVK7LT](https://user-images.githubusercontent.com/56117520/153991755-b89e471c-f9bd-4e95-85e8-fe5655faab5a.png)

**Comment by liang-jingyi** [comment]
An error was reported at runtime.

**Comment by mikel-brostrom** [comment]
It seems to me that you have not cloned the repo recursively:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch#before-you-run-the-tracker

I have to warn you. This piece of software has never been tested on windows.
