### ISSUE TITLE
How Can I select yolov5 5.0 version

### ISSUE THREAD

**Issue by XiangqingZhang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#302]

**Comment by mikel-brostrom** [comment]
You need to change the commit that the submodule is pointing to

```bash
cd yolov5
git checkout f5b8f7d54c9fa69210da0177fec7ac2d9e4a627c  # this change the HEAD to point at Yolov5 v5.0
```

**Comment by XiangqingZhang** [comment]
> You need to change the commit that the submodule is pointing to
> 
> ```shell
> cd yolov5
> git checkout f5b8f7d54c9fa69210da0177fec7ac2d9e4a627c  # this change the HEAD to point at Yolov5 v5.0
> ```

Thanks for your timely reply . I changed the version of yolov5, but how to update the track.py ，This error like this：
![image](https://user-images.githubusercontent.com/22740766/154180219-c6fbf8cd-73f3-43a8-8275-e7392624f141.png)

**Comment by xinli-cm** [comment]
> 

This is due to the changes on yolov5 source code. You have to manually fix these modifications.
