### ISSUE TITLE
 I Just want to know  What is the effect of each one?

### ISSUE THREAD

**Issue by totoadel** [mikel-brostrom/Yolov5_DeepSort_Pytorch#303]
HI , I Just want to know  What is the effect of each one?
what distance means ?
DEEPSORT:
  MODEL_TYPE: "osnet_x_25"
  MAX_DIST: 0.2 # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.7 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 30 # Maximum number of missed misses before a track is deleted
  N_INIT: 3 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100 # Maximum size of the appearance descriptors gallery

**Comment by mikel-brostrom** [comment]
If the comment is not telling you enough I recommend you to explore by yourself. It will be more valuable than any explanation I could provide

**Comment by totoadel** [comment]
@mikel-brostrom sorry .
