### ISSUE TITLE
Cannot call device to detect

### ISSUE THREAD

**Issue by XiongAn01** [mikel-brostrom/Yolov5_DeepSort_Pytorch#304]
Model path：
![1111](https://user-images.githubusercontent.com/37887040/154193765-75f48e45-ccb1-4bec-8dcc-eb7b5f8790be.png)

Log：
![2222](https://user-images.githubusercontent.com/37887040/154193719-5369b59f-03fc-41d1-a2c2-04c5baeef933.png)
![3333](https://user-images.githubusercontent.com/37887040/154193744-0a523e47-c9ae-4c86-b900-bc35232fcf0e.png)

**Comment by mikel-brostrom** [comment]
google drive may not be available from china
