### ISSUE TITLE
When I run python track.py --source 0 I get an error

### ISSUE THREAD

**Issue by liang-jingyi** [mikel-brostrom/Yolov5_DeepSort_Pytorch#308]
![1645081711(1)](https://user-images.githubusercontent.com/56117520/154423596-3735000f-9a12-4db3-b535-4b9bdd348be6.png)

**Comment by liang-jingyi** [comment]
![1645081757(1)](https://user-images.githubusercontent.com/56117520/154423695-b7e6ba03-8334-414e-9a03-67bdd8b9f202.png)

**Comment by liang-jingyi** [comment]
![1645081794](https://user-images.githubusercontent.com/56117520/154423782-74b265aa-ca92-4a67-939c-0b56d517d5e8.png)

**Comment by liang-jingyi** [comment]
![1645081833(1)](https://user-images.githubusercontent.com/56117520/154423857-10aacf45-7a7f-4f25-ae50-02e107062dc6.png)

**Comment by liang-jingyi** [comment]
![1645081866(1)](https://user-images.githubusercontent.com/56117520/154423927-4e7d4710-d4c8-45a4-b8d6-f81375a59c9c.png)

**Comment by liang-jingyi** [comment]
![1645081907(1)](https://user-images.githubusercontent.com/56117520/154424024-dc5326b7-f910-4168-80a6-688744c34ccd.png)

**Comment by liang-jingyi** [comment]
![1645081934(1)](https://user-images.githubusercontent.com/56117520/154424078-92789260-b599-41e6-b49f-e1103dba5a8a.png)

**Comment by liang-jingyi** [comment]
![1645081997(1)](https://user-images.githubusercontent.com/56117520/154424231-8e9fa217-0246-4996-9c38-61a8daa31d89.png)

**Comment by liang-jingyi** [comment]
![1645082033(1)](https://user-images.githubusercontent.com/56117520/154424317-32032076-9bf0-4b74-8225-bf247a841410.png)

**Comment by liang-jingyi** [comment]
I went according to the steps and got such a mistake. How to solve it

**Comment by zxy-0812** [comment]
Hi, I have the same problem as you, can you tell me how you solved it?

**Comment by unbeliveyu** [comment]
> I went according to the steps and got such a mistake. How to solve it？

Hi, I have the same problem as you, can you tell me how you solved it?
