### ISSUE TITLE
Question: Difference in re-id performance between old ckpt7 and osnet_x_25 ? and parsing a config file for classes into track.py ?

### ISSUE THREAD

**Issue by fatbringer** [mikel-brostrom/Yolov5_DeepSort_Pytorch#309]
Hello ! I have a question regarding the difference in re-id performance between the previously used ckptt7 and the currently used osnet_x_25. 

1) Could you please share the rationale for the change ?
2) Also, understand that previously the deep_sort.yaml had a variable for min_confidence. This seems to be gone in the newer deep_sort.yaml file. May I know where can we adjust this setting now ? 

3) I would like to run track.py but have a config file supply the arguments. I tried using parser.get, which returns a string. Which causes me to run into an error. I understand that from terminal, you could specify ``` classes 0 1 2 3 ``` and it would work fine. 
``` /yolov5/utils/general.py", line 698, in non_max_suppression
    x = x[(x[:, 5:6] == torch.tensor(classes, device=x.device)).any(1)]
TypeError: new(): invalid data type 'str'
```
Is a list of integers compatible with this ? i.e. i should convert the string (which is ```0, 1, 2, 3 ```) into a list of ints ?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/wiki/Evaluation (.ckpt7)
vs
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/313 (osnet_x_25)

> Could you please share the rationale for the change ?

To match people and distinguish them from impostors, features corresponding small local regions (e.g. shoes, glasses) and
global whole body regions are equally important. This was not captured in (.ckpt7)

> Also, understand that previously the deep_sort.yaml had a variable for min_confidence. This seems to be gone in the newer deep_sort.yaml file. May I know where can we adjust this setting now ?

according to https://github.com/nwojke/deep_sort/blob/280b8bdb255f223813ff4a8679f3e1321b08cdfc/deep_sort_app.py#L143
```
min_confidence : float
        Detection confidence threshold. Disregard all detections that have
        a confidence lower than this value.
```

this is already taken care by Yolo

**Comment by fatbringer** [comment]
@mikel-brostrom alright i see. Thanks for explaining the difference between ckpt7 and osnet25. I notice that when using osnet25, when i just turn to show my side profile to the camera, i am assigned a different id from when i am facing the camera directly. Ckpt7 seems to be able to identify the same person. 

Is this an effect of the said change ? 

Also, from the model zoo, 


Ok I have managed to get the list of integers for the class to work as well. Thank you.

**Comment by mikel-brostrom** [comment]
Taking into consideration that almost all models under: https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.html are based on euclidean distance I would say it is safe to say that euclidean distance performs better. However that is a question for this repo: https://github.com/KaiyangZhou/deep-person-reid
