### ISSUE TITLE
RuntimeError: Expected object of scalar type struct c10::Half but got scalar type float for sequence element 2.

### ISSUE THREAD

**Issue by dengxuankun** [mikel-brostrom/Yolov5_DeepSort_Pytorch#31]
Yolov5_DeepSort_Pytorch\yolov5\utils\general.py", line 630, in non_max_suppression
    x = torch.cat((box[i], x[i, j + 5, None], j[:, None].float()), 1)
RuntimeError: Expected object of scalar type struct c10::Half but got scalar type float for sequence element 2.

**Comment by mikel-brostrom** [comment]
Make sure that you meet all dependency requirements. If in doubt, create a new virtual Python 3.8 environment, clone the latest repo and `pip install -r requirements.txt`
