### ISSUE TITLE
Delay/Lag in real time stream

### ISSUE THREAD

**Issue by gfleg77** [mikel-brostrom/Yolov5_DeepSort_Pytorch#312]
There is a delay/lag between the output and the actual stream. When starting to detect-tracking objects the lag increases can reach up to 20 seconds. My GPU load is only 40% running detection on 15FPS from camera rtsp stream. I think you should use multithreading.

**Comment by mikel-brostrom** [comment]
Feel free to submit a PR to solve this!

**Comment by vishyVishal** [comment]
May I know if this issue is resolved?
