### ISSUE TITLE
I used two different model weights, and I ran the eval.sh file. I got the same two evaluations

### ISSUE THREAD

**Issue by liang-jingyi** [mikel-brostrom/Yolov5_DeepSort_Pytorch#313]
Evaluating ch_yolov5m_deep_sort

    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.3986 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4142 sec
    CLEAR.eval_sequence()                                                  0.1181 sec
    Identity.eval_sequence()                                               0.0189 sec
    Count.eval_sequence()                                                  0.0000 sec
1 eval_sequence(MOT16-02, ch_yolov5m_deep_sort)                          0.9544 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-04)     1.4155 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.8502 sec
    CLEAR.eval_sequence()                                                  0.2638 sec
    Identity.eval_sequence()                                               0.0354 sec
    Count.eval_sequence()                                                  0.0000 sec
2 eval_sequence(MOT16-04, ch_yolov5m_deep_sort)                          2.5745 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-05)     0.1946 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4567 sec
    CLEAR.eval_sequence()                                                  0.1318 sec
    Identity.eval_sequence()                                               0.0214 sec
    Count.eval_sequence()                                                  0.0000 sec
3 eval_sequence(MOT16-05, ch_yolov5m_deep_sort)                          0.8120 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-09)     0.1831 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.3084 sec
    CLEAR.eval_sequence()                                                  0.0786 sec
    Identity.eval_sequence()                                               0.0093 sec
    Count.eval_sequence()                                                  0.0000 sec
4 eval_sequence(MOT16-09, ch_yolov5m_deep_sort)                          0.5832 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-10)     0.2463 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.3749 sec
    CLEAR.eval_sequence()                                                  0.1235 sec
    Identity.eval_sequence()                                               0.0108 sec
    Count.eval_sequence()                                                  0.0000 sec
5 eval_sequence(MOT16-10, ch_yolov5m_deep_sort)                          0.7594 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-11)     0.2213 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4973 sec
    CLEAR.eval_sequence()                                                  0.1329 sec
    Identity.eval_sequence()                                               0.0162 sec
    Count.eval_sequence()                                                  0.0000 sec
6 eval_sequence(MOT16-11, ch_yolov5m_deep_sort)                          0.8738 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-13)     0.2492 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4239 sec
    CLEAR.eval_sequence()                                                  0.1154 sec
    Identity.eval_sequence()                                               0.0150 sec
    Count.eval_sequence()                                                  0.0000 sec
7 eval_sequence(MOT16-13, ch_yolov5m_deep_sort)                          0.8082 sec

All sequences for ch_yolov5m_deep_sort finished in 7.37 seconds

CLEAR: ch_yolov5m_deep_sort-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT16-02                           40.677    91.743    40.778    41.317    98.714    20.37     40.741    38.889    37.266    7368      10465     96        18        11        22        21        19        
MOT16-04                           65.656    90.874    65.685    65.797    99.831    34.94     36.145    28.916    59.651    31291     16266     53        14        29        30        24        18        
MOT16-05                           55.471    85.627    55.749    62.027    90.81     27.2      49.6      23.2      46.556    4229      2589      428       19        34        62        29        30        
MOT16-09                           74.035    89.755    74.13     76.622    96.85     56        40        4         66.185    4028      1229      131       5         14        10        1         6         
MOT16-10                           62.088    85.56     62.34     66.935    93.576    40.741    46.296    12.963    52.422    8245      4073      566       31        22        25        7         78        
MOT16-11                           64.214    92.027    64.312    66.961    96.195    27.536    49.275    23.188    58.876    6143      3031      243       9         19        34        16        14        
MOT16-13                           51.729    87.662    51.956    53.878    96.557    28.972    40.187    30.841    45.082    6169      5281      220       26        31        43        33        34        
COMBINED                           59.429    89.735    59.54     61.113    97.49     30.948    43.714    25.338    53.156    67473     42934     1737      122       160       226       131       199       

Identity: ch_yolov5m_deep_sort-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT16-02                           50.045    35.496    84.807    6330      11503     1134      
MOT16-04                           75.348    62.504    94.835    29725     17832     1619      
MOT16-05                           63.808    53.696    78.613    3661      3157      996       
MOT16-09                           77.889    69.755    88.17     3667      1590      492       
MOT16-10                           69.052    59.222    82.794    7295      5023      1516      
MOT16-11                           70.334    59.647    85.687    5472      3702      914       
MOT16-13                           58.972    45.939    82.329    5260      6190      1129      
COMBINED                           68.379    55.621    88.73     61410     48997     7800      

Count: ch_yolov5m_deep_sort-pedestrianDets      GT_Dets   IDs       GT_IDs    
MOT16-02                           7464      17833     47        54        
MOT16-04                           31344     47557     72        83        
MOT16-05                           4657      6818      76        125       
MOT16-09                           4159      5257      22        25        
MOT16-10                           8811      12318     58        54        
MOT16-11                           6386      9174      56        69        
MOT16-13                           6389      11450     73        107       
COMBINED                           69210     110407    404       517       

Timing analysis:
MotChallenge2DBox.get_raw_seq_data                                     2.9086 sec
MotChallenge2DBox.get_preprocessed_seq_data                            3.3256 sec
CLEAR.eval_sequence                                                    0.9641 sec
Identity.eval_sequence                                                 0.1270 sec
Count.eval_sequence                                                    0.0000 sec
eval_sequence                                                          7.3654 sec
Evaluator.evaluate                                                     7.3683 sec

**Comment by liang-jingyi** [comment]
Evaluating ch_yolov5m_deep_sort

    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.4098 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4253 sec
    CLEAR.eval_sequence()                                                  0.1318 sec
    Identity.eval_sequence()                                               0.0148 sec
    Count.eval_sequence()                                                  0.0000 sec
1 eval_sequence(MOT16-02, ch_yolov5m_deep_sort)                          0.9860 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-04)     1.4646 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.8255 sec
    CLEAR.eval_sequence()                                                  0.2639 sec
    Identity.eval_sequence()                                               0.0334 sec
    Count.eval_sequence()                                                  0.0000 sec
2 eval_sequence(MOT16-04, ch_yolov5m_deep_sort)                          2.5957 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-05)     0.2469 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4459 sec
    CLEAR.eval_sequence()                                                  0.1171 sec
    Identity.eval_sequence()                                               0.0165 sec
    Count.eval_sequence()                                                  0.0000 sec
3 eval_sequence(MOT16-05, ch_yolov5m_deep_sort)                          0.8322 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-09)     0.1430 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.2761 sec
    CLEAR.eval_sequence()                                                  0.0731 sec
    Identity.eval_sequence()                                               0.0093 sec
    Count.eval_sequence()                                                  0.0000 sec
4 eval_sequence(MOT16-09, ch_yolov5m_deep_sort)                          0.5050 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-10)     0.2461 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.3524 sec
    CLEAR.eval_sequence()                                                  0.1030 sec
    Identity.eval_sequence()                                               0.0135 sec
    Count.eval_sequence()                                                  0.0000 sec
5 eval_sequence(MOT16-10, ch_yolov5m_deep_sort)                          0.7196 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-11)     0.2461 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.5305 sec
    CLEAR.eval_sequence()                                                  0.1566 sec
    Identity.eval_sequence()                                               0.0235 sec
    Count.eval_sequence()                                                  0.0000 sec
6 eval_sequence(MOT16-11, ch_yolov5m_deep_sort)                          0.9634 sec
    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-13)     0.3009 sec
    MotChallenge2DBox.get_preprocessed_seq_data(pedestrian)                0.4315 sec
    CLEAR.eval_sequence()                                                  0.1287 sec
    Identity.eval_sequence()                                               0.0180 sec
    Count.eval_sequence()                                                  0.0000 sec
7 eval_sequence(MOT16-13, ch_yolov5m_deep_sort)                          0.8849 sec

All sequences for ch_yolov5m_deep_sort finished in 7.49 seconds

CLEAR: ch_yolov5m_deep_sort-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT16-02                           40.677    91.743    40.778    41.317    98.714    20.37     40.741    38.889    37.266    7368      10465     96        18        11        22        21        19        
MOT16-04                           65.656    90.874    65.685    65.797    99.831    34.94     36.145    28.916    59.651    31291     16266     53        14        29        30        24        18        
MOT16-05                           55.471    85.627    55.749    62.027    90.81     27.2      49.6      23.2      46.556    4229      2589      428       19        34        62        29        30        
MOT16-09                           74.035    89.755    74.13     76.622    96.85     56        40        4         66.185    4028      1229      131       5         14        10        1         6         
MOT16-10                           62.088    85.56     62.34     66.935    93.576    40.741    46.296    12.963    52.422    8245      4073      566       31        22        25        7         78        
MOT16-11                           64.214    92.027    64.312    66.961    96.195    27.536    49.275    23.188    58.876    6143      3031      243       9         19        34        16        14        
MOT16-13                           51.729    87.662    51.956    53.878    96.557    28.972    40.187    30.841    45.082    6169      5281      220       26        31        43        33        34        
COMBINED                           59.429    89.735    59.54     61.113    97.49     30.948    43.714    25.338    53.156    67473     42934     1737      122       160       226       131       199       

Identity: ch_yolov5m_deep_sort-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT16-02                           50.045    35.496    84.807    6330      11503     1134      
MOT16-04                           75.348    62.504    94.835    29725     17832     1619      
MOT16-05                           63.808    53.696    78.613    3661      3157      996       
MOT16-09                           77.889    69.755    88.17     3667      1590      492       
MOT16-10                           69.052    59.222    82.794    7295      5023      1516      
MOT16-11                           70.334    59.647    85.687    5472      3702      914       
MOT16-13                           58.972    45.939    82.329    5260      6190      1129      
COMBINED                           68.379    55.621    88.73     61410     48997     7800      

Count: ch_yolov5m_deep_sort-pedestrianDets      GT_Dets   IDs       GT_IDs    
MOT16-02                           7464      17833     47        54        
MOT16-04                           31344     47557     72        83        
MOT16-05                           4657      6818      76        125       
MOT16-09                           4159      5257      22        25        
MOT16-10                           8811      12318     58        54        
MOT16-11                           6386      9174      56        69        
MOT16-13                           6389      11450     73        107       
COMBINED                           69210     110407    404       517       

Timing analysis:
MotChallenge2DBox.get_raw_seq_data                                     3.0574 sec
MotChallenge2DBox.get_preprocessed_seq_data                            3.2872 sec
CLEAR.eval_sequence                                                    0.9742 sec
Identity.eval_sequence                                                 0.1291 sec
Count.eval_sequence                                                    0.0000 sec
eval_sequence                                                          7.4869 sec
Evaluator.evaluate                                                     7.4899 sec

**Comment by liang-jingyi** [comment]
When I use yolov5m_crowdhuman.pt, I get the same result. Why?

**Comment by mikel-brostrom** [comment]
I don't understand your question? Did you modify https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/MOT16_eval/eval.sh?

**Comment by liang-jingyi** [comment]
@mikel-brostrom I modified the eval. Sh file every time I ran it.I just replaced the weight.pt file.

**Comment by liang-jingyi** [comment]
#!/bin/bash  set +e   # start from clean slate for i in data.zip MOT16.zip do  zip -T $i  if [ $? -eq 0 ]  then   echo 'zip is ok'     else   echo 'zip corrupted, deleting'   rm -rf $i  fi done   # create output folder if it doesn't exist if [ ! -d ~/Yolov5_DeepSort_Pytorch/inference/output ] then  mkdir -p ~/Yolov5_DeepSort_Pytorch/inference/output  echo 'inference output folder created' fi    # clone evaluation repo if it does not exist if [ ! -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval ] then  echo 'Cloning official MOT16 evaluation repo'  git clone https://github.com/JonathonLuiten/TrackEval ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval  # download quick start data folder if it does not exist  if [ ! -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data ]  then   # download data   wget -nc https://omnomnom.vision.rwth-aachen.de/data/TrackEval/data.zip -O ~/Yolov5_DeepSort_Pytorch/data.zip   # unzip   unzip -q ~/Yolov5_DeepSort_Pytorch/data.zip -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/   # delete zip   #rm data.zip  fi fi   # create MOT16 folder if it doesn't exist if [ ! -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16 ] then  mkdir -p ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16 fi   # if MOT16 data not unziped, then download, unzip and lastly remove zip MOT16 data if [[ ! -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train ]] && [[ ! -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/test ]] then  # download data  wget -nc https://motchallenge.net/data/MOT16.zip -O ~/Yolov5_DeepSort_Pytorch/MOT16.zip  # unzip     unzip -q MOT16.zip -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/  # delete zip  #rm MOT16.zip fi   # create folder to place tracking results for this method mkdir -p ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/trackers/mot_challenge/MOT16-train/ch_yolov5m_deep_sort/data/  # inference on 4 MOT16 video sequences at the same time # suits a 4GB GRAM GPU, feel free to increase if you have more memory N=1  # generate tracking results for each sequence for i in MOT16-02 MOT16-04 MOT16-05 MOT16-09 MOT16-10 MOT16-11 MOT16-13  do  (   # change name to inference source so that each thread write to its own .txt file   if [ ! -d ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train/$i/$i ]   then    mv ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train/$i/img1/ ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train/$i/$i   fi   # run inference on sequence frames   python3 track.py --source ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train/$i/$i --save-txt --evaluate --yolo_model yolov5/weights/yolo3.pt --classes 0 --exist-ok      # move generated results to evaluation repo  ) &  # https://unix.stackexchange.com/questions/103920/parallelize-a-bash-for-loop  # allow to execute up to $N jobs in parallel     if [[ $(jobs -r -p | wc -l) -ge $N ]]  then         # now there are $N jobs already running, so wait here for any job         # to be finished so there is a place to start next one.         wait -n     fi done  # no more jobs to be started but wait for pending jobs # (all need to be finished) wait echo "Inference on all MOT16 sequences DONE"  echo "Moving data from experiment folder to MOT16" mv ~/Yolov5_DeepSort_Pytorch/runs/track/exp/* \    ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/trackers/mot_challenge/MOT16-train/ch_yolov5m_deep_sort/data/  # run the evaluation python ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py --BENCHMARK MOT16 \  --TRACKERS_TO_EVAL ch_yolov5m_deep_sort --SPLIT_TO_EVAL train --METRICS CLEAR Identity \  --USE_PARALLEL False --NUM_PARALLEL_CORES 4

**Comment by mikel-brostrom** [comment]
Did you delete the results

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/42e4a8f537d840ac14509af03d586c14a2dc6960/MOT16_eval/eval.sh#L68

 before running it the second time? I am not sure that they get deleted automatically

**Comment by mikel-brostrom** [comment]
Did you train your own model on the CrowdHuman dataset @liang-jingyi ?

**Comment by liang-jingyi** [comment]
Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/trackers/mot_challenge/MOT16-train/ch_yolov5m_deep_sort/data/
This path file is empty
I trained my model on the COCO dataset.
And I used crowdhuman_yolov5m.pt that you provided
The evaluation results of the three models were the same

**Comment by liang-jingyi** [comment]
I used two models I trained and a crowdhuman_yolov5m.pt and got the same results.
So I don't understand why

**Comment by mikel-brostrom** [comment]
Then something went wrong. I get ~40MOTA on the COCO model. ~57 on the crowd human model

**Comment by liang-jingyi** [comment]
![5bb78d1ce4aa4320f040030608d3216](https://user-images.githubusercontent.com/56117520/155276356-83cb0b36-7d81-4909-8a80-cc2562f04e3a.png)

**Comment by mikel-brostrom** [comment]
> I used two models I trained and a crowdhuman_yolov5m.pt and got the same results.
> So I don't understand why

I see the problem. I do not know exactly what could have caused this. If you get the same results you must be evaluating on the same results files, that is quite clear to me

**Comment by liang-jingyi** [comment]
![2fce003c59172e9207be84bfcf2aeb1](https://user-images.githubusercontent.com/56117520/155281082-003f5d44-d3c4-468d-a045-fcfdf432cdf7.png)

**Comment by liang-jingyi** [comment]
I re-simulated the steps of my code.When I made this mistake，I put in the files in the data.zip and get the same result. 
I know where the error is, but how to put the results of the test in ch_yolov5m_deep_sort/data/
What parts of eval. shshould I modify?

**Comment by mikel-brostrom** [comment]
That data is generated in this for loop: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/42e4a8f537d840ac14509af03d586c14a2dc6960/MOT16_eval/eval.sh#L84

**Comment by liang-jingyi** [comment]
@mikel-brostrom Thank you very much. I have solved the problem

**Comment by mikel-brostrom** [comment]
Could you post the results here? :smile:

**Comment by liang-jingyi** [comment]
@mikel-brostrom I was late replying.Because I'm using a lightweight network, the results aren't great.

**Comment by liang-jingyi** [comment]
yolov4-tiny

CLEAR: ch_yolov5m_deep_sort-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT16-02                           15.836    75.914    16.228    21.713    79.835    11.111    24.074    64.815    10.606    3872      13961     978       70        6         13        35        181       
MOT16-04                           34.054    76.582    34.426    40.577    86.837    10.843    45.783    43.373    24.551    19297     28260     2925      177       9         38        36        581       
MOT16-05                           42.256    73.875    43.576    53.036    84.863    12        63.2      24.8      28.4      3616      3202      645       90        15        79        31        238       
MOT16-09                           50.01     78.984    51.645    64.124    83.71     36        52        12        36.533    3371      1886      656       86        9         13        3         171       
MOT16-10                           30.102    73.966    31.133    37.133    86.091    12.963    35.185    51.852    20.435    4574      7744      739       127       7         19        28        315       
MOT16-11                           49.226    82.201    49.695    59.254    86.108    21.739    33.333    44.928    38.679    5436      3738      877       43        15        23        31        139       
MOT16-13                           19.991    72.186    20.367    24.515    85.527    10.28     29.907    59.813    13.172    2807      8643      475       43        11        32        64        211       
COMBINED                           31.739    76.627    32.315    38.922    85.488    13.926    41.973    44.101    22.642    42973     67434     7295      636       72        217       228       1836

**Comment by liang-jingyi** [comment]
Yolov4-tiny improved network
CLEAR: ch_yolov5m_deep_sort-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT16-02                           19.514    76.121    20.21     27.309    79.368    12.963    31.481    55.556    12.993    4870      12963     1266      124       7         17        30        290       
MOT16-04                           39.483    76.95     39.738    43.815    91.487    10.843    49.398    39.759    29.384    20837     26720     1939      121       9         41        33        625       
MOT16-05                           49.633    74.852    50.763    60.443    86.195    19.2      58.4      22.4      34.433    4121      2697      660       77        24        73        28        209       
MOT16-09                           53.738    79.837    54.955    66.977    84.782    36        52        12        40.233    3521      1736      632       64        9         13        3         141       
MOT16-10                           32.992    73.365    34.226    45.056    80.622    16.667    38.889    44.444    20.992    5550      6768      1334      152       9         21        24        394       
MOT16-11                           50.512    82.156    50.796    61.761    84.922    24.638    31.884    43.478    39.491    5666      3508      1006      26        17        22        30        84        
MOT16-13                           23.668    72.823    24.419    31.328    81.932    13.084    33.645    53.271    15.154    3587      7863      791       86        14        36        57        252       
COMBINED                           36.115    76.79     36.704    43.613    86.325    17.215    43.133    39.652    25.993    48152     62255     7628      650       89        223       205       1995

**Comment by mikel-brostrom** [comment]
Thx you for sharing!

**Comment by mikel-brostrom** [comment]
How did you solve the issue?

**Comment by liang-jingyi** [comment]
@mikel-brostrom 
I found that the TXT file eval.sh evaluated MOT16 was not formatted correctly.
So I run the following command：

python3 track.py --source ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/MOT16/train/$i/$i --save-txt --yolo_model yolov5/weights/crowdhuman_yolov5m.pt --classes 0

Will get TXT file into the following path ：

Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/trackers/mot_challenge/MOT16 - train/ch_yolov5m_deep_sort /data/

Solved the problem.
