### ISSUE TITLE
which ReID model is better for person detection+track？

### ISSUE THREAD

**Issue by XiangqingZhang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#316]
Hi, have you tried to test Reid model, I want to track person only, select which one is better?
![image](https://user-images.githubusercontent.com/22740766/155846348-4bd54b32-fdf0-460a-b14b-88bf3a54d583.png)

**Comment by plusleft** [comment]
I have the same problem as you, have you solved it?

**Comment by plusleft** [comment]
Modifying the path can solve this problem。

**Comment by mikel-brostrom** [comment]
Hi @XiangqingZhang,

It depends on what your needs are. According to https://arxiv.org/pdf/1905.00953.pdf, the best model for same-domain ReID is OSNet with β=1. It gives

| R1 | mAP |
| ------------- | ------------- |
| 94.8 | 84.9  |

β=0.25 yields a x10 smaller model with a competitive result

| R1 | mAP |
| ------------- | ------------- |
| 92.2 | 77.8  |

For cross domain you should probably have a look at:
https://arxiv.org/pdf/1711.08184.pdf

**Comment by XiangqingZhang** [comment]
ok ，Thank you very much for your sharing and advice
