### ISSUE TITLE
How to run DeepSORT on multiprocessing pipeline?

### ISSUE THREAD

**Issue by MichaelAiz** [mikel-brostrom/Yolov5_DeepSort_Pytorch#317]
Hi, I'm working on a project architecture which continuously passes image frames from a drone into a multiprocessing pipeline. I was wondering if it is possible to continuously run deepSORT on these frames as they are retrieved from the pipeline(a queue)? If so, how would I go about doing so? Awesome project and thank you!

**Comment by mikel-brostrom** [comment]
1. Put the images in a queue
2. Check if the queue is empty, if not empty grab and image else wait for an incoming image

**Comment by MichaelAiz** [comment]
I see, yeah that was going to be my approach but to be more specific I was wondering if there is functionality currently in the repo to support running tracking on a per image basis, and without re-calling the main track function on each image? So that as new frames came in it would update the tracker and remember the previous detections

**Comment by mikel-brostrom** [comment]
This repo supports reading from: RTSP, RTMP and HTTP streams. As long as you publish to such a stream
this repo will be able to handle it
