### ISSUE TITLE
ID switching 

### ISSUE THREAD

**Issue by marsyaaaaal** [mikel-brostrom/Yolov5_DeepSort_Pytorch#318]
Hello, i am new to this, why does the id of object 1 swaps with the object 2? Even though they don't have a lot in common and they're far from each other? 

I am using yolov5s at 640 img and 0.45 conf thresh
And osnet_x1_0 reid model 

Thank you

**Comment by gfleg77** [comment]
Try to adjust the  parameters in the Yolov5_DeepSort_Pytorch/tree/master/deep_sort/configs/deep_sort.yaml

**Comment by mikel-brostrom** [comment]
You can start by lowering

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/8bd72cadfae822bbabdc67a45b9d57abbfdf0135/deep_sort/configs/deep_sort.yaml#L3

to 0.1 or 0.05
