### ISSUE TITLE
Image folder as input does not return a movie

### ISSUE THREAD

**Issue by wilmarvanommeren** [mikel-brostrom/Yolov5_DeepSort_Pytorch#319]
When running track.py on a folder containing multiple images the video output is stored as a single image file. The reason for this is the save_path created from the variable p on line 139. In the current case a new path is created for each image with the same extension as the image. If I hardcode line 139 it works:

`p, im0, _ = "hardcode_fix.mp4", im0s.copy(), getattr(dataset, 'frame', 0)`

Is there a possibility to make the track.py working on images with save_vid enabled?

Cheers,
Wilmar

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/250
