### ISSUE TITLE
I could not find yolov5 .pt file in given link

### ISSUE THREAD

**Issue by farhodbekshamsiyev** [mikel-brostrom/Yolov5_DeepSort_Pytorch#32]
Hi! Can you share yolov5 .pt file. I could not find it in google drive.

**Comment by AbedMHroub** [comment]
Hi, I also cannot access the .pt file, after clicking on the link! the message in the image appears.
![Screenshot 2020-11-23 110010](https://user-images.githubusercontent.com/36266329/99944242-32b6cc00-2d7b-11eb-99fb-945cc7bcce6e.png)

**Comment by farhodbekshamsiyev** [comment]
> Hi, I also can not access the .pt file, after clicking on the link! the message in the image appears.
> ![Screenshot 2020-11-23 110010](https://user-images.githubusercontent.com/36266329/99944242-32b6cc00-2d7b-11eb-99fb-945cc7bcce6e.png)

I found .pt file from different github project
If you want I can share![https://github.com/DataXujing/YOLO-v5](url)

**Comment by Kingstom8MB** [comment]
you can try this herf:
https://pan.baidu.com/s/15c0i-EQuKiTXrOGp3ShxvQ 
提取码(key)：u5v3
I saved it on my Baidu disk

**Comment by AbedMHroub** [comment]
> > Hi, I also can not access the .pt file, after clicking on the link! the message in the image appears.
> > ![Screenshot 2020-11-23 110010](https://user-images.githubusercontent.com/36266329/99944242-32b6cc00-2d7b-11eb-99fb-945cc7bcce6e.png)
> 
> I found .pt file from different github project
> If you want I can share![https://github.com/DataXujing/YOLO-v5](url)

Can you share it with me?

**Comment by jasondalycan** [comment]
> > > Hi, I also can not access the .pt file, after clicking on the link! the message in the image appears.
> > > ![Screenshot 2020-11-23 110010](https://user-images.githubusercontent.com/36266329/99944242-32b6cc00-2d7b-11eb-99fb-945cc7bcce6e.png)
> > 
> > 
> > I found .pt file from different github project
> > If you want I can share![https://github.com/DataXujing/YOLO-v5](url)
> 
> Can you share it with me?

Can you share with me too please?

**Comment by hrvojej** [comment]
Use original weight from authors of yolov5 from:
https://github.com/ultralytics/yolov5/releases/download/v3.1/yolov5x.pt
and it works ok,

In case of problems in the future get new weights here:
https://github.com/ultralytics/yolov5/releases

**Comment by farhodbekshamsiyev** [comment]
> > > Hi, I also can not access the .pt file, after clicking on the link! the message in the image appears.
> > > ![Screenshot 2020-11-23 110010](https://user-images.githubusercontent.com/36266329/99944242-32b6cc00-2d7b-11eb-99fb-945cc7bcce6e.png)
> > 
> > 
> > I found .pt file from different github project
> > If you want I can share![https://github.com/DataXujing/YOLO-v5](url)
> 
> Can you share it with me?

https://github.com/DataXujing/YOLO-v5
https: slash slash github dot com slash DataXujing slash YOLO-v5
you can check this site

**Comment by farhodbekshamsiyev** [comment]
> Use original weight from authors of yolov5 from:
> https://github.com/ultralytics/yolov5/releases/download/v3.1/yolov5x.pt
> and it works ok.
> 
> In case of problems in the future get new weights here:
> https://github.com/ultralytics/yolov5/releases

Thanks bro

**Comment by farhodbekshamsiyev** [comment]
Finally we found a .pt files
Thanks a lot for supporting
