### ISSUE TITLE
Result txt file doesn't show str results but only %g %g

### ISSUE THREAD

**Issue by Sarouch** [mikel-brostrom/Yolov5_DeepSort_Pytorch#320]
Hello, I wonder if anyone knows why my results.txt is like this ? What's wrong ?

![image](https://user-images.githubusercontent.com/40342672/156533863-4e4aa589-76fc-4934-8709-3819c5f3d3aa.png)

Regards,

**Comment by mikel-brostrom** [comment]
I have never tried this piece of code on windows. Maybe some other windows user could help out here :smile:

**Comment by Sarouch** [comment]
> I have never tried this piece of code on windows. Maybe some other windows user could help out here 😄

Thanks, otherwise I will run the code on ubuntu and see .... 
But interesting to have an answer from windows users
