### ISSUE TITLE
deepsort with detections other than yolov5

### ISSUE THREAD

**Issue by hlmhlr** [mikel-brostrom/Yolov5_DeepSort_Pytorch#324]
Hi,

I have detections in .txt file. Can i use this repository by importing the detections from text file without using the yolov5 detector?
Thanks in advance

**Comment by mikel-brostrom** [comment]
Sure, but there is no functionality for doing this out of the box. You would basically need to read the detections from the `.txt` file and format them in the same way as the Yolov5 output. By doing so would be able to pass this values forward to deepsrot

**Comment by hlmhlr** [comment]
Many thanks dear for your response. I shall be making the changes accordingly. I am closing it for now.
Also, if possible please guide for the issue #325.

**Comment by jakobGTO** [comment]
> Many thanks dear for your response. I shall be making the changes accordingly. I am closing it for now. Also, if possible please guide for the issue #325.

Hello,

Did you manage to make the necessary changes for this to work, would be greatly appreciated if you could share in that case! :)
