### ISSUE TITLE
Loading the custom trained Re-ID model for deepsort

### ISSUE THREAD

**Issue by hlmhlr** [mikel-brostrom/Yolov5_DeepSort_Pytorch#325]
Hi,
 I am trying to run this repo with a Re-ID model trained on the custom dataset. For that, I tried to run the repo using the following command:

python3 .../DeepSort_Pytorch/track.py --source .../mot_val_sequences --yolo_model ...weights/yolov5s.pt --deep_sort_model .../deep_sort/deep/checkpoint/osnet_x1_0.tar-150 --config_deepsort .../deep_sort/configs/deep_sort.yaml

For the  "--deep_sort_model" argument, I have given the path of Re-ID trained model and this has thrown the error, pasted below. 
However, when I give any name from the list (mentioned in the last part of the error), the imagenet pre-trained model is initialized for the Re-ID, instead of the custom trained model. 

How can I ensure that custom trained Re-ID model is loaded for the deep-sort?

Thanks in advance!

  
Error:===================================
Traceback (most recent call last):
  File "/home/hlr/Documents/3rd_year_21_22/mot_22/deepsort/Yolov5_DeepSort_latest_1/Yolov5_DeepSort_Pytorch/track.py", line 279, in <module>
    detect(opt)
  File "/home/hlr/Documents/3rd_year_21_22/mot_22/deepsort/Yolov5_DeepSort_latest_1/Yolov5_DeepSort_Pytorch/track.py", line 58, in detect
    max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET,
  File "/home/hlr/Documents/3rd_year_21_22/mot_22/deepsort/Yolov5_DeepSort_latest_1/Yolov5_DeepSort_Pytorch/deep_sort/deep_sort.py", line 20, in __init__
    device=str(device)
  File "/home/hlr/anaconda3/envs/test_track/lib/python3.7/site-packages/torchreid/utils/feature_extractor.py", line 75, in __init__
    use_gpu=device.startswith('cuda')
  File "/home/hlr/anaconda3/envs/test_track/lib/python3.7/site-packages/torchreid/models/__init__.py", line 115, in build_model
    'Unknown model: {}. Must be one of {}'.format(name, avai_models)
KeyError: "Unknown model: /home/hlr/Documents/3rd_year_21_22/mot_22/deepsort/Yolov5_DeepSort_latest_1/Yolov5_DeepSort_Pytorch/deep_sort/deep/checkpoint/osnet_x1_0.tar-150. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25']"

> 

>

**Comment by mikel-brostrom** [comment]
```python
self.extractor = FeatureExtractor(
    model_name=model_type,
    model_path="/home/mikel.brostrom/Yolov5_DeepSort_Pytorch/deep_sort/deep/checkpoint/osnet_ibn_x1_0_market1501_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip_jitter.pth",
    device=str(device)
)
```

**Comment by mikel-brostrom** [comment]
This just got an update! As long as you provide the model type, i.e. 

```
__model_types = [
    'resnet50', 'mlfn', 'hacnn', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4',
    'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25',
    'osnet_ibn_x1_0', 'osnet_ain_x1_0']
```

 in your model path it should be able to handle it.
