### ISSUE TITLE
ID Switching frequently

### ISSUE THREAD

**Issue by zxq309** [mikel-brostrom/Yolov5_DeepSort_Pytorch#327]
https://user-images.githubusercontent.com/22740766/157569884-51296df3-a8c1-49ab-b5f0-43f2587a091d.mp4

yolov5 inference results

https://user-images.githubusercontent.com/22740766/157569934-786d79f4-e37a-4b90-9dad-93432766c04e.mp4

yolov5_deepsort results

how to solve ID switch frequently

**Comment by songjiahao-wq** [comment]
I have the same problem and look forward to the solution

**Comment by mikel-brostrom** [comment]
Try the following:

MAX_DIST: 0.1
MAX_AGE: 90

Set lambda to 0.1 here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/e43588593a93f9fa48d7a994ed9be9fa7f71b9f0/deep_sort/sort/tracker.py#L38

Does this make any difference?

**Comment by XiangqingZhang** [comment]
@mikel-brostrom I set conf-thres=0.25, all your mentioned I will test later

**Comment by songjiahao-wq** [comment]
When I am reasoning pedestrian video, the change in ID is in the order, for example, how to do it from 20 to 25? @mikel-brostrom

**Comment by songjiahao-wq** [comment]
When I am reasoning pedestrian videos, pedestrian ID changes is in order, such as new pedestrians, will allocate a 25 ID from 20 @mikel-brostrom

**Comment by mikel-brostrom** [comment]
Any updates @zxq309 , @songjiahao-wq?

**Comment by Saad-Salman101** [comment]
@mikel-brostrom i tried to make the changes you told but it wasn't helpful. whenever i move my head quickly the bounding box disappears and when ever there was a new bounding box on my head it was of different id(when using webcam). I also tried it on a video of people on escalator i am attaching the video( id gets switched easily ). btw i am using it on cpu (osnet_x0_25 model)

https://user-images.githubusercontent.com/75979337/160679998-26ea92ba-d1d5-44b1-9f99-1aa7acaa9097.mp4

)

**Comment by mikel-brostrom** [comment]
COCO does not contain top-view images of people. So if that is what you want to track you should train a Yolo model on top-view images of people for best performance. Its to much to ask a model for top-view people detection if it has never seen a top view representation of people previously.
