### ISSUE TITLE
x1y1x2y2 to xywh normalized

### ISSUE THREAD

**Issue by nullun1998** [mikel-brostrom/Yolov5_DeepSort_Pytorch#329]
Hi,
 I wonder is there a way to get the normalization's coordinate and save into text file?

**Comment by mikel-brostrom** [comment]
You could input `det[:, 0:4]` to:

https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/utils/general.py#L573

By doing so you would get normalized x, y, w, h out

**Comment by nullun1998** [comment]
Hi, really thank for your reply
I did try using xyxy2xywhndet(det[:, 0:4]) to get coordinate
However, the coordinate did not seen to be normalized
it show :
![messageImage_1647014831924](https://user-images.githubusercontent.com/71395474/157904311-8079520d-abbd-44d9-90a3-a0f746d6e0b1.jpg)
what is the reason it did not normalized?

**Comment by mikel-brostrom** [comment]
Have you changed:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/8bd72cadfae822bbabdc67a45b9d57abbfdf0135/track.py#L235

?

**Comment by nullun1998** [comment]
No , I didn't change the size of image.
Or should I set it to 640 by using --img-size ?

**Comment by mikel-brostrom** [comment]
`xyxy2xywhn` has hardcoded w & h to 640. If your `img-size` would be different it would explain the larger-than-1 values you get

**Comment by nullun1998** [comment]
Hi , sorry for the late reply
Even I set --img-size to 640 or not change any size
it show same 640 image size:
![image](https://user-images.githubusercontent.com/71395474/158011258-a474ae68-4eef-4a12-9437-ffd1218b2ab3.png)
The result stay as same as the last result:
![image](https://user-images.githubusercontent.com/71395474/158011427-410d297e-5c16-4470-a658-700a5c224d92.png)

However , i try to use original yolov5 code to output txt: 
![image](https://user-images.githubusercontent.com/71395474/158011523-2885d266-675f-4a07-89bb-c5dbaa19d236.png)
It seem to output normalization's coordinate fine:
![image](https://user-images.githubusercontent.com/71395474/158011581-e7d49e10-3a33-4e46-ad73-b6c2a766acfa.png)

The number of x center  form using xyxy2xywhn(det[:, 0:4]) divided by 3 is exacty same as original yolov5 code output
So I change 
![image](https://user-images.githubusercontent.com/71395474/158012056-a45c8c4a-6d06-4f11-9f12-b34e6f60b824.png)
and the output almost as same as the original yolov5 code output except the y center is slighty diffierent

the reason of y center using (640/384) :
![image](https://user-images.githubusercontent.com/71395474/158012225-f555985b-7e8d-43d8-ae8a-8540f303839d.png)

Is there any reason why the  def xyxy2xywhn need to divided by 3 and (640/384)?
Thank you once again for everything you've done and your reply!

**Comment by nullun1998** [comment]
Hi , I find out that the reason why need to add 3 and (640/384)
It affected by original video size (1920,1080) ,so it shoud be 1920/640 and 1080/640
Is there any way to auto detect the original video size or fix this problem?

Its kind of weird that it didnt change  xyxy2xywhn(det[:, 0:4]) to 640 and other just working fine.

**Comment by mikel-brostrom** [comment]
This is a question for the Yolov5 repo. It looks like they have updated the way of normalizing. I wasn't aware of this

https://github.com/ultralytics/yolov5/blob/698a5d7f26002e7b0b0d535d981c2b92f25bc76e/detect.py#L161
