### ISSUE TITLE
Human overlapping tracking is not accurate

### ISSUE THREAD

**Issue by eeric** [mikel-brostrom/Yolov5_DeepSort_Pytorch#33]
1.reid of one people was not ok sametimes.
2.Human overlapping tracking is not accurate.
hope the author can improve.

**Comment by mikel-brostrom** [comment]
Thanks for the feedback!

This repo contains mostly the work of other people. I wanted to try how much the tracking accuracy of Deep Sort would increase with yolov5 compared to yolov4.
