### ISSUE TITLE
Should it keep tracking people if there is no detection after some point?

### ISSUE THREAD

**Issue by sezer-muhammed** [mikel-brostrom/Yolov5_DeepSort_Pytorch#332]
Tracker stops tracking objects when yolo cannot find them, Shouldn't it compensate this error and detect people?

**Comment by mikel-brostrom** [comment]
> Shouldn't it compensate this error and detect people?

You could do that for some frames (while you wait for a new observation) but it is not the case for this implementation. As you can see here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/8bd72cadfae822bbabdc67a45b9d57abbfdf0135/deep_sort/sort/tracker.py#L76

Only matched tracks get their KF state updated by its associated detection. But you could of course input the predicted KF state recursively while there are no matches
