### ISSUE TITLE
Question on Logger output

### ISSUE THREAD

**Issue by HeChengHui** [mikel-brostrom/Yolov5_DeepSort_Pytorch#334]
@mikel-brostrom 
command passed: 
`python track_edited.py --device 0 --yolo_model yolov5s.pt --source "./sequences/uav0000009_03358_v"--classes 0 --imgsz 1360`

1) image size
Input images size (w x h) = 1360 x 765
logger output after processing 1 image = `800x1376 1 person, Done. YOLO:(0.031s), DeepSort:(0.017s)`
logger output at the end = `per image at shape (1, 3, 1376, 1376)`

    why is there a difference in size?

2) speed
The timing stated at the end is: `Speed: 1.6ms pre-process, 27.4ms inference, 1.9ms NMS, 29.5ms deep sort update`
Is it correct to say that the combination of all the timing is the average throughput of an image?
Is there a way to calculate latency?

3) missing lines in text saved
From Logger = `image 1/219 E:\FYP\Yolov5_DeepSort_Pytorch\sequences\uav0000009_03358_v\0000001.jpg: 800x1376 1 person, Done. YOLO:(0.031s), DeepSort:(0.018s)`
From saved results = `3,1,348,304,15,34,1,2,0,0`

    Can see that it is missing tracks from 1st frame. Furthermore, Frame 3 has 2 people detected but the text file only showed 1.

**Comment by mikel-brostrom** [comment]
> why is there a difference in size?

Yolov5 uses something called letterbox. Check:

https://github.com/ultralytics/yolov5/blob/b7d18f363665791bfaf58cd110dc162ebb5df3b5/utils/augmentations.py#L91

>  Is it correct to say that the combination of all the timing is the average throughput of an image?

Yes

> Can see that it is missing tracks from 1st frame. Furthermore, Frame 3 has 2 people detected but the text file only showed 1

DeepSort keeps tracks in initialization phase a certain number of frames before it starts tracking them. You can control this behavior by:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/ab4dd57f61e67e0cced34126e0ba01a442c6a99a/deep_sort/configs/deep_sort.yaml#L6

**Comment by HeChengHui** [comment]
> Yolov5 uses something called letterbox. Check:

in (https://github.com/ultralytics/yolov5/issues/6946), it seems that `--imgsz 1360` should conform to the input image size of 1360x765. However, the logger doesn't seem to agree. Can I check what is the correct image size being inferred?

> DeepSort keeps tracks in initialization phase a certain number of frames before it starts tracking them. You can control this behavior by:

Does that mean the logger displays the total number of objects detected, regardless of whether an object has 3 consecutive hits? Whereas the objects saved to text has 3 or more consecutive hits?

**Comment by HeChengHui** [comment]
@mikel-brostrom 

> Yolov5 uses something called letterbox. Check:

in (https://github.com/ultralytics/yolov5/issues/6946), it seems that `--imgsz 1360` should conform to the input image size of 1360x765. However, the logger doesn't seem to agree. Can I check what is the correct image size being inferred?

> DeepSort keeps tracks in initialization phase a certain number of frames before it starts tracking them. You can control this behavior by:

Does that mean the logger displays the total number of objects detected, regardless of whether an object has 3 consecutive hits? Whereas the objects saved to text has 3 or more consecutive hits?

**Comment by HeChengHui** [comment]
@mikel-brostrom hi possible to clarify the image size differences?

**Comment by mikel-brostrom** [comment]
I revisited our conversation.

> why is there a difference in size?

The length of the longest side of the image conforms to the closest multiple of 32. If you set `--imgsz 1360` this will be `1376`
