### ISSUE TITLE
Bug : Error when specifying yolo_model

### ISSUE THREAD

**Issue by Camilochiang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#336]
`Traceback (most recent call last):
  File "track.py", line 260, in <module>
    detect(opt)
  File "track.py", line 70, in detect
    name = yolo_model.split(".")[0] + "_" + deep_sort_model
AttributeError: 'list' object has no attribute 'split'`

Easily fix changing  `track.py` from
`
parser.add_argument('--yolo_model', nargs='+',type=str, default='yolov5n.pt', help='model.pt path(s)')`
to
`parser.add_argument('--yolo_model', type=str, default='yolov5n.pt', help='model.pt path(s)')`

**Comment by mikel-brostrom** [comment]
Thank you for pointing this out! This should now be fixed and should also be working for ensembled Yolo models. This is:

> python3 track.py **--yolo_model yolov5n.pt yolov5s.pt** --source 0 --classes 0 1 2
