### ISSUE TITLE
About training the RE-ID model

### ISSUE THREAD

**Issue by Liqq1** [mikel-brostrom/Yolov5_DeepSort_Pytorch#337]
Hi～
![72AFCEA575E865DE06BE5C894E139A57](https://user-images.githubusercontent.com/54054113/159126484-dfd5baad-5ccf-4ae0-862a-984024e37a2f.jpg)
I can't open this website where I can download train.Can you help me？
![DFBBA9455FCFD3C394E99B5CC9D05416](https://user-images.githubusercontent.com/54054113/159126510-03fd6b7e-4d59-4f1f-9dbb-3eac3d17e52b.jpg)

**Comment by mikel-brostrom** [comment]
I cannot help you. That is not my repository. Contact the repo's responsible person

**Comment by Liqq1** [comment]
> I cannot help you. That is not my repository. Contact the repo's responsible person

I mean can you open the file? I want to know if the file is missing
