### ISSUE TITLE
No parent package Error

### ISSUE THREAD

**Issue by hazelfield** [mikel-brostrom/Yolov5_DeepSort_Pytorch#340]
What can I do when it keeps warning that something wrong with my Anaconda\Lib\site-packages\urllib3\util? Like "ImportError: attempted relative import with no known parent package". But it's exactly what I downloaded from anaconda's official website

**Comment by mikel-brostrom** [comment]
Not sure. I am not a big fan of Anaconda. But check:
https://stackoverflow.com/questions/16981921/relative-imports-in-python-3
