### ISSUE TITLE
Track.py

### ISSUE THREAD

**Issue by farshokat** [mikel-brostrom/Yolov5_DeepSort_Pytorch#345]
Hello everyone, I run track.py but I have an error when runed this file: TypeError: __init__() got multiple values for argument 'max_dist'. I also don't know why and can't fix it. Can you help me? thank you very much.   
![Screenshot from 2022-03-26 12-27-15](https://user-images.githubusercontent.com/48058622/160226163-fa4340a6-25d0-47a7-8357-3a811508416d.png)

**Comment by mikel-brostrom** [comment]
CI pipeline shows a working master. I recommend you to reclone the repo. It seems that you have made some modifications to the code that makes it non runnable

**Comment by farshokat** [comment]
thanks you @mikel-brostrom , I reclone this repo and run successful
