### ISSUE TITLE
Getting Bounding Boxes with Object IDs

### ISSUE THREAD

**Issue by BaranGursoy** [mikel-brostrom/Yolov5_DeepSort_Pytorch#346]
Hi, I'm new to object tracking and gotta use it for my term project, I need to track people and some machines and check if a specific person collides with a specific machine, tracking works just fine but I couldn't get the data that I need. Is there a way for this, or do you recommend something to get this (bounding box, object id) data? Thanks in advance and sorry if my question is very simple.

**Comment by mikel-brostrom** [comment]
You could check if the IoU (intersection over union) for the bboxes associated to people and machines are over a certain threshold. Whatever you would consider as collision.
