### ISSUE TITLE
Track module doesn't work

### ISSUE THREAD

**Issue by CloudShen-107** [mikel-brostrom/Yolov5_DeepSort_Pytorch#347]
I git cloned the repo and followed the tutorial, but it seems the deepsort module doesn't work. It can only detect without track, IDs on objects change out of control.
Here is my run command. 
python track.py --source Videos/people.avi --deep_sort_model models/osnet_ain_x1_0_msmt.pth --yolo_model models/yolov5m.pt --show-vid --class 0 2 5

**Comment by CloudShen-107** [comment]
I have tried other deepsort repos using yolov3 or yolov5 on the same video, they can work well. I wonder which step was wrong.

**Comment by mikel-brostrom** [comment]
Could you post as snippet of the video that you are trying to track?

**Comment by Gigigi77** [comment]
Hi @CloudShen-107 , excuse me.
I met a bother that 
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1q3Sj2ii34NlfxA4LvmHdWO_75NDRmECJ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4ead93df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))`
Do u know how to solve this? I can not download `models/osnet_ain_x1_0_msmt.pth `, Where did you download it from?

**Comment by CloudShen-107** [comment]
> 

https://user-images.githubusercontent.com/56819813/161485681-ce4c0a77-bba8-482b-95af-d85612d26de8.mp4

**Comment by CloudShen-107** [comment]
> Hi @CloudShen-107 , excuse me. I met a bother that `urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1q3Sj2ii34NlfxA4LvmHdWO_75NDRmECJ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4ead93df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))` Do u know how to solve this? I can not download `models/osnet_ain_x1_0_msmt.pth `, Where did you download it from?

Are you Chinese? Maybe you can try VPN.

**Comment by Gigigi77** [comment]
> > Hi @CloudShen-107 , excuse me. I met a bother that `urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1q3Sj2ii34NlfxA4LvmHdWO_75NDRmECJ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4ead93df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))` Do u know how to solve this? I can not download `models/osnet_ain_x1_0_msmt.pth `, Where did you download it from?
> 
> Are you Chinese? Maybe you can try VPN.

okay. Thank u sir. I use VPN on Ubuntu, but it didn't work. FInally I download modules on the website directly, it solved.

**Comment by mikel-brostrom** [comment]
Try with a larger Yolo model @CloudShen-107 . l  or x. If still not happy with the results you would need to train a custom model

**Comment by CloudShen-107** [comment]
> Try with a larger Yolo model @CloudShen-107 . l or x. If still not happy with the results you would need to train a custom model

Ok，I will have a try. Thank you very much!
