### ISSUE TITLE
yolov5 weight no longer available on google drive

### ISSUE THREAD

**Issue by kate-sann5100** [mikel-brostrom/Yolov5_DeepSort_Pytorch#35]
Hi, thank you for your great work.

However, the yolov5 weight appears to be remove from the google drive link provided.

Would you mind upload the weight again please?

**Comment by eeric** [comment]
download from:
https://github.com/ultralytics/yolov5
torch>=1.6

**Comment by wutheringcoo** [comment]
baidu drive?发错了把

**Comment by eeric** [comment]
@wutheringcoo thanks, modified.

**Comment by mikel-brostrom** [comment]
I updated the README and added new functionality to the repo @kate-sann5100, @eeric, @wutheringcoo
