### ISSUE TITLE
Why is DeepSort slower than Yolov5?

### ISSUE THREAD

**Issue by elofamomo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#350]
![image](https://user-images.githubusercontent.com/75571933/160534547-365c5621-795c-4b4d-aa03-247acaf14ef0.png)
I'm try to demo yolov5 + deep sort . I'm curiously that might happen , is deep sort actually slow down the track phase ??Can anyone do me a favor on it ?? thank very muchhhh

**Comment by mikel-brostrom** [comment]
Based on your results I suppose your are running the tracker on CPU. 
`osnet_ibn_x1_0_MSMT17` is probably very inefficient on CPU.

MY GPU results with the default setting:

`0: 480x640 1 person, 1 laptop, Done. YOLO:(0.041s), DeepSort:(0.018s)`

my CPU results:

`0: 480x640 1 person, 1 laptop, Done. YOLO:(0.417s), DeepSort:(0.932s)`

However, if you change the deep sort model to osnet_x0_25_MSMT17. The CPU results would look like this:

`0: 480x640 1 person, 2 laptops, Done. YOLO:(0.429s), DeepSort:(0.037s)`

It is matter of what model you choose. Experiment with them a check which one suits your use-case the most.

**Comment by elofamomo** [comment]
thank you . It worked
