### ISSUE TITLE
No bboxes are drawn when set multiple input streams to sources

### ISSUE THREAD

**Issue by satosisotas** [mikel-brostrom/Yolov5_DeepSort_Pytorch#352]
I am trying to use two or more webcams at the same time by using `--souce stream.txt` option.
The content of stream.txt is like followings:
```
/dev/video0
/dev/video1
```
Two video windows open, and looks running fine as far as the logs go.
However no bounding box visualization are drawn on the video window .
If the stream.txt is only one line like as `/dev/video0`, everything is works fine.

So I checked the code, at first, at track.py#L174;
```python
                if len(outputs) > 0:
```
`len(outpus)` is always 0.

Next, I found at deep_sort.py#L75;

```python
            if not track.is_confirmed() or track.time_since_update > 1:
```
`track.is_confirmed()` is always False.

Could you give me a hint to solve this?

**Comment by akbarali2019** [comment]
The same issue I have. I have tested on .mp4 fromat but when I checked the saved results there are no bounding boxes for visualization.

**Comment by satosisotas** [comment]
Solved.

After solved by patching the code, I found this issue is almost same as the pull request https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/pull/284

I paste my patch for reference.

```
diff --git a/track.py b/track.py
index 066360e..0e4b3e5 100644
--- a/track.py
+++ b/track.py
@@ -9,6 +9,7 @@ os.environ["NUMEXPR_NUM_THREADS"] = "1"
 import sys
 sys.path.insert(0, './yolov5')
 
+import copy
 import argparse
 import os
 import platform
@@ -100,6 +101,9 @@ def detect(opt):
         cudnn.benchmark = True  # set True to speed up constant image size inference
         dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt and not jit)
         bs = len(dataset)  # batch_size
+        if bs > 1:
+            deepsort_list = [copy.deepcopy(deepsort) for i in range(bs)]
+            del deepsort
     else:
         dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt and not jit)
         bs = 1  # batch_size
@@ -141,6 +145,8 @@ def detect(opt):
             if webcam:  # batch_size >= 1
                 p, im0, _ = path[i], im0s[i].copy(), dataset.count
                 s += f'{i}: '
+                if bs > 1:
+                    deepsort = deepsort_list[i]
             else:
                 p, im0, _ = path, im0s.copy(), getattr(dataset, 'frame', 0)
```

**Comment by akbarali2019** [comment]
What about with .mp4 file? I have run log is okay, it is giving tracking message but in the saved video boxes are not drawn.

**Comment by satosisotas** [comment]
Try this branch of my fork.

https://github.com/advaly/Yolov5_DeepSort_Pytorch/tree/patches/multiple_sources

Note that this branch requires `--show-vid` option if you want to show video window.
