### ISSUE TITLE
 bboxes are not there for visualization after saving tracking (--source .mp4 files)

### ISSUE THREAD

**Issue by akbarali2019** [mikel-brostrom/Yolov5_DeepSort_Pytorch#355]
Strange...  
1. There is no bboxes for tracked object when I watch the saved .m4 files. But in the log it is showing the tracking process. Please help, why it is not showing bboxes even after tracking?

Here you can see it is tracking the ball... but in the video there is no bboxes for visualization...   How can I fix this?

![issue](https://user-images.githubusercontent.com/52565814/161438617-7cedaac9-d4ae-4720-9f1e-e3cd89dd19ea.png)
2. When I use [--source 0] (local cam), it is tracking and showing the bbox for visualization. BUT it is not saving the stream as .mp4 file even I used [--save-vid].  When I USE [--save-txt] it is saving. How can I fix this saving issue?
.>
3. Can we use DeepSort for SOT(Single Object Tracking)? I have only one object to detect and track?
.>

**Comment by mikel-brostrom** [comment]
> 1. & 2.

 This repo has never been tested on windows. If you have a solution for this please leave a PR.

> 3.

Sure. As long as Yolov5 detect that single object that you want to track
