### ISSUE TITLE
Issue while running deepsort model 

### ISSUE THREAD

**Issue by ashwath1295** [mikel-brostrom/Yolov5_DeepSort_Pytorch#359]
Model: resnet50
- params: 23,508,032
- flops: 2,669,150,208
Successfully loaded pretrained weights from "deep_sort/deep/checkpoint/resnet50_MSMT17.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']**
Is this ok??

**Comment by mikel-brostrom** [comment]
The model is only used as feature extractor, it is not doing classification, so the classification layers are not relevant. That is why they are discarded.

**Comment by ashwath1295** [comment]
But I am getting precisely the same output while running with a different deepsort models. all the outputs are same
