### ISSUE TITLE
RuntimeError: CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by YuGongCharley** [mikel-brostrom/Yolov5_DeepSort_Pytorch#36]
When I run 'python3 track.py', whether pic or video
Jetson nano

**Comment by eeric** [comment]
reference test script

**Comment by mikel-brostrom** [comment]
It will be hard to help you with this little information. Could you provide he total error so that I can try to reproduce this on my Jetson nano

**Comment by YuGongCharley** [comment]
@eeric @mikel-brostrom sorry i forget the error information..
there is the pic about error when i run :
![Screenshot from 2020-12-02 16-58-01](https://user-images.githubusercontent.com/23618226/101518498-f4e1b680-39bc-11eb-916b-6947404f1e76.png)

and it was success when i run the project [ultralytics/yolov5](https://github.com/ultralytics/yolov5)
thanks a lot

**Comment by eeric** [comment]
The process needs to be shut down, you can use kill order

**Comment by YuGongCharley** [comment]
> The process needs to be shut down, you can use kill order

i run this command first after jetson nano power up, it didn't run any program before

**Comment by qingfeng-zhang** [comment]
I have the same error under latest jetson name 4GB, can't solve ,  can you please share how to work around?

**Comment by qingfeng-zhang** [comment]
sorrry, I am using latest jetson nano  4GB,
