### ISSUE TITLE
Issue running with Deepsort ReID model 

### ISSUE THREAD

**Issue by ashwath1295** [mikel-brostrom/Yolov5_DeepSort_Pytorch#362]
while running the model with different ReId models like resnet or osnet. After evaluation, the output is exactly the same. 
Can you help me with this?

**Comment by mikel-brostrom** [comment]
> After evaluation, the output is exactly the same. Can you help me with this?

You mean that the MOT16 evaluation results are the same no matter what DeepSORT model you use?

**Comment by ashwath1295** [comment]
yes @mikel-brostrom 

> > After evaluation, the output is exactly the same. Can you help me with this?
> 
> You mean that the MOT16 evaluation results are the same no matter what DeepSORT model you use?

**Comment by mikel-brostrom** [comment]
Are you sure that the files (MOT16_02.txt, ...) are getting overwritten?

**Comment by ashwath1295** [comment]
For some models, it is working and for some, it is not.

**Comment by mikel-brostrom** [comment]
Did you got this working @ashwath1295? What was the issue?
