### ISSUE TITLE
Unable to use this with yolov5s

### ISSUE THREAD

**Issue by kronu5** [mikel-brostrom/Yolov5_DeepSort_Pytorch#37]
I tried using a yolov5s model instead of the suggested yolov5x and for some reason there seem to be no detections.
I trained a custom dataset using yolov5s, renamed the 'best.pt' obtained at the end to 'yolov5s.pt' and pasted it in the yolov5_DeepSort_Pytorch/yolov5/weights and executed the command "python3 track.py --source vid.mp4 --weights yolov5/weights/yolov5s.pt

I can only see the video play at a high frame rate than usual with no detections being made and the same video gets saved in output. This doesn't happen while using yolov5x.pt
I have a RTX2070 max-q and am unable to train the model using the custom dataset( CUDA allocation error) and the provided yolov5x.pt is not so accurate.

I'd really appreciate it if you can help me run this using v5s instead.

**Comment by eeric** [comment]
torch >=1.6

**Comment by kronu5** [comment]
yep, I'm using torch 1.6. I guess I figured out my mistake. I was using a YAML file with humans being assigned class '1' instead of '0'.
I haven't tested this but I guess this should be the issue.
