### ISSUE TITLE
use yolov5 train our own datasets

### ISSUE THREAD

**Issue by feidasheng** [mikel-brostrom/Yolov5_DeepSort_Pytorch#4]
Hello, I would like to ask if your YOLOv5 code can be trained with your own dataset, thank you for your answer

**Comment by mikel-brostrom** [comment]
Hi!

Sorry for the late response, I have been on vacation. 

Yes, you can train YOLOv5 with your own dataset. In order to do so I recommend you to go through this: https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
