### ISSUE TITLE
How to solve this error? RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend 

### ISSUE THREAD

**Issue by lvxuanxuan123** [mikel-brostrom/Yolov5_DeepSort_Pytorch#42]
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].

Actually, I didn't get this error and couldn't search anything about this on google.
Is there anybody who knows the way to handle this?

Info:
I installed the CUDA v11.1 from https://developer.nvidia.com/cuda-downloads
torch version: 1.7.0
torchvision version: 0.8.0

**Comment by mikel-brostrom** [comment]
Could you try to upgrade torch and torchvision?
