### ISSUE TITLE
Objects that are fewer than the detected objects are numbered.

### ISSUE THREAD

**Issue by koreadhkim** [mikel-brostrom/Yolov5_DeepSort_Pytorch#43]
Objects that are fewer than the detected objects are numbered.

Isn't the detected object unconditionally assigned a number?

![image](https://user-images.githubusercontent.com/48986889/101652612-caa5fc80-3a81-11eb-8f7d-17ede2e91542.png)
![image](https://user-images.githubusercontent.com/48986889/101652628-cf6ab080-3a81-11eb-91fb-1f8c3a738d15.png)

As above, there are 4 detected objects, but 3 are numbered.

**Comment by mikel-brostrom** [comment]
No, detected object are not unconditionally assigned an ID. That is due to the fact that the Tracker needs a certain number of consecutive detections before the track is "confirmed".

**Comment by GairePravesh** [comment]
i am also facing same condition.... 6 detection's but only 5 are assigned, what can be done to solve it ? Every detection's are almost similar, i don't see a reason one not being assigned here ....

**Comment by koreadhkim** [comment]
Sorry. I don't understand well.
Could you please explain the example below?

For example, in frame 1, 4 objects are detected and numbers are assigned to 4 objects. What is the reason why 1 object is dropped in frame 2 (numbers are assigned only to 3 objects)?

**Comment by mikel-brostrom** [comment]
In the `Tracker` class you have an input parameter called `n_init`

```
n_init : int
        Number of consecutive detections before the track is confirmed. The
        track state is set to `Deleted` if a miss occurs within the first
        `n_init` frames.
```

**Comment by koreadhkim** [comment]
Thanks!!!!!!! ㅎㅎ
