### ISSUE TITLE
one shot tracking

### ISSUE THREAD

**Issue by berkantay** [mikel-brostrom/Yolov5_DeepSort_Pytorch#44]
hello @mikel-brostrom can we just initialize the tracker with optional bounding boxes?

**Comment by mikel-brostrom** [comment]
You could initialize the tracker with some a priori detections just after creating it by:

`deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
                        max_dist=cfg.DEEPSORT.MAX_DIST, min_confidence=cfg.DEEPSORT.MIN_CONFIDENCE,
                        nms_max_overlap=cfg.DEEPSORT.NMS_MAX_OVERLAP, max_iou_distance=cfg.DEEPSORT.MAX_IOU_DISTANCE,
                        max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET,
                        use_cuda=True)
outputs = deepsort.update(xywhs, confss, im0)`
