### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

### ISSUE THREAD

**Issue by balaji-skoruz** [mikel-brostrom/Yolov5_DeepSort_Pytorch#45]
when using google colab

**Comment by mikel-brostrom** [comment]
A quick search gave me:
https://stackoverflow.com/questions/64113537/google-colab-error-could-not-load-the-qt-platform-plugin-xcb

**Comment by mikel-brostrom** [comment]
Google Colab does not allow to open additional windows so it will fail every time that `cv2.imshow()` is called

**Comment by balaji-skoruz** [comment]
Yeah Google colab doesn't allow to use the gui, Then how do I use this code
in colab , I am using colab because I don't have gpu in my system. Give me
a solution please.

**Comment by mikel-brostrom** [comment]
You won't be able to see the visual results but you can save the tracking information to a text file if that is enough for you

**Comment by balaji-skoruz** [comment]
Is there any function to save the output video or image ?
But the whole execution is aborted with the qt error. Then how can I get
the results in other way?

**Comment by mikel-brostrom** [comment]
`imshow()` is just showing the image, so you can comment those lines out. Then

set `save_img` in `def detect(opt, save_img=False):` to `True`

This will cancel the real time visualization and save the results to `inference/output`

**Comment by balaji-skoruz** [comment]
where to change ?

**Comment by balaji-skoruz** [comment]
same error continues even though save_img set to True

**Comment by balaji-skoruz** [comment]
Got it , just comment the line as shown below
 # # Stream results
            # if view_img:
            #     cv2.imshow(p, im0)
            #     if cv2.waitKey(1) == ord('q'):  # q to quit
            #         raise StopIteration


thank you mike !

**Comment by sandeepkamineni** [comment]
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

can please help me with this error

**Comment by balaji-skoruz** [comment]
> 

you cant view image in a separate window because colab is headless. find the code that used to view the image in the separate window and comment it.
