### ISSUE TITLE
tracking failed when open two streams

### ISSUE THREAD

**Issue by feifeiwei** [mikel-brostrom/Yolov5_DeepSort_Pytorch#49]
can you help me, when i open two or more cameras, the tracking is failed and object detection result is also disappeared.

**Comment by mikel-brostrom** [comment]
What do you mean? Do you run two instances of the tracker on the same machine?

**Comment by hdnh2006** [comment]
Yes @mikel-brostrom, if you put as `source` a txt file with several ip cameras as yolov5 does, it is not able to track. Any recommendation to fix it?

**Comment by hdnh2006** [comment]
@feifeiwei you have part of the solution in this answer: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/88#issuecomment-839671616
