### ISSUE TITLE
Taking too long

### ISSUE THREAD

**Issue by felipec23** [mikel-brostrom/Yolov5_DeepSort_Pytorch#5]
Hi! Thanks for creating this repository!
I'm running everything in Google Colab (with its 12GB of GPU). However, it's taking way too more than YOLOV3+Deepsort. Any idea why? How do I know I'm actually using the GPU? Thanks again!

**Comment by mikel-brostrom** [comment]
Hi!

Thank you for showing interest in my repo!

Could it have to do with the incompatibility between the CUDA version that Google Colab is running and the Pytorch version required (torch==1.5.1)? Torch 1.5 is built for CUDA 10.2 but when I run:

`!nvcc --version`

I get: 
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release **10.1**, V10.1.243`
