### ISSUE TITLE
nn_budget value is overwritten

### ISSUE THREAD

**Issue by umutpiri** [mikel-brostrom/Yolov5_DeepSort_Pytorch#52]
Hi, thanks for this great work! 
nn_budget configuration is overwritten in deep_sort.py [here](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/14c32b9c9494aaf9e1792f6ae7fb8d61afd822c8/deep_sort_pytorch/deep_sort/deep_sort.py#L22). I simply removed that line, but I wonder if there is a reason.

**Comment by mikel-brostrom** [comment]
Hi!

I am glad you like my repo! I deleted this unnecessary line. Thank for pointing this out @umutpiri!
