### ISSUE TITLE
Question : Why the track id suddenly jump from 30 to 36 ?

### ISSUE THREAD

**Issue by wwdok** [mikel-brostrom/Yolov5_DeepSort_Pytorch#53]
Hi, i print out identities in `track.py` after [this line of code](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/14c32b9c9494aaf9e1792f6ae7fb8d61afd822c8/track.py#L172), i found the log shows:

```
video 1/1 (2/341) /media/weidawang/DATA/FFOutput/Walking_Office_People.mp4: One prediction round
video 1/1 (3/341) /media/weidawang/DATA/FFOutput/Walking_Office_People.mp4: One prediction round
identities:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
video 1/1 (4/341) /media/weidawang/DATA/FFOutput/Walking_Office_People.mp4: One prediction round
identities:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 36]
video 1/1 (5/341) /media/weidawang/DATA/FFOutput/Walking_Office_People.mp4: One prediction round
identities:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 36 38]
video 1/1 (6/341) /media/weidawang/DATA/FFOutput/Walking_Office_People.mp4: One prediction round
identities:[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 36 38 40]
...
```
Observe those ids at the end of the identities list, they jump from 30 directly to 36, how to finetune some parameters to make the id number changes more continuous, thanks !

I use yolov5m.pt and [this video](https://www.youtube.com/watch?v=BFFZ6PZjM_E).

**Comment by mikel-brostrom** [comment]
Try this model out: 

https://github.com/deepakcrk/yolov5-crowdhuman

It should be stabler for pedestrians. let me know if you see any improvements.

**Comment by wwdok** [comment]
Sorry, i have gone to another company, the computer and the environment no longer exists , so i can't test it now... Welcome other people to test it ~

**Comment by mikel-brostrom** [comment]
Good luck at the new company!
