### ISSUE TITLE
yolov5 4.0 released 

### ISSUE THREAD

**Issue by NullpoGah** [mikel-brostrom/Yolov5_DeepSort_Pytorch#54]
So ultralytics just released new yolov5, but Milkel's repository links for 3.0 version. If anyone has any troubles with getting it to work, rm old yolov5 and clone Yolov5 by yourself, or just do not clone this rep recursively
```
git clone https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git
cd Yolov5_DeepSort_Pytorch
git clone https://github.com/ultralytics/yolov5.git
```
also ultralytics added seaborn plots so install seaborn if you have any troubles with module import

**Comment by mikel-brostrom** [comment]
I updated the submodule pointer, from version 3.0 to 4.0. Thanks for pointing this out @NullpoGah !
