### ISSUE TITLE
 I want to put the class name detected in the result.txt file as well. Is there any way?

### ISSUE THREAD

**Issue by bigreen8801** [mikel-brostrom/Yolov5_DeepSort_Pytorch#55]
The part I want to know is 'Put the class name detected in the result.txt file'  like the title.
I have tried this and that, but I am having difficulties. If there is any way, please.

Thank you.

![image](https://user-images.githubusercontent.com/56245227/103885914-12bd4b00-5124-11eb-8aa0-6b9408c77644.png)

**Comment by mikel-brostrom** [comment]
you have a solution [here](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/tree/class_to_txt)

**Comment by lonnylundsten** [comment]
Adding this just in case its helpful to others:

My solution was to add str(c) to the txt output at Lines 159,160 in the track.py file:

f.write(('%g ' * 10 + **str(c)** + '\n') % (frame_idx, id, bbox_left,
                                                           bbox_top, bbox_w, bbox_h, -1, -1, -1, -1))  # label format

This essentially adds the class_id to the end of each row like this:
<frame> <id> <bb_left> <bb_top> <bb_width> <bb_height> <conf> <x> <y> <z> **<class_id>**

Note, the class_id comes from your yolo.names file.

**Comment by BenzKukkik** [comment]
> Hi! you have a solution [here](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/tree/class_to_txt)

I cannot open your link. please share it again.
