### ISSUE TITLE
Using custom trained weight file instead of the weights available at website.

### ISSUE THREAD

**Issue by Subhajyotidas** [mikel-brostrom/Yolov5_DeepSort_Pytorch#57]
In the track.py file the classes argument takes class number as input. Default value is 0 that is why it detects persons. When I increased the class numbers it detected other objects too, despite saying " _The reason behind the fact that it just tracks persons is that the deep association metric is trained on a person ONLY datatset._". Then I got the impression that if I provide other weight file trained on custom dataset the tracking will work on that too, but it didn't. I have a custom trained weight file trained on '_license plate_'. When I use this file the detector detects nothing. How to make it work?

**Comment by Subhajyotidas** [comment]
Found the problem. Issue solved.

**Comment by Sarouch** [comment]
@Subhajyotidas Hello, could you tell me how did you solve the problem please ? I used another weight file, but it only detect one class, how can I make Track.py detect the 5 classes ?
