### ISSUE TITLE
Inference on Raspberry Pi 4 / Jetson Nano

### ISSUE THREAD

**Issue by ghost** [mikel-brostrom/Yolov5_DeepSort_Pytorch#58]
Hello, 

Thank you again for the repo. It is wonderful implementation and has sped up my work. I was wondering if you performed these experiments on Raspberry Pi 4 or Jetson Nano devices ? 

Thank you.

**Comment by mikel-brostrom** [comment]
Thank you!

I haven't tried to run this piece of code on niether of them. But I talked to people that achieved 5FPS on RPi3 if that helps

**Comment by gayatriprasad** [comment]
Thanks. Sure, that helps.  I'll try and run some experiments and let you know the results too.

**Comment by gayatriprasad** [comment]
Also, don't want to open a new issue for this. Maybe add EasyDict to the requirements.txt.

**Comment by gayatriprasad** [comment]
Hello, 

Well, I ran a couple of experiments on Raspberry Pi 4 ( 4GB). The time taken for each frame was about 7 seconds so I guess it is about 8-9 fps. However this is on a saved video and not webcam. 

Will update more results soon. 

Thank you.

**Comment by GeekAlexis** [comment]
[FastMOT](https://github.com/GeekAlexis/FastMOT) is more optimized if you want to run on Jetson devices.

**Comment by yyyhainan** [comment]
I would like to ask what value about --source should be given for using CSI camera on Nano?
