### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by seahawks8** [mikel-brostrom/Yolov5_DeepSort_Pytorch#6]
you are the first person I found that is using Yolov5 for deep sort. Thank you!

**Comment by mikel-brostrom** [comment]
I am glad that you like my Yolov5_DeepSort_Pytorch repo!

Most certainly I am. I couldn't find any deep sort implementation using Yolov5, that was the reason why I created this repository  :smile:

**Comment by seahawks8** [comment]
I am training my own deep sort, but unfortunately I have to annotate the video sequences, and I have been searching for the annotation software/tool that UA-detrac used.

**Comment by mikel-brostrom** [comment]
According to http://detrac-db.rit.albany.edu/ the UA-detrac dataset was annotated manually

However, if what you want is to track vehicles here is a list of a few vehicle re-identification datasets:

https://github.com/knwng/awesome-vehicle-re-identification

**Comment by seahawks8** [comment]
Yea they annotated manually, but I am looking for the software they used. I think they used this tool - https://github.com/KeLipeng/Multi-Object-Annotation-Tool

I am not tracking vehicles, but thanks for the heads-up, I will bookmark that link.

**Comment by mikel-brostrom** [comment]
I'll bookmark that multi-object annotation tool. Thanks!
