### ISSUE TITLE
Question: Why separated predict function()?

### ISSUE THREAD

**Issue by dsantiago** [mikel-brostrom/Yolov5_DeepSort_Pytorch#60]
What was the point in separating this function:

```python
...
def predict(self, kf):
    self.mean, self.covariance = kf.predict(self.mean, self.covariance)
    self.age += 1
    self.time_since_update += 1
```

into this one:

```python
...
def increment_age(self):
    self.age += 1
    self.time_since_update += 1

def predict(self, kf):
    self.mean, self.covariance = kf.predict(self.mean, self.covariance)
    self.increment_age()
```

You separated the age step and coll it on `track.py`
```python
...
if det is None:
    print('increment ages!')
    deepsort.increment_ages()
```
Even though the Tracker.update() method (from original code) appear to treat empty tracks. Any reason for this modification?

**Comment by mikel-brostrom** [comment]
The  age incremented functionality was separated to be able to increment the ages in the case that there are no detections.
In the case that there are no detections

 `# Pass detections to deepsort
outputs = deepsort.update(xywhs, confss, im0)`. 

does not get called, which implies that the ages of the tracks are not incremented either.

**Comment by dsantiago** [comment]
I see but isn't the age of the track needed to get rid oa a track, like if `max_age = 5` so if a detection is not seen in 5 frames, so it is removed

**Comment by mikel-brostrom** [comment]
Yes, that is right. But if the object was re-associated within those 5 frames the object was hopefully there, only that it was not detected. It is not that it makes a big difference in the final result but I still think is the right way to treat the tracks' ages

**Comment by dsantiago** [comment]
Thanks for clarifications!
