### ISSUE TITLE
The rationality of multi-class tracking

### ISSUE THREAD

**Issue by starsky68** [mikel-brostrom/Yolov5_DeepSort_Pytorch#61]
If tracking multiple classes, the reid should be a combination of multiple vectors. If it is a matrix of multiple vectors, it is sent directly to the back for tracking. Is this reasonable?

**Comment by mikel-brostrom** [comment]
I don't fully understand what you mean; but,  basically, what happens regardless you chose to track a single class or multiple is:

1. Kalman filtering is perfomed  in 2D image space and 
2. Frame-by-frame data association is calculated using the Hungarian method with an association metric that measures bounding box overlap and a deep learning metric (which is a single vector) for each of the objects

**Comment by starsky68** [comment]
What I mean is, if you track multiple calsses, does the output of the reid network contain multiple reid vectors to distinguish the vector groups corresponding to each classes, and then each vector group contains multiple targets of a certain classes

**Comment by lmarval** [comment]
> What I mean is, if you track multiple calsses, does the output of the reid network contain multiple reid vectors to distinguish the vector groups corresponding to each classes, and then each vector group contains multiple targets of a certain classes

The deep-sort implementation doesn't make use of the detection class. So it can mix the Ids of different classes. You can make a tracker object per class and distribute the detections to the class-respective tracker object. Take into account that the reid network used by deep-sort algorithm is  designed and trained for person tracking.
