### ISSUE TITLE
Saving results per detected person 

### ISSUE THREAD

**Issue by ghost** [mikel-brostrom/Yolov5_DeepSort_Pytorch#62]
Hi, 

Can you clarify if I can save images per ID ?

**Comment by Dishant-P** [comment]
A little clarification required. 
Saving the frames or saving just the cropped part of the IDs' bounding boxes?

**Comment by ahmedghadani** [comment]
Hi, I am interested in doing the same. Save a cropped image of the detection which is the IDs' bounding box area.

Similar to the original argument function "save-crop" in YOLO detect.py.

Any hints on how to do this? or if there is a repo/fork where someone already implemented something similar?

Thanks in advance

**Comment by Dishant-P** [comment]
You can just make a similar function inside of the draw function inside the track.py file. 
It already has the for loop and the overall frame. All you have to do is take the bounding box coordinates and crop the frame using PIL Image.crop or any similar function and save it.
