### ISSUE TITLE
How to skip frames in video?

### ISSUE THREAD

**Issue by WhiteD3vil** [mikel-brostrom/Yolov5_DeepSort_Pytorch#64]
My video has 1500 frames for 1 min. (Which is 25fps). I wanted the model to detect a 10th , 20th , 30th .. and so on till 1500th frame. So it should skip the in-between frames. How can i do it?

**Comment by raja1196** [comment]
Find where the frames are taken in as input (should be looping through the frames of the video) and try the methods suggested in the [link](https://vuamitom.github.io/2019/12/13/fast-iterate-through-video-frames.html)
