### ISSUE TITLE
It doens't follow an order in the name of the id

### ISSUE THREAD

**Issue by hdnh2006** [mikel-brostrom/Yolov5_DeepSort_Pytorch#66]
I used for track people and it is working well, but I cannot understand why the id are assigned without any order, as you can see in the next video, the numbers skip frequently and don't follow an order.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17271049/106128618-d2b81980-615f-11eb-93cc-1eadc44e68d5.gif)

As you can see, from 10 skip to more than 20, anyone know what is happening here?

Thanks in advance

**Comment by mikel-brostrom** [comment]
The algorithm works poorly in this case due to the position of the camera. It is positioned in such way that the object detector cannot make a god job as it is barely trained on BEV person images.

**Comment by hdnh2006** [comment]
I think this is happening for other reason, I have tried with different angles and the result is the same, I will upload another video tomorrow.

**Comment by AKHILzz12345** [comment]
Hey,
I have also encountered the same issue, track_ids are not in order Eg :[ 0, 1, 2, 10, 11, 13, 15, 18, 23, 26]. I am not sure why this is happening. Any help is much appreciated
Thanks

**Comment by mikel-brostrom** [comment]
Try this model out:

https://github.com/deepakcrk/yolov5-crowdhuman

It should be stabler for pedestrians. let me know if you see any improvements.
