### ISSUE TITLE
Where to find the towncenter dataset?

### ISSUE THREAD

**Issue by AsakusaRinne** [mikel-brostrom/Yolov5_DeepSort_Pytorch#67]
Hello, I'm also trying to combine yolov5 with deep-sort and I am finding the **towncenter** dataset, which is showed in your README file. But I got that this dataset has been no longer distributed on the Internet since June 2020. Could you please tell me where to find this dataset or send me via email? I will appreciate it a lot if you would be willing to help me.

**Comment by mikel-brostrom** [comment]
The dataset was taken down most probably due to GDPR concerns as they didn't blur the faces of the people in it. As of today I don't have the dataset so I cannot help you. I will probably update the example GIF in the repo.
