### ISSUE TITLE
Change the parameter "class" problem

### ISSUE THREAD

**Issue by wangmhua** [mikel-brostrom/Yolov5_DeepSort_Pytorch#68]
Hello, I have a question. If I want to track vehicles, change the default value of the "class" parameter from 0 (persons in COCO) to 2 (cars in COCO) to change the class. The experimental results show that it can be tracked. Why do you say this operation is meaningless? Thanks for the answer!

**Comment by mikel-brostrom** [comment]
I didn't said that it was meaningless, I said it is sub-optimal as the deep learning metric is trained on a person only Re-ID dataset
