### ISSUE TITLE
Problems in the category change code

### ISSUE THREAD

**Issue by wangmhua** [mikel-brostrom/Yolov5_DeepSort_Pytorch#69]
Hello, I have a question. I changed parser.add_argument('--classes', nargs='+', type=int,default=[2], help='filter by class') to track the vehicle. But I didn't find the setting about category change in the code. How do I realize the category change on the coco data set in the code? Many thanks!

**Comment by mikel-brostrom** [comment]
Each integer in the 'classes' argument list is associated to a MS-COCO class. You can find them here

https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml
