### ISSUE TITLE
unpickler.load()      ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by Leizhengwang** [mikel-brostrom/Yolov5_DeepSort_Pytorch#70]
How solve this? thanks

Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.4, config_deepsort='deep_sort_pytorch/configs/deep_sort.yaml', device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='detection.mp4', view_img=False, weights='yolov5/weights/yolov5s.pt')
D:\ML_Data\4_Mikel_brostrom_Yolov5_DeepSort_Pytorch\Yolov5_DeepSort_Pytorch-master\deep_sort_pytorch\utils\parser.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
Traceback (most recent call last):
  File "track.py", line 263, in <module>
    detect(args)
  File "track.py", line 88, in detect
    model = torch.load(weights, map_location=device)[
  File "C:\Users\Welcome\anaconda3\lib\site-packages\torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Welcome\anaconda3\lib\site-packages\torch\serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

**Comment by mikel-brostrom** [comment]
Comments about YOLOv5 will be solved better in the [original repository](https://github.com/ultralytics/yolov5)
