### ISSUE TITLE
Exporting to Onnx -- Opinion

### ISSUE THREAD

**Issue by ghost** [mikel-brostrom/Yolov5_DeepSort_Pytorch#74]
Hello Mikel.

Did you by any chance try to exporting to onnx models ? 

Thank You

**Comment by mikel-brostrom** [comment]
I haven't personally exported any of the models to ONNX. But I talk to people who did and got this running on an RPI3 at ~5FPS.
I suggest you to check https://github.com/ultralytics/yolov5/blob/master/models/export.py
