### ISSUE TITLE
multiple rtsp streams 

### ISSUE THREAD

**Issue by markride** [mikel-brostrom/Yolov5_DeepSort_Pytorch#77]
Hello! Is it possible to set up tracking on several rtsp streams at the same time? Unfortunately, when you start several streams written in the txt file, there is no tracking, but only the broadcast of the streams.

**Comment by hdnh2006** [comment]
Same for here, it seems the repo is not being updated :-(

**Comment by hdnh2006** [comment]
Did you find anyway to solve it @markride? 

Any suggestion @mikel-brostrom?

**Comment by hdnh2006** [comment]
@markride please you have part of the solution in this answer: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/88#issuecomment-839671616
