### ISSUE TITLE
How to obtain center points of bounding box from track.py

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [mikel-brostrom/Yolov5_DeepSort_Pytorch#78]
Hello everyone and thank you @mikel-brostrom for this amazing repo. I wanted to obtain and display the center points of the bounding boxes and found variables x_c and y_c which point to the center coordinates of the bbox. I used those variables to draw a circle using opencv in the draw_boxes function but the results shown is the center coordinates for a single object only, even when there are multiple objects in the frame. My question is how to display center coordinates for each object detected in the frame? Thank you.

**Comment by mikel-brostrom** [comment]
I am glad that you liked my repo @abuelgasimsaadeldin!

This:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/a60dcf9300ee7673b7d484e8ebb363b9a6408b81/track.py#L167

outputs the  bounding boxes for all the tracked files.

These are then passed to `draw_boxes` in which they are looped and plotted:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/a60dcf9300ee7673b7d484e8ebb363b9a6408b81/track.py#L46

In this loop you should draw your circles

**Comment by abuelgasimsaadeldin** [comment]
Hi @mikel-brostrom, 

Thank you for the swift reply! yes I did draw my circle under the loop in the  *draw_boxes* function, but the center point is only displayed for 1 object at a time, even though there are multiple objects present in the frame. Attached herewith is a snippet of my code, am I doing something wrong? Thank you again.

![2](https://user-images.githubusercontent.com/68045710/112270919-3c165d80-8cb5-11eb-9789-a9f7eed02a79.png)

**Comment by Sarouch** [comment]
@abuelgasimsaadeldin hello, could you tell me how did you make the class name on the bbox, I only have the id ? Thank you
