### ISSUE TITLE
Hello, I want to know how to train deep sort with my own data. Thank you for your reply

### ISSUE THREAD

**Issue by joe660** [mikel-brostrom/Yolov5_DeepSort_Pytorch#79]
**Hello, I want to know how to train deep sort with my own data. Thank you for your reply**

**Comment by zhongxu-Sun** [comment]
> **Hello, I want to know how to train deep sort with my own data. Thank you for your reply**

Hello, I also want to use this model to achieve similar functions, training my own dataset to achieve identification and tracking, have you achieved it at present? 
How did it happen?

**Comment by mikel-brostrom** [comment]
Hi!

I recommend you to check the Market1501 dataset or Mars dataset and mimic that structure, in that way you could start the training right away based on the orignal repo's instructions.

They are basically comprised of folders with images associated to the same instance object where all the images are of the same size (in the case of Mars for example 128 x 256).
