### ISSUE TITLE
Is it possible for TensorRT model from here?

### ISSUE THREAD

**Issue by PiyalGeorge** [mikel-brostrom/Yolov5_DeepSort_Pytorch#8]
Hi @mikel-brostrom , I've checked your repo, its output is really cool. Currently i have done tensorrt implementation of yolov5 following https://github.com/wang-xinyu/tensorrtx for detecting mobilephones in hand . I would like to implement tracking also for real-time tracking, Is it possible with tensorrt? If yes, do i need to train deepsort model?

**Comment by mikel-brostrom** [comment]
Thank you! 

I am not familiar with TensorRT but from what I understand you should be able to serialize the Deep Sort weights in the same way you did with the Yolov5 weights, of course taking into consideration the architecture differences. The network for deep sort is just comprised of convolutional layers followed by residual blocks and a dense layer so it should be easier to serialize than Yolov5. 

Then you could deserialize them in a  c++ ported version of track.py for real-time tracking

**Comment by PiyalGeorge** [comment]
@mikel-brostrom Thanks. I have trained yolov5 for my custom object detection, Similarly do i need to train 'tracking model' deepsort for tracking my custom object?

**Comment by mikel-brostrom** [comment]
Yes, you need to train the deep association metric. Ideally on a large-scale re-identification dataset containing the classes you want to track

**Comment by Wulingtian** [comment]
我试了yolov5_deepsort的tensorrt版本，大概15ms一帧
