### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aaronrmm** [mikel-brostrom/Yolov5_DeepSort_Pytorch#80]
Please add a license of your choosing to the repo. The [deep sort library](https://github.com/ZQPei/deep_sort_pytorch) you are using has an MIT license. Thanks!

**Comment by mikel-brostrom** [comment]
No. I am not responsible for the respective licenses of the repositories used. It is clearly stated in the REAME that: "For more detailed information about the algorithms and their corresponding licenses used in this project access their official github implementations."

**Comment by aaronrmm** [comment]
Sorry, I missed that and the fact that Yolov5 is GPLv3. Closing
