### ISSUE TITLE
Replace yolov5 model with mask recognition model

### ISSUE THREAD

**Issue by Jackson-leo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#82]
I replaced your yolov5 weight file with my weight file of the mask recognition model. As a result, an error was reported when loading the model.It is "＜AttributeError: Can't get attribute 'C3' on module ‘__main__‘＞". What is the reason？

**Comment by Jackson-leo** [comment]
If you know, please guide me. I'm stuck in this step

**Comment by Jackson-leo** [comment]
I use the windows 10 operating system and create a virtual environment in Anaconda to run this project.Does this environmental impact project run?

**Comment by Jackson-leo** [comment]
I use the window10 operating system and create a virtual environment to run the project in anaconda.Does this environmental impact project run?

**Comment by mikel-brostrom** [comment]
1. Re-clone repo 

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch.git`

2. Move into flder 

`cd Yolov5_DeepSort_Pytorch`

3. create new pip environment

`python3 -m venv /path/to/new/virtual/environment`

4. Activate environment

source /path/to/new/virtual/environment/bin/activate

5. Install repo's requirements

`pip3 install -r requirements.txt`

6. Run the tracker

`python3 track.py --source 0`
