### ISSUE TITLE
yolov5/models/experient.py  Class C3  What is its function？

### ISSUE THREAD

**Issue by Jackson-leo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#83]
Is it used to connect yolov5 and deepsort？I replaced your yolov5 weight file with my weight file of the mask recognition model. As a result, an error was reported when loading the model.

**Comment by mikel-brostrom** [comment]
There can be problems if you try to load a model trained with an old version of this repo. I recommend to retrain if this is the case.
