### ISSUE TITLE
When running the new project, an error is reported that the file is missing

### ISSUE THREAD

**Issue by Jackson-leo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#84]
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

**Comment by TheoTaffin** [comment]
Hi Jackson, I think you did not download the checkpoint. You can find it at this link : https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6. Place ckpt.t7 file under deep_sort/deep/checkpoint/

You can find this instruction and more info in the README as well :)

**Comment by Jackson-leo** [comment]
However, this file is no longer in the checkpoint folder of the project after the author modified it, as it was before

**Comment by mikel-brostrom** [comment]
This file has never been under `deep_sort_pytorch/deep_sort/deep/checkpoint/`. In any of my commits
