### ISSUE TITLE
Hi can you help me ? qt.qpa.xcb: could not connect to display qt.qpa.plugin

### ISSUE THREAD

**Issue by musketeera** [mikel-brostrom/Yolov5_DeepSort_Pytorch#85]
I run your project on remote server without qt, I just want to save the ouput video, but not want to use qt to display. How can I achieve it.
when I run project,it printed this error:

qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/conda/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.

**Comment by yinhao970313** [comment]
if you cannot use qt, you use imwrite() to output the result video.
I use colab to run project but it cannot connect to x server for Linux OS, so imshow is not working, imwrite could be successful

**Comment by mikel-brostrom** [comment]
Disable all the GUI related output such as, imshow(), as all this functionality won't work if you don't have a GUI. Then you can use the `save_img` flag under [this line of code](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/5ca1787611bef84d149fb05868d7122505013c09/track.py#L65) to save the video
