### ISSUE TITLE
Model loading problem

### ISSUE THREAD

**Issue by Jackson-leo** [mikel-brostrom/Yolov5_DeepSort_Pytorch#86]
Is only one class read when loading the model？Can't other classes be displayed?

**Comment by CynicalHeart** [comment]
If you can read the code simple：
```python
    # class 0 is person
    parser.add_argument('--classes', nargs='+', type=int,
                        default=[0], help='filter by class')
```
in track.py [248-250] line

**Comment by mikel-brostrom** [comment]
Add more tracking classes by adding their respective COCO indexes to [this list](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/5ca1787611bef84d149fb05868d7122505013c09/track.py#L251)
