### ISSUE TITLE
Multi Camera box is not following each camera

### ISSUE THREAD

**Issue by berkat28** [mikel-brostrom/Yolov5_DeepSort_Pytorch#88]
Hello,
Thank you so much for making this awesome project!
I have a problem, how to integrate box with many camera?
When i use many camera, the box is synced to all camera.
![Screenshot](https://user-images.githubusercontent.com/77950858/114653249-d1839b00-9d11-11eb-9d80-39202c17604f.png)
It must be like this :
![Screenshot](https://user-images.githubusercontent.com/77950858/114654100-a26e2900-9d13-11eb-97ea-63c790d833d3.png)

Thank you,
Regards

**Comment by HoiBunCa** [comment]
I am also having the same problem, please help me.

**Comment by hdnh2006** [comment]
Did you solve it @berkat28? Please could you help us @mikel-brostrom?

**Comment by berkat28** [comment]
not yet @hdnh2006

**Comment by hdnh2006** [comment]
I could solved it by creating a deepsort object for each stream url in a list. The "problem" then is you have to do the same with other parameters.

There is no change in the performance, similar fps rate is gotten.

Some of my code:

```
# Function for creating deepsort objects
def create_DeepSort_object(cfg):
    my_deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
                            max_dist=cfg.DEEPSORT.MAX_DIST, min_confidence=cfg.DEEPSORT.MIN_CONFIDENCE,
                            nms_max_overlap=cfg.DEEPSORT.NMS_MAX_OVERLAP, max_iou_distance=cfg.DEEPSORT.MAX_IOU_DISTANCE,
                            max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET,
                            use_cuda=True)
    return my_deepsort


# Create as many deepsort objects as cameras
for i in range(len(cameras)):
     deepsort_list.append(create_DeepSort_object(cfg))

# Pass detections to deepsort (put inside [this](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/64c59e17fb570c3626c459f6a0216d8b46a074bd/track.py#L137) for loop)

if blablabla:
     outputs[i] = deepsort_list[i].update(xywhs, confss, new_labels, im0)
else:
     deepsort_list[i].increment_ages()
```

Try to avoid use `deepsort_list = [deepsort]*number_of_cameras` because python create same object in each coordinate of the list, so if you update one object the others will also be updated with same properties.

**Comment by sainivedh** [comment]
Any idea on How to move forward with Multi Camera Multi Object tracking ?. 

Like if the same person goes from cam1 to cam2 model should recognize him as the same person. Any advice/tip would be much appreciated.

Thanks

**Comment by hdnh2006** [comment]
> Any idea on How to move forward with Multi Camera Multi Object tracking ?.
> 
> Like if the same person goes from cam1 to cam2 model should recognize him as the same person. Any advice/tip would be much appreciated.
> 
> Thanks

Please, read my comment...

**Comment by zfs1993** [comment]
> ] if blablabla:
     outputs[frame_idx] = deepsort_list[frame_idx].update(xywhs, confss, new_labels, im0)
else:
     deepsort_list[frame_idx].increment_ages()
it should be this.(change the index i to frame_idx),I think you could provide the whole code and commit it ,it is valuable
