### ISSUE TITLE
Invalid shape for input

### ISSUE THREAD

**Issue by Arhanel** [mikel-brostrom/Yolov5_DeepSort_Pytorch#9]
Hey I am getting an error when trying to run this code, that says: 

RuntimeError: shape '[1, 3, 85, 64, 80]' is invalid for input of size 655360

What did I do wrong :/ ?

**Comment by mikel-brostrom** [comment]
Are you running the tracker on a video?
Could you give me the total error so that I can try to reproduce this?

**Comment by Arhanel** [comment]
![image](https://user-images.githubusercontent.com/56166334/89337443-38d54f80-d69b-11ea-8a19-2fb97c881cea.png)
I was running it on video file and camera. Both gave me the same results.

**Comment by Arhanel** [comment]
Also when I running it on my laptop without GPU it gives me this:
![image](https://user-images.githubusercontent.com/56166334/89387085-483bb380-d702-11ea-9209-d4a2206bfa96.png)

**Comment by mikel-brostrom** [comment]
I generated a dummy video of your frame size (i.e. [85, 64]) but couldn't replicate your error on my Ubuntu 20.04 LTS machine. This piece of software has never been run on a Windows machine as I don't own one. 

However, I recommend you to pull my latest update and try again with the updated requirements.txt

**Comment by Arhanel** [comment]
Cool, now it's working for me. I wonder now if I can train it to track vehicles.

**Comment by mikel-brostrom** [comment]
Sweet!

Yes you can track vehicles. You would need to change the Yolov5 '--classes' argument from 0 to 2 in order to filter out cars. Then  you need to train the deep association metric on a car re-identification dataset
