### ISSUE TITLE
Multiclass detection and name of classes on bbox

### ISSUE THREAD

**Issue by Sarouch** [mikel-brostrom/Yolov5_DeepSort_Pytorch#91]
Hello, Thank you for this repostory.

Could you tell me please, how can I make Track.py detect the 5 classes ? I used another weights file which contains 5 classes, when I run track.py, only class 0 is detected.
I also want to see the names of my classes not only IDs, how can I solve this ?

Regards,

**Comment by mikel-brostrom** [comment]
Add the index corresponding to the respective classes to the list in [this line of code](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/a60dcf9300ee7673b7d484e8ebb363b9a6408b81/track.py#L251)

**Comment by Sarouch** [comment]
> Add the index corresponding to the respective classes to the list in [this line of code](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/a60dcf9300ee7673b7d484e8ebb363b9a6408b81/track.py#L251)

@mikel-brostrom Thank you for your answer, do you mean "...default=[0,1,2,3,4,5], help='filter by class')" ? Because when I put classes = 1 or 2 or 3 it works but only for one class, I want the five classes, thanks

**Comment by mikel-brostrom** [comment]
Yes. Exactly. Add the indexes to the list as in your reply

**Comment by Sarouch** [comment]
And soemone know why the result.txt is like this ? 
![image](https://user-images.githubusercontent.com/40342672/117319803-efb16680-ae8b-11eb-8c6f-c4dd504980ea.png)
 
Thanks

**Comment by Bobur1992** [comment]
> > Yes. Exactly. Add the indexes to the list as in your reply
> 
> @mikel-brostrom Thank youu !!! it works.
> Do you have any idea how can I replace the number of class bu its name please ? thanks again

Hi could you find how to put classes on bounding boxes?

**Comment by Sarouch** [comment]
> > > Yes. Exactly. Add the indexes to the list as in your reply
> > 
> > 
> > @mikel-brostrom Thank youu !!! it works.
> > Do you have any idea how can I replace the number of class bu its name please ? thanks again
> 
> Hi could you find how to put classes on bounding boxes?

@Bobur1992  Hi ! Unfortunately no, I just put the number of classes but not names !

**Comment by Bobur1992** [comment]
> > > > Yes. Exactly. Add the indexes to the list as in your reply
> > > 
> > > 
> > > @mikel-brostrom Thank youu !!! it works.
> > > Do you have any idea how can I replace the number of class bu its name please ? thanks again
> > 
> > 
> > Hi could you find how to put classes on bounding boxes?
> 
> @Bobur1992 Hi ! Unfortunately no, I just put the number of classes but not names !

Thank you for your quick reply
I tried to do the same. But I need to use class name and id for my code. if I display class names(the numbers) combined with deepsort id it is getting confused.
I want to class and id match. But couldn't grt them matched. 
did you display class names for showcase purpose or did you actually want yo use class name and id in your code?

**Comment by mikel-brostrom** [comment]
I worked on a branch for this functionality. You can find it here: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/tree/class_to_txt. I basically saves the class name for each track that the tracker handles. In that way you can access it and print it in **tracker.py**.

**Comment by Bobur1992** [comment]
> I worked on a branch for this functionality. You can find it here: https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/tree/class_to_txt. I basically saves the class name for each track that the tracker handles. In that way you can access it and print it in **tracker.py**.

@mikel-brostrom thank you I really appreciate it.

**Comment by Bobur1992** [comment]
@mikel-brostrom I also needed the confidence to access in output list. I have tried the same procedure as you did for classes.But, I  got a static confidence which doesn't change.It is assigning the confidence when the object  is detected first time and it doesn't change. I would appreciate your help.I want to get bounding box coordinates,track_id,class_id,confidence.

**Comment by Sarouch** [comment]
@mikel-brostrom  thank you very much !!

**Comment by mikel-brostrom** [comment]
Id, class name and confidence now plotted with the bounding box. Check it out under master!

**Comment by hedi1920** [comment]
Does the custom data include train and test and in which of these we make video files (e.g. from 1 to 50). And what about the labels in train.py?
