### ISSUE TITLE
FPS counter

### ISSUE THREAD

**Issue by redogsal** [mikel-brostrom/Yolov5_DeepSort_Pytorch#93]
Hey guys,

Might be a basic question but is there an easy way to add a FPS counter to this detector so that the outputted clip shows the FPS and how it changes for comparison to other detectors?

**Comment by mikel-brostrom** [comment]
You can create a counter under this line of [code](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/a60dcf9300ee7673b7d484e8ebb363b9a6408b81/track.py#L134) You can then use cv2.putText to show the frame index
