### ISSUE TITLE
Two NMS

### ISSUE THREAD

**Issue by wzwb** [mikel-brostrom/Yolov5_DeepSort_Pytorch#96]
Hi，when I read your code, I found there are tow NMS in deepsort. The first is in track.py and the other is in def update() in deepsort.py . I can't understand are these repeat?

**Comment by mikel-brostrom** [comment]
Thank you so much for pointing this out! I missed this totally. The NMS in `update() `under `deep_sort_pytorch/deep_sort/deep_sort.py` is now deleted
