### ISSUE TITLE
error message: 

### ISSUE THREAD

**Issue by fiastros** [mikel-brostrom/Yolov5_DeepSort_Pytorch#98]
I'm currently working on ubuntu 20.10
I have cloned the repositories recursively as stated the readme
I also have isntalled all the requirements of the requirements file
i downloaded a random video of people walking in the streets to test the code but when i launch the command :
"python track.py --source video.mp4" i can a message i think of error:

"QObject::moveToThread: Current thread (0x5628252fb1f0) is not the object's thread (0x562823ae33b0).
Cannot move to target thread (0x5628252fb1f0) "

**Comment by mikel-brostrom** [comment]
A quick search gave me this [result.](https://stackoverflow.com/questions/52337870/python-opencv-error-current-thread-is-not-the-objects-thread) Seems like it could be your case

**Comment by fiastros** [comment]
I was able to solve this problem. 
The issue is with open-cv: for some reason the newest versions of opencv (4.5.2) don't work with this repository. 
but by downgrading to an older version like the 4.1.2 everything works fine !!
the command to downgrade is: 
pip install opencv-python==4.1.2.30
